# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ABC";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/colomon/ABC/archive/499e3aa56d7c1635d26b91b0529939d2e55144ce.tar.gz";
        sha256 = "8d36ff9c0dfa19b5d1e6bd00ac7bbeab7ef4202b8293aae74b64ef094825a3db";
    };
}
