# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-Cow6";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Acme-Cow6-0.0.1.tar.gz";
        sha256 = "0673bfbee9c3ecff05748a630eaee2c0ede5d59ac2feb6ed965cabec32b17146";
    };
}
