# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-Text-UpsideDown";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Acme-Text-UpsideDown-0.0.4.tar.gz";
        sha256 = "7428d311462c510b40146e9af697e0bc302f9801d233422d6533cab928f97260";
    };
}
