# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-ಠ_ಠ";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Acme-_-0.0.1.tar.gz";
        sha256 = "360bc7ce16051831cb98271d3ddc271c32ad1b75087dfa4ea8aca78038b62b82";
    };
}
