# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-WTF";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" rakuPackages."Test-Output" ];
    src = fetchurl {
        url = "https://github.com/Skarsnik/acme-wtf/archive/e53d165d344e810da87e02c59cde2c4c49307d51.tar.gz";
        sha256 = "8ad70296f8dcd78f373cde14b003873ddd76dd7c9861b5f7f8e0183618a4d2d4";
    };
}
