# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-Advent-Highlighter";
    buildDepends = [  ];
    depends = [ rakuPackages."DOM-Tiny" rakuPackages."Pastebin-Gist" rakuPackages."Text-Markdown" rakuPackages."UUID" rakuPackages."WWW" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Acme-Advent-Highlighter/archive/2f32283c153ba9eaddf9df55607441b994ddf479.tar.gz";
        sha256 = "9ff95d2dc2d7c7f34a20f5d5956f5f1e33b4ef43d43718fee22fd9a919a4d324";
    };
}
