# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-Meow";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TA/TADZIK/Perl6/Acme-Meow-0.1.tar.gz";
        sha256 = "b9a0586070f1d5939f7af9b9537b2fc4e3fff35aaeeb0626ac1d2df22e0626d6";
    };
}
