# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-Insult-Lala";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Acme-Insult-Lala-0.0.4.tar.gz";
        sha256 = "514c82d3e50a70b5a1f713ca6a8e09860cf1294e704dca4c1406527ae3456b3e";
    };
}
