# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Acme-Meow";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tadzik/perl6-Acme-Meow/archive/5b1e7553da1686b3a141334a6b1e966daf5e3463.tar.gz";
        sha256 = "7208e3dd8ae13fc68c8e76d1a41c30f5cac4b072a9b38418064f4e99db744cc2";
    };
}
