# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ADT";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/timo/ADT/archive/a423ac781b9762adaeb29e38f30e1c24af379025.tar.gz";
        sha256 = "9675210e1e09f1f35d4055ffcef953e4f072b1089cb5f4548a225571068717c3";
    };
}
