# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "AI-FANN";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perlpilot/p6-AI-FANN/archive/42b89fd2a4f3a6feb4f4fab3b00287cd67ae8da4.tar.gz";
        sha256 = "603b85f385a24156fd9d7c4ee6622f1ab1cf1f0e69547b1e0fc1322e0e8c4e76";
    };
}
