# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-Tarjan";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/finanalyst/p6-Algorithm-Tarjan/archive/c277e1f216dee68cef2c6c9021082990798b9363.tar.gz";
        sha256 = "3bab8ffe8a8f0e240a5c0b00e48ac31e4770ddfaf141998c0104b43268c80c4e";
    };
}
