# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-BloomFilter";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest-MurmurHash3" ];
    src = fetchurl {
        url = "https://github.com/yowcow/p6-Algorithm-BloomFilter/archive/2cecaa4e8aa8cb360625338c2e0ca331f626b424.tar.gz";
        sha256 = "e20db8fea487acd3ee8f9c3d462f1cb703d2943bca5f3f2ebb9bb8ea8438b589";
    };
}
