# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-Elo";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/hoelzro/p6-algorithm-elo/archive/b412f3e037cd83eaa985262908efb917efb8e851.tar.gz";
        sha256 = "4c96022875aeacee0ca52258c0769084fadf444abd218806fec963f038217d11";
    };
}
