# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-SpiralMatrix";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/mj41/Algorithm-SpiralMatrix/archive/854e718582c3ac35698ee6df2913887f64dc9e36.tar.gz";
        sha256 = "3f047cadecdfd4c21bd98670e4a39e99bb1441aaa8eb889da9dcaddce29db63f";
    };
}
