# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-ZobristHashing";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/titsuki/p6-Algorithm-ZobristHashing/archive/a25c61be00261e4d0e998efd9d239738fd7c8570.tar.gz";
        sha256 = "c3758104c72f8120a43e1bd8d07720fc91abac93c4313838348a0ece2bffeeff";
    };
}
