# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-LDA";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TI/TITSUKI/Perl6/Algorithm-LDA-0.0.9.tar.gz";
        sha256 = "e2968b4d1ddc1a44e4d889dbd01717ec78c906c3eed7fc8bd2332cefed3cd050";
    };
}
