# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-Evolutionary-Simple";
    buildDepends = [  ];
    depends = [ rakuPackages."Log-Async" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMERELO/Perl6/Algorithm-Evolutionary-Simple-0.0.8.tar.gz";
        sha256 = "5aaabe09e354735e9ff05fca2b1d201c9c880146ecdd7f1d42e6e98adc9e159a";
    };
}
