# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-Soundex";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/leto/perl6-Algorithm-Soundex/archive/d610a48c923fd2a99346138668649d6b8f06887e.tar.gz";
        sha256 = "1c700d95b06c57b1239dd1f93a4af5ad38d028da6fcc4bb7bcb145d7f2e6e8ce";
    };
}
