# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-SkewHeap";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JE/JEFFOBER/Perl6/Algorithm-SkewHeap-0.0.1.tar.gz";
        sha256 = "b31072f61fd8edd725572bd70971401c22f32c86197f01d1e62d179d11623f49";
    };
}
