# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-Treap";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/titsuki/p6-Algorithm-Treap/archive/33871ab492d11676b693e520460f5059db62c5ec.tar.gz";
        sha256 = "b3787b9e9061d1bb0b7793e522867175a681ccacbf48c4b4f302bbfaa861bbc7";
    };
}
