# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-Heap-Binary";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CO/CONO/Perl6/Algorithm-Heap-Binary-0.0.1.tar.gz";
        sha256 = "caf50cfd3d042358f845bb6dacf44bc61f30eae72b3b569f23bf72d4da68fbfa";
    };
}
