# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-KdTree";
    buildDepends = [  ];
    depends = [ rakuPackages."NativeHelpers-Array" ];
    src = fetchurl {
        url = "https://github.com/titsuki/p6-Algorithm-KdTree/archive/b2328650e81f781670c89984d2a43a94b6dce93c.tar.gz";
        sha256 = "87dda6e5a1f4752520edd6fdf248ef712765294a2176fafbec97af775b0d5070";
    };
}
