# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-GooglePolylineEncoding";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SC/SCIMON/Perl6/Algorithm-GooglePolylineEncoding-1.0.3.tar.gz";
        sha256 = "5efee0d736358685214bd4645f41b7ba9364f73ff111dfd74fc3fa1318b0ef7f";
    };
}
