# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-Kruskal";
    buildDepends = [  ];
    depends = [ rakuPackages."Algorithm-MinMaxHeap" rakuPackages."Algorithm-SetUnion" ];
    src = fetchurl {
        url = "https://github.com/titsuki/p6-Algorithm-Kruskal/archive/48bd7154436e94e0bcc64fc80686c52df3b22a87.tar.gz";
        sha256 = "203670ef4391d3ea2731e4e1bbcb5c79c94330f0c431bf1abb32eb755545ddbc";
    };
}
