# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Algorithm-TernarySearchTree";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/titsuki/p6-Algorithm-TernarySearchTree/archive/6d9abcc8b6c416b2ac55b1a37633b4730c8d91f9.tar.gz";
        sha256 = "bb956be988d2a5a50f19e557f2104853fb3019f04c6db38c1682fd2b28b346ec";
    };
}
