# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Amazon-DynamoDB";
    buildDepends = [  ];
    depends = [ rakuPackages."AWS-Session" rakuPackages."Cro-HTTP" rakuPackages."HTTP-UserAgent" rakuPackages."JSON-Fast" rakuPackages."String-CRC32" rakuPackages."WebService-AWS-Auth-V4" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/Amazon-DynamoDB-0.3.tar.gz";
        sha256 = "5df0a92e00d556f59d100252ad43e6334c0964c5f49ef39f7bece12f020e117f";
    };
}
