# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ANTLR4-Grammar";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JG/JGOFF/Perl6/ANTLR4-Grammar-0.6.2.tar.gz";
        sha256 = "1996e1eabc9dbf2835ff7f793a75d6688088fd95e19cde460d620d81f6ff7873";
    };
}
