# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ANTLR4-Grammar";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/drforr/perl6-ANTLR4/archive/ffa588bd94ccf02660a5b05c16b2199f9d58cf89.tar.gz";
        sha256 = "2fed6faaa6c4919ec297cb33691e012365d1cf10faa40c20bec826ca13182062";
    };
}
