# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Apache-LogFormat";
    buildDepends = [  ];
    depends = [ rakuPackages."DateTime-Format" ];
    src = fetchurl {
        url = "https://github.com/lestrrat/p6-Apache-LogFormat/archive/46b65c453f1e47999d4895a2ad6ffe6caaca8c3b.tar.gz";
        sha256 = "f65eff2460f4ba6410e6bad09e6f7277d0572b343bb89be8fc0e1d0a472013f2";
    };
}
