# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "API-USNavalObservatory";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP-Client" rakuPackages."JSON-Pretty" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://github.com/cbk/API-USNavalObservatory/archive/e5b31e42d334eebdc110812b0d82dfcf975497ef.tar.gz";
        sha256 = "64c2aed4130598cca9e0317d5169b8aa0672fd3e2a602de40ea19a047e8f0210";
    };
}
