# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "API-Discord";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-WebSocket" rakuPackages."URI-Encode" ];
    src = fetchurl {
        url = "https://github.com/shuppet/p6-api-discord/archive/47cc99367a28efa8af6962636a355bf7556f35e3.tar.gz";
        sha256 = "0c23362da100575289dfc3a10f2ea6dc5c356ddbb4c688552fd0695dbd20cfe9";
    };
}
