# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Nopaste";
    buildDepends = [  ];
    depends = [ rakuPackages."Pastebin-Gist" rakuPackages."Pastebin-Shadowcat" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-App-Nopaste/archive/05b878a70e6e56ab7fc83b634ee54c9b7cb54011.tar.gz";
        sha256 = "43fa84321396450adaeee6f86da0defd7c8efe43f7784591ab6c75a06d6bd7a1";
    };
}
