# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Tasks";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest-SHA1-Native" rakuPackages."File-Temp" rakuPackages."P5getpriority" rakuPackages."P5localtime" rakuPackages."Term-ReadKey" rakuPackages."Term-termios" rakuPackages."Terminal-ANSIColor" rakuPackages."YAMLish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMASLAK/Perl6/App-Tasks-0.0.17.tar.gz";
        sha256 = "58282e5e9e81cd7a360ff2dca9602d828654e885b9b830d99fec827a8d068f25";
    };
}
