# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-FindSource";
    buildDepends = [  ];
    depends = [ rakuPackages."Getopt-Advance" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/araraloren/perl6-app-findsource/archive/2a10109a83d20600ea57fe048320052d15a6a2fc.tar.gz";
        sha256 = "788ad3898a6fa8e721ee2f826cb12804928bbcc8748e34dacbb29b6d9711e83f";
    };
}
