# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-FindSource";
    buildDepends = [  ];
    depends = [ rakuPackages."Getopt-Advance" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AL/ALOREN/Perl6/App-FindSource-0.0.6.tar.gz";
        sha256 = "f4084fe3b67ede9c9aa0fb5946aa943edae6106470dc651a304d33aaa0b9c0b5";
    };
}
