# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-p6tags";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Find" ];
    src = fetchurl {
        url = "https://github.com/stmuk/p6-app-p6tags/archive/f6556090512b4c56384a26823912f15c2e08c62a.tar.gz";
        sha256 = "9c927d15ea22c5fae5ec9cc52440b17af63abaab3dcca6573bd486753ecfcbb5";
    };
}
