# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-snippet";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Which" rakuPackages."Getopt-Advance" rakuPackages."PathTools" rakuPackages."Pluggable" rakuPackages."Readline" ];
    src = fetchurl {
        url = "https://github.com/araraloren/perl6-app-snippet/archive/20333f22fdd5a01cdeab860f2968688772d12f5e.tar.gz";
        sha256 = "05cffcbb29a27a43d211595f35ebca1edf03387c9654d953a7ce5b22ef49466f";
    };
}
