# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Rakuman";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" rakuPackages."File-Which" rakuPackages."JSON-Fast" rakuPackages."Pod-To-Anything" rakuPackages."String-Fold" rakuPackages."Terminal-ANSIColor" rakuPackages."Text-BorderedBlock" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/App-Rakuman-0.1.0.tar.gz";
        sha256 = "526713bb7b31d2e60191fc9487416a173d5848da403b3b4678a63631b4fa441f";
    };
}
