# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Pray";
    buildDepends = [  ];
    depends = [ rakuPackages."Image-PNG-Portable" rakuPackages."JSON-Tiny" ];
    src = fetchurl {
        url = "https://github.com/raydiak/pray/archive/33077fac681b0a2a19823960e7b780656a5c93aa.tar.gz";
        sha256 = "20d1d1f7f8e4d70e14b4974c14a315bcf725fb894409a79094e940859485b974";
    };
}
