# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-OrgSleep";
    buildDepends = [  ];
    depends = [ rakuPackages."Inline-Perl5" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/AlexDaniel/orgsleep/archive/c7ac458a1fde84c3a9eda0e86a5df96dcecd820d.tar.gz";
        sha256 = "72d4a002bb1adaa82bbc349f44b944fb160d4881752b6a9da152dcdc8d36d464";
    };
}
