# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Prove6";
    buildDepends = [  ];
    depends = [ rakuPackages."Getopt-Long" rakuPackages."TAP" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/L/LE/LEONT/Perl6/App-Prove6-0.0.12.tar.gz";
        sha256 = "a9aa41050938729db68c93a002705ecfe383fd8859cb5bc9c79160d83eb0df47";
    };
}
