# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Assixt";
    buildDepends = [  ];
    depends = [ rakuPackages."CPAN-Uploader-Tiny" rakuPackages."Config-Parser-toml" rakuPackages."Config" rakuPackages."Dist-Helper" rakuPackages."Hash-Merge" rakuPackages."I18n-Simple" rakuPackages."IO-Path-Dirstack" rakuPackages."Pod-To-Markdown" rakuPackages."Pod-To-Pager" rakuPackages."String-Fold" rakuPackages."Terminal-Getpass" rakuPackages."Version-Semantic" rakuPackages."zef" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/App-Assixt-1.0.0.tar.gz";
        sha256 = "2beecb62925f4e96c588faefaf8026494217ca79d0661190631749a25e3b3177";
    };
}
