# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-AizuOnlineJudge";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" rakuPackages."Terminal-Getpass" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TI/TITSUKI/Perl6/App-AizuOnlineJudge-0.0.3.tar.gz";
        sha256 = "03e020c4e6011e329d385be2fc11e124d114b32b6c510b37413bcbaf285d78a4";
    };
}
