# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Squashathons";
    buildDepends = [  ];
    depends = [ rakuPackages."IO-Socket-SSL" rakuPackages."LWP-Simple" ];
    src = fetchurl {
        url = "https://github.com/JJ/p6-app-squashathons/archive/570d5ee3395a9a96a711882d2e97889b041cecbb.tar.gz";
        sha256 = "14695ed28125e663a2176df6fa8390069f5296b1fa067ce68b265465b0de7361";
    };
}
