# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-MPD-AutoQueue";
    buildDepends = [  ];
    depends = [ rakuPackages."Config" rakuPackages."MPD-Client" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/App-MPD-AutoQueue-0.1.1.tar.gz";
        sha256 = "50c310cfcc8ae23871aaa44393dc1a5b9556676b781fc82e759082c726814018";
    };
}
