# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-SixLib";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/cygx/6lib/archive/78909b34ed4794c786f97aa82326ac853b0d9ed8.tar.gz";
        sha256 = "58f351509290a0de292c2cf13410837a7aa8ba87d84056af7991de716cadd240";
    };
}
