# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-AizuOnlineJudge";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" rakuPackages."Terminal-Getpass" ];
    src = fetchurl {
        url = "https://github.com/titsuki/p6-App-AizuOnlineJudge/archive/61054ef6ea9ad3be7fe836955e9ff7f47cca943e.tar.gz";
        sha256 = "a1c1ae85ab7cdb867ecc203b463ce680138840032dcdc59c560e3599d952d3c8";
    };
}
