# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Whiff";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Which" ];
    src = fetchurl {
        url = "https://github.com/Altai-man/perl6-app-whiff/archive/00d7cee57a46c240b03b3a8d48603070f2a05fc3.tar.gz";
        sha256 = "ba36b79fc8d99c61b9ceaff24ae65e327d6b891b7b70778994503d13d865dc3c";
    };
}
