# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Uni";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CO/COKE/Perl6/App-Uni-1.0.1.tar.gz";
        sha256 = "5f345549c73ee8463bcfdaee577d7af2c64b77c9ca138d67f79d73487b890779";
    };
}
