# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "App-Mi6";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Find" rakuPackages."Getopt-Kalkin" rakuPackages."JSON-Pretty" rakuPackages."License-Software" rakuPackages."Pod-To-Markdown" rakuPackages."Shell-Command" ];
    src = fetchurl {
        url = "https://github.com/kalkin/Ddt/archive/103905441f43a50e31f8665cb04b026358850d7b.tar.gz";
        sha256 = "f36fda99a18fa7c32a518dc9a30a4fbb5c076d8d2d6aa40a7189d3bef51d38ad";
    };
}
