# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Archive-Libarchive";
    buildDepends = [  ];
    depends = [ rakuPackages."Archive-Libarchive-Raw" rakuPackages."NativeHelpers-Blob" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Archive-Libarchive-0.0.15.tar.gz";
        sha256 = "41da3d904c6db80b6b97abb7fb41a6ae0fa44eaaa14c68ae5972002c29f6dbbf";
    };
}
