# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Archive-Libarchive-Raw";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Archive-Libarchive-Raw-0.1.0.tar.gz";
        sha256 = "d9f6375d03ec3464a8bb6561959ebbf0b36e2b448577a973d8262e620f8b2f7d";
    };
}
