# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Archive-SimpleZip";
    buildDepends = [  ];
    depends = [ rakuPackages."CompUnit-Util" rakuPackages."Compress-Bzip2" rakuPackages."Compress-Zlib" rakuPackages."Compress-Zlib-Raw" rakuPackages."IO-Blob" ];
    src = fetchurl {
        url = "https://github.com/pmqs/Archive-SimpleZip/archive/50ac4e0c876e95dbc167ecf295c52e3028662452.tar.gz";
        sha256 = "d497debacff99245e76f3f7c096715d97d6729da9282921b65ea94484be82da0";
    };
}
