# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Archive-Libarchive-Raw";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Archive-Libarchive-Raw-0.0.10.tar.gz";
        sha256 = "ec77b382a02324c0a03c17776e3213f3fbae0a5ce2de9e5af16d027cce2ffc41";
    };
}
