# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Aria";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/palapitta/Aria/archive/5ac513894a39beb392dda282afa83114cbbba028.tar.gz";
        sha256 = "6234bc5f37ac48be2045ce60d5ae72e3a8cdaf80a9588c6b287e76fe4701a2c6";
    };
}
