# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ArrayHash";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/ArrayHash-0.4.tar.gz";
        sha256 = "c0e5bd3e91280eb39f85bc46d48cbb4bf5eb36b35f8eef811f398f2d1f1a5e7f";
    };
}
