# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ASN-BER";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Altai-man/ASN-BER/archive/dc724ee5d6c6a0724437c59f3c9804a3d78180f4.tar.gz";
        sha256 = "6a61409adb6df0a4c351d7c666ab4fa7626cb506d411cdde36a267cc5469d1ef";
    };
}
