# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ASN-META";
    buildDepends = [  ];
    depends = [ rakuPackages."ASN-BER" rakuPackages."ASN-Grammar" rakuPackages."Type-EnumHOW" ];
    src = fetchurl {
        url = "https://github.com/Altai-man/ASN-META/archive/1957cda0401e0ea692773b333ced1fc591ca0b53.tar.gz";
        sha256 = "abe314f83c4f7d3c7b9dea1246e7e1875075cd74044ae99ba166c2effb2d164f";
    };
}
