# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ASN-Grammar";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Altai-man/ASN-Grammar/archive/abb5b5cd51c11b28676325eeedc16243189df999.tar.gz";
        sha256 = "ee983fab8c1652803f6237b9474e1f519f71a05fdb38213fa96e6185cd5c044c";
    };
}
