# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Async-Command";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ML/MLDEVINE/Perl6/Async-Command-0.1.1.tar.gz";
        sha256 = "98fb7d0056b9e6d6d60b6352478c69f819a1add3adbbfef9bfff5efa3b4eb95c";
    };
}
