# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "AttrX-Mooish";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/V/VR/VRURG/Perl6/AttrX-Mooish-v0.7.3.tar.gz";
        sha256 = "3eeb6dc1f87fe72f0599ce2bc72729073c49e53c1f2350af96e6ec88fde20669";
    };
}
