# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "AttrX-Mooish";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/V/VR/VRURG/Perl6/AttrX-Mooish-v0.7.0.tar.gz";
        sha256 = "8e60b65b4aca18306802ca2ebc140fca93886ed4549c800b90c7fd93c349ca90";
    };
}
