# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Attribute-Predicate";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Attribute-Predicate-0.0.2.tar.gz";
        sha256 = "5614976ca85128d0adbfa6baaf767d69f7975bf076ca3fa0414e3e9797d8f4e9";
    };
}
