# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "AttrX-Lazy";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/pierre-vigier/Perl6-AttrX-Lazy/archive/8d9b1f91db88ba5223b5b82126958f7433c427b2.tar.gz";
        sha256 = "38e7db59997253969a93054a2915a2f6980177a497530642bbd01189d3e97e4c";
    };
}
