# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Audio-Liquidsoap";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Which" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Audio-Liquidsoap-0.0.8.tar.gz";
        sha256 = "b790d5da9405626dd3c46b449ef66206451dee04bf6f29241bfbca35d4e64a33";
    };
}
