# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Audio-Silan";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Which" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Audio-Silan-0.0.7.tar.gz";
        sha256 = "e4c80c9be5220f8b60e708688fb4cc416f3460ca37ba3490d682a5b7c4ddb158";
    };
}
