# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Audio-PortAudio";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Perl6-Noise-Gang/Audio-PortAudio/archive/a07dd3d9598ece3c9db28c58d2ad0f6195871990.tar.gz";
        sha256 = "4888ddd924609aca7f78aa4bcbe4ae542072bf0046788960f6a64c30a75df971";
    };
}
