# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Audio-PortMIDI";
    buildDepends = [  ];
    depends = [ rakuPackages."Util-Bitfield" ];
    src = fetchurl {
        url = "https://github.com/Perl6-Noise-Gang/Audio-PortMIDI/archive/f2f2884db2014849435f425433b6a63ed6f44c0d.tar.gz";
        sha256 = "16e0924f5ad5088490ac22fb3883205feb10e30fafb535283f680a4ea5e15925";
    };
}
