# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Auth-PAM-Simple";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Auth-PAM-Simple/archive/964a8bb2e1cdf11e9989f4e334f1cac28690d2f4.tar.gz";
        sha256 = "7572acf5b495559ef7a585912f13b043ce41f0a9b71c22e1c255001eab2dcd94";
    };
}
