# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "AVL-Tree";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TB/TBROWDER/Perl6/AVL-Tree-0.0.1.tar.gz";
        sha256 = "32173601c14ae5129c2312ac17bbd02c3b02f361927491dbb211d77c0a711acc";
    };
}
