# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Avolution-Emoji";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/XiKuuKy/Avolution-Emoji/archive/4db4ec762c65de97f47583b8c6a72c9799ff5933.tar.gz";
        sha256 = "d0f5ac1723204c081b4d83e066ab4bb20ae3fa58e76a07f8003fbcc6f03bb598";
    };
}
