# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Avro";
    buildDepends = [  ];
    depends = [ rakuPackages."Compress-Zlib" rakuPackages."JSON-Tiny" ];
    src = fetchurl {
        url = "https://github.com/sylvarant/Avro/archive/297c6aba75971fcd4dcc6a841044e2de63849f3d.tar.gz";
        sha256 = "cd8c45df0407fa4facb092f3e5979447f721193be3e475513706a1805d219d72";
    };
}
