# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "AWS-Session";
    buildDepends = [  ];
    depends = [ rakuPackages."Config-INI" rakuPackages."DateTime-Format-W3CDTF" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/AWS-Session-0.7.tar.gz";
        sha256 = "c06107a18f0a58e43babf486fcdf0d0c9b297814d4011fadcc59fbfcfd6fec38";
    };
}
