# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Backtrace-AsHTML";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/moznion/p6-Backtrace-AsHTML/archive/93b46da52922cc686a69163ceb96649b65579032.tar.gz";
        sha256 = "5514c60562d844be8fde5a3f983b848f7d5fba499ec9adc8c4aebc36819ccb6c";
    };
}
