# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Bailador-Plugin-NamedQueries";
    buildDepends = [  ];
    depends = [ rakuPackages."Bailador" rakuPackages."DBIx-NamedQueries" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MZ/MZIESCHA/Perl6/Bailador-Plugin-NamedQueries-0.1001.tar.gz";
        sha256 = "61d407432c3428caff33fc5a58868139aeb8ada892a92befe4a04edd709c5321";
    };
}
