# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Base64-Native";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/Base64-Native-p6/archive/23c93f8f9fe5031870abd1ffb7e17b7943651587.tar.gz";
        sha256 = "0cdaf70ada67f7016ab0127ab6ee4764300156c7289b19c69c450e5a22f70904";
    };
}
