# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "BDD-Behave";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/G/GD/GDONALD/Perl6/BDD-Behave-0.0.3.tar.gz";
        sha256 = "f63a6f93508c6f2a5c5e5735f00c4012116f2fc7eca291b1136e8e094e191456";
    };
}
