# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Binary-Structured";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/avuserow/perl6-binary-structured/archive/ca12905a688d927c5df143cf1de4ce38ddbb2724.tar.gz";
        sha256 = "f0484520224020fded6022dbf111dad3643e47066450aa5f0f77249eabd1abfe";
    };
}
