# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Bio-ViennaNGS";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/mtw/Perl6-Bio-ViennaNGS/archive/d6bce4bd07c179f1d074611fb7d48a2b97ac7d97.tar.gz";
        sha256 = "537a8d184fa6c7ac0391087936c76c5b3b16d3581c5fc608742680491b31874c";
    };
}
