# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "BioPerl6";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" ];
    src = fetchurl {
        url = "https://github.com/cjfields/bioperl6/archive/dcf2c56f7871820b767ec274c5c7f8a7347d1d01.tar.gz";
        sha256 = "6fe59e0b49e883ca04cca82071894be380c6dd400e39f16f2b4d440218e4efea";
    };
}
