# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Bitcoin-RPC-Client";
    buildDepends = [  ];
    depends = [ rakuPackages."Base64-Native" rakuPackages."Data-Dump" rakuPackages."JSON-Fast" rakuPackages."LWP-Simple" rakuPackages."Slippy-Semilist" rakuPackages."WWW" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/B/BR/BRAKMIC/Perl6/Bitcoin-Client-0.0.2.tar.gz";
        sha256 = "1ea80cd4265e5821ef9050b24480a3b000332401d13ed35357edf024a1501920";
    };
}
