# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "BitEnum";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/BitEnum-0.1.tar.gz";
        sha256 = "d2e2a45ac7b79d6c456fa3878153bbbb32a6ed06c594c2585e7764f9efbab7e9";
    };
}
