# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Bits";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Bits-0.0.2.tar.gz";
        sha256 = "1c44882ce085185240413f7f4f136176c656229669a8402896e6cc54330aed07";
    };
}
