# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Blin";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Directory-Tree" rakuPackages."File-Temp" rakuPackages."JSON-Fast" rakuPackages."Whateverable" rakuPackages."Zef" ];
    src = fetchurl {
        url = "https://github.com/perl6/Blin/archive/0b12bc0b33f2e47ebb7c3669abf1f690a173d9ee.tar.gz";
        sha256 = "9709c6edaca9407d6fa20a70693e3f36a95dce6e9a96cbbaf4d827bda95757ff";
    };
}
