# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Brazilian-FederalDocuments";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/paulohrpinheiro/Brazilian-FederalDocuments/archive/f0963ba98008aa9170d5a7dde4a8fde54daffbaa.tar.gz";
        sha256 = "250b084fec65066d7262305a5de10bb3d7e1bbf0bd31ebd19301d910d7af8b04";
    };
}
