# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Build-Graph";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Leont/build-graph6/archive/ec807d1da46cc00e031e2e856d0a18cbe454ee99.tar.gz";
        sha256 = "605ed725bf92e39a5700a6690bd1c460788fdf5ff119918bdba4ae981b3b5d68";
    };
}
