# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cairo";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/timo/cairo-p6/archive/79c03ecaa23281f42d220e0e937df3c88e423ae2.tar.gz";
        sha256 = "607a5ff15d44d6af9c561d35c5df86c4b1bab9591c81b2f2827b718e42a9c7d3";
    };
}
