# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Calculator";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/manwar/p6-Calculator/archive/e707645a77a17696171124183aa9a42310ebc417.tar.gz";
        sha256 = "d5b4abf565052905f1e68035eeee067ebbf7524c05efad2e37b5db12c714358a";
    };
}
