# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CamelPub";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" rakuPackages."DBIish" rakuPackages."HTML-Parser-XML" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/D/DO/DONPDONP/Perl6/CamelPub-0.2.6.tar.gz";
        sha256 = "1485079d28db679a3e45cafb38c165ee144b73d6185714417a0cd3ab4e864c9a";
    };
}
