# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Canoe";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AL/ALOREN/Perl6/Canoe-0.0.3.tar.gz";
        sha256 = "52d6a0ce7e8e3770cc9952215587cb7cb1a740312c92439381b54aae7cd887ff";
    };
}
