# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CCChart";
    buildDepends = [  ];
    depends = [ rakuPackages."CCLog" rakuPackages."Cairo" ];
    src = fetchurl {
        url = "https://github.com/ccworld1000/CCChart/archive/4bbd8db326466c5464573b5b53a42f03537c8817.tar.gz";
        sha256 = "74933c1a50ae61fd17ec4c367019f5348873b6add185accce303da7fce134697";
    };
}
