# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CCLog";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ccworld1000/CCLog/archive/98fe66d7c76746451af826636ec4561c6e188130.tar.gz";
        sha256 = "134d5a72c329925bc3b0e7e836831d727480301ab281922603b2caab16e30384";
    };
}
