# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Channel-Pauseable";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TH/THINCH/Perl6/Channel-Pauseable-1.0.0.tar.gz";
        sha256 = "0bf487d5dd9472302deaeebeb40be571a55cb5bd37739378d675de03cef3e0bb";
    };
}
