# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CheckSocket";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/CheckSocket-0.0.6.tar.gz";
        sha256 = "712b00dbf3098b3bd1f7a277e4a798e6f44f00fc56af6eecad5061ee5a3a3a6e";
    };
}
