# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Chess";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/grondilu/chess/archive/e411908b2d26af86e89e8ebb355ea8d59559bcdc.tar.gz";
        sha256 = "e629776a5f6cf7970fbb77bbb0269048cb1445f63e1ade4e18795cfa07e8e0f9";
    };
}
