# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Chronic";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Chronic-0.0.7.tar.gz";
        sha256 = "d4adb6c3566dba09d04e4df98c4b6c0ab6852188b3bccad11af1b713f8588040";
    };
}
