# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CI-Gen";
    buildDepends = [  ];
    depends = [ rakuPackages."Config-INI" rakuPackages."Getopt-Long" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SH/SHLOMIF/Perl6/CI-Gen-0.0.2.tar.gz";
        sha256 = "5230b07d8f8d60b566c5e2eb5a1d56799778c336f241cc481730dc44aae79528";
    };
}
