# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Class-Utils";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/sirrobert/Class-Utils/archive/61f0ade3505525e13ed8808b8d844426fb15d413.tar.gz";
        sha256 = "02658b94d1034047b59ae71b35c9e0126408aa1c8c28517b2784c0197395c0cc";
    };
}
