# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ClassX-StrictConstructor";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tadzik/ClassX-StrictConstructor/archive/d9bfd03b379293039735df635763760976dbe9e1.tar.gz";
        sha256 = "e2e7265ad41d187ae08128537f53dee9319d57b2cc4adcb990cad7d804272db5";
    };
}
