# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Clean";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-clean/archive/fefb5ed2602c5ddaf6118d1a756513e68db3e2f3.tar.gz";
        sha256 = "0fb537572f189c48e95380ca2fea551f446edf055f31cca3759353d602c5ee0a";
    };
}
