# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Clifford";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/grondilu/clifford/archive/1d4905ce9c6a795caec90609d20db8131f2c0ed0.tar.gz";
        sha256 = "ea3cada4842c5efae6cbebff742764b2f21248ec14fd46315eca7308e2ecb297";
    };
}
