# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cofra";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Headers" rakuPackages."HTTP-Status" rakuPackages."JSON-Fast" rakuPackages."Path-Router" rakuPackages."Smack" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/Cofra-0.2.0.tar.gz";
        sha256 = "762c6dd0aa857ffeb9d05acf2796028e81ed570a10c0d43e873efafc6298be9d";
    };
}
