# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Color-Named";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HO/HOLLI/Perl6/Color-Named-1.001002.tar.gz";
        sha256 = "5071579eda97bace11369368ea6c4ebc603932157553d1de4fff715eb1a0e1cb";
    };
}
