# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Color-Names";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HO/HOLLI/Perl6/Color-Names-1.001003.tar.gz";
        sha256 = "30c97e4fbc00d0b8c75dff6b3ca7417edc4316fe6213e9d43dbc89646babc222";
    };
}
