# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Colorizable";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/U/UZ/UZLUISF/Perl6/Colorizable-0.1.1.tar.gz";
        sha256 = "02e426d62b2a5aa96362202e733df57b434346d32c764869703fffe6c4dcc194";
    };
}
