# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CommonMark";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JG/JGOFF/Perl6/CommonMark-0.0.5.tar.gz";
        sha256 = "7d65a498c5c53cafdfee3c68aa3cc7ffd1b7fc26f796bc0aa84f212087cf9fc0";
    };
}
