# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Compress-Snappy";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/avuserow/perl6-compress-snappy/archive/6f0eea0b175043ccb5eca1899165ccc3dd5c539b.tar.gz";
        sha256 = "668ac1d40edee832af2a0636095a5e7ba038fb628adb7fab84af1264a9865a25";
    };
}
