# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Compress-Bzip2-Raw";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Altai-man/perl6-Compress-Bzip2-Raw/archive/0d6db18b4557b3f33e488c8c8bafd4bba0f8f1b8.tar.gz";
        sha256 = "7f0cfb225f22fe408c0c519f8d9bc1ebd3d6a514917b4c42a7ad009a9b2a9eab";
    };
}
