# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Compress-Zlib";
    buildDepends = [  ];
    depends = [ rakuPackages."Compress-Zlib-Raw" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Compress-Zlib/archive/4c8eecb7cfcf64ba84c1df54a92ddb6af5e56802.tar.gz";
        sha256 = "18404fc70d766ecf02994f837be86067875c30b8e14090cad94e8668edaab02e";
    };
}
