# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CompUnit-Util";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/LLFourn/p6-CompUnit-Util/archive/39ffd1de0c768881f18aef2a6a225a998e194965.tar.gz";
        sha256 = "8ccbcf0203206f3b6a5ba4150585bc00f917e22a6e1a4b6594af6f7d79606337";
    };
}
