# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Compress-Bzip2";
    buildDepends = [  ];
    depends = [ rakuPackages."Compress-Bzip2-Raw" ];
    src = fetchurl {
        url = "https://github.com/Altai-man/perl6-Compress-Bzip2/archive/ef34605ed5d055c1fafb225bd9a29e47bd14bb39.tar.gz";
        sha256 = "aab2be27624820340e310fd54c0f6773f5b2aa6763b8a04fdf573312bc9524f8";
    };
}
