# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Concurrent-Iterator";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jnthn/p6-concurrent-iterator/archive/3847868b75afd2cdc69612bc2fbb2ec842f7be6f.tar.gz";
        sha256 = "ea1d0545c82d96be97329e70b003f5f942546628144b410203cccfd3b21ebcdc";
    };
}
