# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Concurrent-Trie";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/Concurrent-Trie-1.1.tar.gz";
        sha256 = "e27062f261df02d2edff6b56b18aa9387e0cc5b3a85eb9dc30120a0dbdbaa7b2";
    };
}
