# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Concurrent-Stack";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/Concurrent-Stack-1.2.tar.gz";
        sha256 = "ae1d6723e58b48428f03710cc726bd6b9bfa93e4655b0f3115b2bb2ef7608135";
    };
}
