# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Concurrent-Channelify";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/gfldex/perl6-concurrent-channelify/archive/6d2f2e60beea6e991e24fa2541331e3f098f6f76.tar.gz";
        sha256 = "81e5f4c565ca8d0acc1fd73cb863d02f6e5a2928b65cd5567c57da88402da302";
    };
}
