# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Concurrent-PChannel";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/V/VR/VRURG/Perl6/Concurrent-PChannel-0.0.2.tar.gz";
        sha256 = "6a767e18e802aa3d96096e7d41309369d06291277acd2ca6bd68400a9d7f1cce";
    };
}
