# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Config-TOML";
    buildDepends = [  ];
    depends = [ rakuPackages."Crane" ];
    src = fetchurl {
        url = "https://github.com/atweiden/config-toml/archive/5a6dbd31340629d9bf53af230b7dbd6ac3faa673.tar.gz";
        sha256 = "6e86d8d6a9ad25e5f37e2521a43fc5e659b25da799721911de2c895465434853";
    };
}
