# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Config";
    buildDepends = [  ];
    depends = [ rakuPackages."Hash-Merge" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Config-2.1.0.tar.gz";
        sha256 = "d2df36cd34d4a8a0dd12667ea5f0e51c95f952e34868947eb0da056fcce799a1";
    };
}
