# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Config-Parser-yaml";
    buildDepends = [  ];
    depends = [ rakuPackages."Config" rakuPackages."YAMLish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Config-Parser-yaml-1.0.1.tar.gz";
        sha256 = "b8282cec28202c5c8729b51ea002f7abb62c72267b54260bcdf2e623ec5e75f8";
    };
}
