# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Config-JSON";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Config-JSON/archive/84b9a5617a0f6f4c277f17366f613e246204f3e5.tar.gz";
        sha256 = "d6ebdfb649146aaa877097856196d8e041cf4a7f2e88c9d5ac4c6731aa3f054b";
    };
}
