# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Config-Netrc";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Altai-man/perl6-Config-Netrc/archive/a0d8849dcaf66e21435bf8a0fa5a102f54f16b16.tar.gz";
        sha256 = "60e27bd6672ee89469a55fa8176dddf113210a2f10d8d417c4b6e3f4e31fc84e";
    };
}
