# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Constants-Net-If";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/G/GA/GARLANDG/Perl6/Constants-Net-If-0.0.1.tar.gz";
        sha256 = "3cc5736797f86f4fade0a691657f37c00c18a4cd8454dc253d75529db5f873c8";
    };
}
