# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Constants-Sys-Socket";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/G/GA/GARLANDG/Perl6/Constants-Sys-Socket-0.0.2.tar.gz";
        sha256 = "6e31472ed8a3588a815772edfa0bd414897f4bc1e29674751ee30d725c857832";
    };
}
