# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Control-Bail";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/skids/perl6-Control-Bail/archive/3e6ab6c3bab9176a44476bd0883ba99205306400.tar.gz";
        sha256 = "b0b179ce4ca8336c0fda7719a525b7d03c0e661db69c221f7d18244366fcdf33";
    };
}
