# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CPAN-Uploader-Tiny";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Tinyish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SK/SKAJI/Perl6/CPAN-Uploader-Tiny-0.0.6.tar.gz";
        sha256 = "6de47694f0eb6c3239fdb81d4a7420d9d9ec16b0a9092f50ad0f7415ceb10176";
    };
}
