# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-HTTP-Session-Redis";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" rakuPackages."Redis-Async" ];
    src = fetchurl {
        url = "https://github.com/croservices/cro-http-session-redis/archive/adfe87c8a7a00e548ff0d46d027441c39de0bd85.tar.gz";
        sha256 = "cfffcce8391a2c3ffe9038fb2ff53a7b599bcff419fd6140cac0df5018c47124";
    };
}
