# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-H";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-Core" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/G/GA/GARLANDG/Perl6/Cro-H-0.0.2.tar.gz";
        sha256 = "69a4432d57cf68943a407e24a6e960d5f545db87ded04d59024f1519a9b05b23";
    };
}
