# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-Core";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/cro-core-0.8.3.tar.gz";
        sha256 = "6565aee9d6ff97748861f0694778f975a40d9af03c9f8b32fba8da8f0ca5f49e";
    };
}
