# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
openssl }:
rakuPackage {
    name = "Cro-HTTP";
    buildDepends = [  ];
    depends = [ rakuPackages."Base64" rakuPackages."Cro-Core" rakuPackages."Cro-TLS" rakuPackages."Crypt-Random" rakuPackages."DateTime-Parse" rakuPackages."HTTP-HPACK" rakuPackages."IO-Path-ChildSecure" rakuPackages."IO-Socket-Async-SSL" rakuPackages."JSON-Fast" rakuPackages."JSON-JWT" rakuPackages."Log-Timeline" rakuPackages."OO-Monitors" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/cro-http-0.8.3.tar.gz";
        sha256 = "e5c6cff3013946dd0ab5b533ec87e2305fcfcb6ef7c3a4aaf942f4ccc3bd4ad4";
    };
    preInstallPhase = ''
        ldLibraryPath=${lib.makeLibraryPath [ openssl ]}
        export LD_LIBRARY_PATH=$ldLibraryPath:$LD_LIBRARY_PATH
    '';
}
