# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-HTTP-Test";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/Cro-HTTP-Test-0.8.0.tar.gz";
        sha256 = "7c2a6e9492528a7b79faf996145fb862b46ca1935192a8490662bd568c1c7012";
    };
}
