# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-HTTP-Session-Red";
    buildDepends = [  ];
    depends = [ rakuPackages."Red" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FC/FCO/Perl6/Cro-HTTP-Session-Red-0.0.2.tar.gz";
        sha256 = "7911b36d918d44fe226b90abb2c98a1c93df739ccd67706d5a2e4e183e05489b";
    };
}
