# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-ZeroMQ";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro" rakuPackages."Cro-Core" rakuPackages."Net-ZMQ" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/cro-zeromq-0.8.3.tar.gz";
        sha256 = "202e00dd00919a571188a6ad289bfd4e15fcfe730f757a7a8e59f5a1059799e8";
    };
}
