# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-LDAP-ASN-Plugin";
    buildDepends = [  ];
    depends = [ rakuPackages."ASN-BER" ];
    src = fetchurl {
        url = "https://github.com/Altai-man/cro-ldap-asn-plugin/archive/b5fb041c1c464389d708fdee5a116e24babf607e.tar.gz";
        sha256 = "c124d21433948a4e247d78b7c8e43216ae80b57b6131d13aed3c6e601af0dfe8";
    };
}
