# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-ZeroMQ";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro" rakuPackages."Cro-Core" rakuPackages."Net-ZMQ" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/cro-zeromq-0.8.1.tar.gz";
        sha256 = "ad77c7948ba5ebac0d421db207e36e04c0ea6d134ea125e4761e0f74823e66f9";
    };
}
