# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-OpenAPI-RoutesFromDefinition";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" rakuPackages."JSON-Fast" rakuPackages."OpenAPI-Model" rakuPackages."OpenAPI-Schema-Validate" rakuPackages."YAMLish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/Cro-OpenAPI-RoutesFromDefinition-1.0.1.tar.gz";
        sha256 = "754adb0f16f7e8ccca8cb91cea57afdd540ffbea94b44e866eae76beed00356f";
    };
}
