# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-RPC-JSON";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/V/VR/VRURG/Perl6/Cro-RPC-JSON-v0.0.5.tar.gz";
        sha256 = "4519858daa794fea572aaa9fd45056e80c9a5791bab249e7d2e6c8acbef090e9";
    };
}
