# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-TLS";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-Core" rakuPackages."IO-Socket-Async-SSL" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/cro-tls-0.8.2.tar.gz";
        sha256 = "9241a2cd358278568a1f80ff5192fceb75d06c982b8aa48dba4bed9059bbfd6a";
    };
}
