# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Cro-WebApp";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/cro-webapp-0.8.2.tar.gz";
        sha256 = "f3e5834c689e81e76ab1635812a0a39354bedd35355c24a496406a9c9de432ba";
    };
}
