# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "cro";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-WebSocket" rakuPackages."Docker-File" rakuPackages."File-Find" rakuPackages."File-Ignore" rakuPackages."IO-Socket-Async-SSL" rakuPackages."JSON-Fast" rakuPackages."META6" rakuPackages."OO-Monitors" rakuPackages."Shell-Command" rakuPackages."Terminal-ANSIColor" rakuPackages."YAMLish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/cro-0.8.2.tar.gz";
        sha256 = "efd5ebc7481bdaadd3ee19986b806bea781c7191c1edb1c7c2f5bc41de2e66c9";
    };
}
