# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CroX-HTTP-Transform-GraphQL";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP-Request" rakuPackages."Cro-HTTP-Response" rakuPackages."Cro-HTTP-Router" rakuPackages."Cro-Transform" rakuPackages."GraphQL" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/CroX-HTTP-Transform-GraphQL-0.1.tar.gz";
        sha256 = "1a3016f980d4e43aa8b8bc7386757355328250dfb61635d0628f79abc513bcc8";
    };
}
