# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CroX-HTTP-FallbackPassthru";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/CroX-HTTP-FallbackPassthru-0.1.tar.gz";
        sha256 = "b65b4ee09861b418c165b19a2f53319f081c52be8ded6a3540621e8fb6c97328";
    };
}
