# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crust-Handler-SCGI";
    buildDepends = [  ];
    depends = [ rakuPackages."IO-Blob" rakuPackages."SCGI" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/p6-Crust-Handler-SCGI/archive/c11f0b537d1cd98966fcdfd77336549d5a5aa9e1.tar.gz";
        sha256 = "69c8f9a0fed426d207870a7f886d672a4c9a61fd3e31b1f2bd6bc5af526ee3e7";
    };
}
