# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crust-Middleware-Syslog";
    buildDepends = [  ];
    depends = [ rakuPackages."Crust" rakuPackages."Log-Syslog-Native" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Crust-Middleware-Syslog/archive/2da5706ab7735edaaa6678d2a58f2be7ed1feb6d.tar.gz";
        sha256 = "d0bbda9b24822e137ff39c37a42b850ef6e73f34c5bd5c4ab8f86b0604ccb472";
    };
}
