# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crypt-SodiumScrypt";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryCheck" rakuPackages."NativeHelpers-Array" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Crypt-SodiumScrypt-0.0.2.tar.gz";
        sha256 = "8dfbc0b5075ceea95e0de7a8a691c6e9f5a37865cb124a2c84eee1ba36f2502d";
    };
}
