# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crypt-AnyPasswordHash";
    buildDepends = [  ];
    depends = [ rakuPackages."Crypt-Libcrypt" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Crypt-AnyPasswordHash-0.0.2.tar.gz";
        sha256 = "98572e98ea35ecea4aaf432c3ec58a6df66ad4ceb657f93acf79dec145fcb5c8";
    };
}
