# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crypt-Argon2";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/skinkade/p6-crypt-argon2/archive/70b041bdf7ac6d68e7c010d3581e075f9a704d4c.tar.gz";
        sha256 = "65bb694b76311b0eee1bfcfa471c6ba36a0ae86a3ac9e5af9540e8d698e509d4";
    };
}
