# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crypt-RC4";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/Crypt-RC4-p6/archive/3534bd32f28948474a6e7fbcc48ad2adc1590ab2.tar.gz";
        sha256 = "b5d7c9b55c51360e4e921088fc7abe9045fe9fff771d8b7d6c4861ab63ec85db";
    };
}
