# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crypt-CAST5";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Crypt-CAST5-0.1.0.tar.gz";
        sha256 = "486240bb9a603479c136c422ac22c6dd8ac9525d20d65183726148e1dc2aca91";
    };
}
