# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crypt-Libcrypt";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Crypt-Libcrypt-0.1.0.tar.gz";
        sha256 = "aa26ea3207828a234bc9a5b7aa092b0fe25b8619e01b3bb90b7f5dfeb3150330";
    };
}
