# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Crypt-RC4";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/Crypt-RC4-p6/archive/d0a170a1c7371dbdac7cb766300ed19b7e67b8b8.tar.gz";
        sha256 = "8448636df97a36eac01a078680111d6e789c321b79f00275b025f4e7f88f9f5b";
    };
}
