# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CSS-Grammar";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/p6-css/CSS-Grammar-p6/archive/2ef5a15b741823b7f269d5b5a7397f56b506c035.tar.gz";
        sha256 = "b083d4c0034e4a4fb466f235a9efbdcbf3ff498c93fcee428918e0b21bf5875d";
    };
}
