# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CSS-Grammar";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/p6-css/CSS-Grammar-p6/archive/8d3f7e2c0692b04c0cfb989acf0db5f26d20c384.tar.gz";
        sha256 = "574db327d2ffb909be8a952030a62842e7af4d8b56d265411b5b7b8080c8c39e";
    };
}
