# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CSS-Module-CSS3-Selectors";
    buildDepends = [  ];
    depends = [ rakuPackages."CSS-Grammar" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/p6-css/CSS-Module-CSS3-Selectors-p6/archive/734b2d8e75accc52d9ca424acb71b9761bccd37a.tar.gz";
        sha256 = "73808efed5d8bcb73be6ae942dc1456f9844ef849aa86f3c091b243412f46586";
    };
}
