# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CSS-Module";
    buildDepends = [  ];
    depends = [ rakuPackages."CSS-Grammar" rakuPackages."CSS-Module-CSS3-Selectors" rakuPackages."CSS-Specification" rakuPackages."CSS-Writer" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/p6-css/CSS-Module-p6/archive/5b6b4f30e65aada7d5ba346e9b54c7a009e77e65.tar.gz";
        sha256 = "fe9c5f1ce8202cb1b9ef6c2838ef735fddbd350527669c25c975efa2f258777d";
    };
}
