# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CSS-Properties";
    buildDepends = [  ];
    depends = [ rakuPackages."CSS-Box" rakuPackages."CSS-Module" rakuPackages."CSS-Writer" rakuPackages."Color" rakuPackages."Method-Also" ];
    src = fetchurl {
        url = "https://github.com/p6-css/CSS-Properties-p6/archive/a25c16588e9d6c2abb9971b79f79e9893f91e7b2.tar.gz";
        sha256 = "7ca31739312baaaf62fa5c0a7d88713090239231ce829aff46e0a6a92df5c8cf";
    };
}
