# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CSS-Module-CSS3-Selectors";
    buildDepends = [  ];
    depends = [ rakuPackages."CSS-Grammar" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/p6-css/CSS-Module-CSS3-Selectors-p6/archive/e53862025a7664a1cb60b090a950987d91cc0929.tar.gz";
        sha256 = "39348c1c0d19f95a767e08656df17ee2d7809b33aff221ca04d9b8527a6bb2e0";
    };
}
