# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CSV-Parser";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-csv-parser/archive/08f59cb34798556ebe636f476c0c3c1fe78d0577.tar.gz";
        sha256 = "f42689e9e1d9bc74877148f20d9ee2c423fd1ca2fc38f7f56245375aa4199d45";
    };
}
