# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CucumisSextus";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RO/ROBERTLE/Perl6/perl6-cucumis-sextus-0.1.2.tar.gz";
        sha256 = "dd25f3038bea81d6d76303303b3ecc4e8f35b3bc81fdfa62b70d1982ea0bb94f";
    };
}
