# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "CUID";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/marcoonroad/perl6-cuid/archive/f6065d1feb835b67b4e029a814a5df2499648e64.tar.gz";
        sha256 = "f650d38461d5b3b4624078ff8579107853a3ed90d4b48350ff4079c43ac1b642";
    };
}
