# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Data-StaticTable";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/shinobi/Data-StaticTable/archive/88bbef5a80e4cb3cb28c83d36f74941e8e6bf3b6.tar.gz";
        sha256 = "1e2e87f84d294e30ae642b6ebb32a2ed89bd79303c387cdf0585abbc0dec0b59";
    };
}
