# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Data-TextOrBinary";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jnthn/p6-data-textorbinary/archive/138289584f63ed522f20aeda26d974e3aa85a43f.tar.gz";
        sha256 = "7353bd2deb8893ae1b078a10674c26292fab8ebfad521c74b2949164f2b132f3";
    };
}
