# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Data-ICal";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-iCal/archive/c6f83d0e177d9cae72c0c8eef8a0594b277f82e7.tar.gz";
        sha256 = "0cd7981d1e3a767e02995de24e6d83520f99cfd5839a18fd7b0c16530a3eb43f";
    };
}
