# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Data-Selector";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JD/JDV/Perl6/Data-Selector-1.02.tar.gz";
        sha256 = "e97c56a04b9158f1ed2611359454a72751898c652d58168a9dad9fc1b90f35a4";
    };
}
