# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Data-Record";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Data-Record-0.2.0.tar.gz";
        sha256 = "c9ab309d7c35ae9fec7bbce921a8481fecf4774f1f529935b7a0e52fe9c95061";
    };
}
