# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Data-MessagePack";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/pierre-vigier/Perl6-Data-MessagePack/archive/99766f38ca4c6fbeb5da4b6b6d06dd3289607a82.tar.gz";
        sha256 = "4f5d598542338b15a0884a255810f9dd008aef79b84e30e5044550e18b5a2913";
    };
}
