# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DateTime-Monotonic";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMASLAK/Perl6/DateTime-Monotonic-0.0.6.tar.gz";
        sha256 = "a8886956c50622e76aadb123bf27157d0f0960c9ef769d1661be10862c587bbd";
    };
}
