# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Date-Calendar-FrenchRevolutionary";
    buildDepends = [  ];
    depends = [ rakuPackages."Date-Calendar-Strftime" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JF/JFORGET/Perl6/Date-Calendar-FrenchRevolutionary-0.0.4.tar.gz";
        sha256 = "008e22af77f677ddc432968137794f81716e0af93a0b69f93ebb814016448555";
    };
}
