# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DateTime-Extended";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FCO/DateTime-Extended/archive/b91b304fdfd6a44b8786daca9ae7a46305d83113.tar.gz";
        sha256 = "c39a60b553714bbdd3691e63097225d80a5056e555780b0359e665c575b91e46";
    };
}
