# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Date-Calendar-Hebrew";
    buildDepends = [  ];
    depends = [ rakuPackages."List-MoreUtils" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JF/JFORGET/Perl6/Date-Calendar-Hebrew-0.0.2.tar.gz";
        sha256 = "a1d19835f519aff329dffbbc5e0d789c161de1a22274f59de0a4cc9252292787";
    };
}
