# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Date-Calendar-Strftime";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JF/JFORGET/Perl6/Date-Calendar-Strftime-0.0.3.tar.gz";
        sha256 = "3255dfcbbc41f223cf86597f97f4dc4c2220f1ab5b297c8d9cfa73713f745f80";
    };
}
