# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Date-Calendar-MayaAztec";
    buildDepends = [  ];
    depends = [ rakuPackages."Date-Calendar-Strftime" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JF/JFORGET/Perl6/Date-Calendar-MayaAztec-0.0.1.tar.gz";
        sha256 = "c3c5f3e5d1c76f32939c95c5b6053206255d4f9f7c86a4aa08eb7736ac329e08";
    };
}
