# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Date-Calendar-Julian";
    buildDepends = [  ];
    depends = [ rakuPackages."Date-Calendar-Strftime" rakuPackages."Date-Names" rakuPackages."List-MoreUtils" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JF/JFORGET/Perl6/Date-Calendar-Julian-0.0.1.tar.gz";
        sha256 = "2efecb8e8fce3a6c9f08280f62560030e3506af10e5890329e012dc3233ea8c3";
    };
}
