# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Date-Calendar-FrenchRevolutionary";
    buildDepends = [  ];
    depends = [ rakuPackages."Date-Calendar-Strftime" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JF/JFORGET/Perl6/Date-Calendar-FrenchRevolutionary-0.0.3.tar.gz";
        sha256 = "1cee1b6fe3c769098dd92136dbf15e8a0098b0a4a559d954b29051f374b3ff39";
    };
}
