# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DB-Migration-Simple";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MB/MBP/Perl6/DB-Migration-Simple-1.0.tar.gz";
        sha256 = "e572564a37feeeefc7f7a0a58bb82868ca9b778ac29689033c36b622a6c95401";
    };
}
