# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DB-ORM-Quicky";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-db-orm-quicky/archive/81d63526df1dbf5402117b5c9e827332c68f3013.tar.gz";
        sha256 = "591f0bf9747b5d14a9e1b9548d8813ad22df8f287d89d614591e0dfa30885974";
    };
}
