# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DB-Pg";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" rakuPackages."LibUUID" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/DB-Pg-0.6.tar.gz";
        sha256 = "17cb85708dfe98db74d8def106b4d1c2d0bc5f7ac5ef5a08da4d2f4378d10cb9";
    };
}
