# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DB-Xoos-SQLite";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tony-o/p6-db-xoos-sqlite/archive/ebdb46975a61b34a864a9d94df9f9a15895daa0b.tar.gz";
        sha256 = "b0fcfb92d5b9adcbc671b2a79ddb0f3bd4faaee13d196fe3f311bcead560429d";
    };
}
