# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DB-Xoos-Pg";
    buildDepends = [  ];
    depends = [ rakuPackages."DB-Pg" rakuPackages."DB-Xoos" ];
    src = fetchurl {
        url = "https://github.com/tony-o/p6-db-xoos-pg/archive/00e91e73cf7b594ab30fa5b5f195e8d3340a239f.tar.gz";
        sha256 = "5af7a13f21270201d8cf4e001fa76452f4bb2e43d45e5ee244b9cd05057d782c";
    };
}
