# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DB-Xoos";
    buildDepends = [  ];
    depends = [ rakuPackages."DB" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/Y/YN/YNOTO/Perl6/db-xoos-0.0.13.tar.gz";
        sha256 = "40a9d418c9e9a98daea2cb6f069e7a42927d1a32933c42b9a2ab321a747cb5ed";
    };
}
