# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DB-Xoos";
    buildDepends = [  ];
    depends = [ rakuPackages."DB" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-xoo/archive/389dc99da9d8104f473a63ffc49d725d369412d5.tar.gz";
        sha256 = "243c25245ce48ceee54416a175a117caa04ced7a12cd5439605a3712537b9336";
    };
}
