# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DBDish-ODBC";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" rakuPackages."NativeHelpers-Blob" ];
    src = fetchurl {
        url = "https://github.com/salortiz/DBDish-ODBC/archive/ddcc1173b87fbac06e6dfc707294103dcb9c72a5.tar.gz";
        sha256 = "6c50330138238887693168f6b2c4a9954f5f10315bdd325c4d7e5c66dbead263";
    };
}
