# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DBIish-Transaction";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RB/RBT/Perl6/DBIish-Transaction-1.0.3.tar.gz";
        sha256 = "be33aaaf31a62147fb6c84fe1a387ad30d0c80765cde78b3b787dc7c411eb743";
    };
}
