# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DBIish";
    buildDepends = [  ];
    depends = [ rakuPackages."NativeHelpers-Blob" ];
    src = fetchurl {
        url = "https://github.com/perl6/DBIish/archive/9868d84810a73232a60cd3a6086a7e120eece96d.tar.gz";
        sha256 = "24253e50dbe565c7a717d33e809c0d7f920f0a9d8a5f8bb37cc853bbd6bd1592";
    };
}
