# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DBIx-NamedQueries";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MZ/MZIESCHA/Perl6/DBIx-NamedQueries-0.0.3.tar.gz";
        sha256 = "8b40ff1f0a045f7331bf84d117c828d0324de555bc355a66e31360edcf6f0cb4";
    };
}
