# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Ddt";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Find" rakuPackages."File-Ignore" rakuPackages."File-Temp" rakuPackages."JSON-Fast" rakuPackages."License-Software" rakuPackages."META6" rakuPackages."Pod-To-Markdown" rakuPackages."Test-META" rakuPackages."Zef" rakuPackages."Zef-Client" rakuPackages."Zef-Config" rakuPackages."Zef-Distribution" rakuPackages."Zef-Identity" ];
    src = fetchurl {
        url = "https://github.com/kalkin/Ddt/archive/eef70edf8ca3c48d4b4353faf52a35b2a3831516.tar.gz";
        sha256 = "535ed7ed58702f1356e7290151da015baba07319ddb06f64d39f8a07cdb1f825";
    };
}
