# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DEBUG";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/cygx/p6-debug/archive/6ab20f4fe822f9a02325aa0a085fd83c7454f32d.tar.gz";
        sha256 = "84db171a1490ddebd82e9c613fdf96abb2532c7bf7440b4583e1b3c5fb3195d7";
    };
}
