# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Dependency-Sort";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jaffa4/Dependency-Sort/archive/ae14049d8fe70d45f6fd9781f583c9481edb813d.tar.gz";
        sha256 = "7f274f0505765645e1e8e38cf231ea785e17e98e538955640628fdf7b4ccf1c5";
    };
}
