# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "deredere";
    buildDepends = [  ];
    depends = [ rakuPackages."Gumbo" rakuPackages."HTTP-UserAgent" ];
    src = fetchurl {
        url = "https://github.com/Altai-man/deredere/archive/697cd43669331b6af0870003a540db26644e9ee1.tar.gz";
        sha256 = "fe6f1b89b4ec248b81193c577cb96cf3d0afdb355f0d6b50896bc9283dfe5aad";
    };
}
