# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Device-HIDAPI";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/Device-HIDAPI-0.0.1.tar.gz";
        sha256 = "34f79e988b3ab5ced1cf0d1ac344c9e7a5e72f2c12a18edc4e2e78c8ac8aa4f5";
    };
}
