# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Dice-Roller";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jamesneko/dice-roller/archive/a14e827f8f4d8bd72ce5a25e970a2a71e6b77d68.tar.gz";
        sha256 = "81d57d9598e2f08bd138381958a9feda521c5fdc3657fdbfb2a4f724999cddb1";
    };
}
