# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Dictionary-Create";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/prodotiscus/perl6-Dictionary-Create/archive/5436b34a877ddf1454036c7f8b1a43da76865942.tar.gz";
        sha256 = "dcaf21f13878e3febac61973ed070658e2e49c695428326c45af813afe07de30";
    };
}
