# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest-xxHash";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/atweiden/digest-xxhash/archive/6fa5beb2d13864394d28c29f3884d4fd46b077de.tar.gz";
        sha256 = "1c43f0353472f97034ddbc1c417dd7ff0050e59aae0b74f1ed194d26c644787b";
    };
}
