# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest-FNV";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-digest-fnv/archive/13aae6276205577adb6730ab4c6c44fd2ae186b4.tar.gz";
        sha256 = "1b2617929fe934a6b299d7f12bc14b50498f7be96ac7227adbc5bdbef952b63e";
    };
}
