# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest-xxHash";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/atweiden/digest-xxhash/archive/2365e9a34947b451c56d88d63804f3b5f5ed68df.tar.gz";
        sha256 = "2ef3f8223efdfd18bf70d417b794e65a4cc0fc058b86eae0ddcfe16cddd10574";
    };
}
