# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/grondilu/libdigest-perl6/archive/42ba6bef6ca5a9e532ad1436465df7af0cd5f70c.tar.gz";
        sha256 = "0300cd24343e2633e6ef5eaa34ff02f09db1df2298dfee2a0aef73a59752ef6f";
    };
}
