# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest-SHA256-Native";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/B/BD/BDUGGAN/Perl6/Digest-SHA256-Native-0.03.tar.gz";
        sha256 = "ed5e470aebb7c9b940b56b8383351bf0f5ae36c441fe38c063819d8c0be7cdd1";
    };
}
