# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest-SHA1-Native";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" ];
    src = fetchurl {
        url = "https://github.com/bduggan/p6-digest-sha1-native/archive/44c3452d057fabc293386af2d752683364e8eb45.tar.gz";
        sha256 = "cd77e4fb141b820ba395620a1774d6ab520e93942dc0468670f1aedbfd5eb578";
    };
}
