# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest-BubbleBabble";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Digest-BubbleBabble-0.0.3.tar.gz";
        sha256 = "696748c32dc76cbb4eac37c6433669d7f9bb7337a36b329f79e9fc1d33981b0a";
    };
}
