# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Digest-HMAC";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Digest-HMAC/archive/dcc292d77c7158eb7b53d3673cbee66d8b7b4fdf.tar.gz";
        sha256 = "35446ceb61b9c65dbb52f4c0136772235cd2874bcfcd2459dab4641e57a191d3";
    };
}
