# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DirHandle";
    buildDepends = [  ];
    depends = [ rakuPackages."P5opendir" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/DirHandle-0.0.3.tar.gz";
        sha256 = "708a504404bccbc319ce6dc54c913631d65640bc68c4dca7a992b0e75b6de646";
    };
}
