# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Distribution-Builder-MakeFromJSON";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/niner/Distribution-Builder-MakeFromJSON/archive/db586206d7c4d62a4d5033be3a23e42b1e0e48a2.tar.gz";
        sha256 = "d19a2087e9a3f081e75295ecd63d2a8d55c2ee02f0e663d402a7b79bb290a934";
    };
}
