# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "DNS-Zone";
    buildDepends = [  ];
    depends = [ rakuPackages."Test" rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/jsimonet/dns-zone/archive/343bd15a043bbf7163644e67a955c5504927fcc7.tar.gz";
        sha256 = "a63506f6d6859ec170aff2a058558ea9d17751a9b378ed490ecf3cdbe70b7f8f";
    };
}
