# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Docker-File";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jnthn/p6-docker-file/archive/8cf3c23faea6e2687b3608eae108d2a7ab8d7e34.tar.gz";
        sha256 = "b4ac543de018d8a78dc5f921f30eaaded10819827cec0aaf87819f785f703d72";
    };
}
