# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "EC-Grammars-DIG";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/bioduds/EC-Grammars-DIG/archive/f6b23da23deb643b91ac66a220a057e64c55c3b9.tar.gz";
        sha256 = "c7bfde11ddd61760c19fc915d9535cd111c184ea02afcfd02f22623182117d10";
    };
}
