# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ECMA262Regex";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/edumentab/p6-ecma262regex/archive/4dd66c067e9182212bca875c8b963ecec8d83fdc.tar.gz";
        sha256 = "7802e100755c93c5b68e4c93c5739892003783b514c1ffdb2bc83ebb6298bf6d";
    };
}
