# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Email-Notmuch";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/goneri/p6-Email-Notmuch/archive/f2c1f495ef42822f164902c5893bd98a737af5aa.tar.gz";
        sha256 = "3d5b99cc6943f293772def3bcf3ef3a014a1a3f3ef09588cd67d63b30e984194";
    };
}
