# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Email-SendGrid";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/Email-SendGrid-0.1.tar.gz";
        sha256 = "7b69889eef49d1d423eaeef90fe87fa1ad47ead030b973f539f5ea7ae5450025";
    };
}
