# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Email-MIME";
    buildDepends = [  ];
    depends = [ rakuPackages."Email-Simple" rakuPackages."MIME-Base64" rakuPackages."MIME-QuotedPrint" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/p6-Email-MIME/archive/ba75f8c02a3f5c370a68adb0e53a0ca117a581c8.tar.gz";
        sha256 = "7222b3ca46fe24c5364b245189994bc584ab36c9c2effbaa9c1c50c940ff2d4c";
    };
}
