# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Encode";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/sergot/perl6-encode/archive/7561b5f48cd666f5f767d400c5fa7444f546e3a0.tar.gz";
        sha256 = "54006f636e05ee9cb46c3db265298774cc937ab70ccd103cf6c1b34db69cdb37";
    };
}
