# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "EventSource-Client";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/EventSource-Client-0.0.2.tar.gz";
        sha256 = "f99982be29806382e3642540bb72b66dc4d7a5a34c39c229de5b58183197af7a";
    };
}
