# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Failable";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Failable-0.1.2.tar.gz";
        sha256 = "25e24a7b086fb295211bd66a3c9c47a2f8bce47f751088f7867acad707faa1be";
    };
}
