# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Farabi6";
    buildDepends = [  ];
    depends = [ rakuPackages."Browser-Open" rakuPackages."Debugger-UI-CommandLine" rakuPackages."File-Temp" rakuPackages."HTTP-Easy" rakuPackages."JSON-Tiny" rakuPackages."Pod-To-HTML" rakuPackages."URI" rakuPackages."p6doc" ];
    src = fetchurl {
        url = "https://github.com/azawawi/farabi6/archive/bb8399303659cc9d17429b22fb17c20f9ace4fd7.tar.gz";
        sha256 = "0ae1899f02d235ca9080f9a8876b903a4e876092d20e044e193d7b2c2afc09b7";
    };
}
