# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "FastCGI-NativeCall";
    buildDepends = [ rakuPackages."LibraryMake" rakuPackages."Shell-Command" ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/FastCGI-NativeCall-0.0.6.tar.gz";
        sha256 = "ffb43695e4a0d3987d4718444d8eefbc2d1b8793de840ba804812da407dfccbc";
    };
}
