# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "File-XML-DMARC-Google";
    buildDepends = [  ];
    depends = [ rakuPackages."XML-XPath" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/File-XML-DMARC-Google-0.1.1.tar.gz";
        sha256 = "93976f242120005d2bd13a94f1c76d0bd870cd224f35fd930e133e858bc441fc";
    };
}
