# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "File-Compare";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/labster/perl6-File-Compare/archive/d70db24f6f86238fe27c17f6b3b2590a07560454.tar.gz";
        sha256 = "13a74ae520d346fc82378dc915abbbba98ae9736805db4f4dde7b3bb2d82ee25";
    };
}
