# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "File-Zip";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" rakuPackages."File-Which" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/File-Zip-0.1.2.tar.gz";
        sha256 = "b87145c9d0a968560a7036bed96455fda339e7753b9223a81ed15526a15f1713";
    };
}
