# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "File-HomeDir";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-file-homedir/archive/09f4cead7a29d6537e8a3ac2703a39b651d74fda.tar.gz";
        sha256 = "12ba68e52f2fd8d5ebcd19b2902b194f7ceba185ddd5ab59ee1f1cc0f12b40dd";
    };
}
