# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "File-Path-Resolve";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/atweiden/file-path-resolve/archive/d55045fbca24abdc5cebf82f1ed34946cb81bc29.tar.gz";
        sha256 = "92966185a618f9d3c9c8bb2d17e6fd146f6c188ce83a93e3c14a315c6cd66f75";
    };
}
