# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "FileSystem-Capacity";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ramiroencinas/perl6-FileSystem-Capacity/archive/5dc0a9c53119414e0112f679aa8add8b9b90cc12.tar.gz";
        sha256 = "9564ce54b6add816fed69942e7a074b66cd83472209f8cd47eb6e67f9a24ef67";
    };
}
