# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "FileSystem-Parent";
    buildDepends = [  ];
    depends = [ rakuPackages."FindBin" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/L/LE/LEMBARK/Perl6/FileSystem-Parent-0.3.6.tar.gz";
        sha256 = "b15165fe87379e5d3c870340c061d552f32f2fb8992afaf70b9422d5e7943127";
    };
}
