# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "File-Temp";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Directory-Tree" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RB/RBT/Perl6/File-Temp-0.0.8.tar.gz";
        sha256 = "80f3e1ba344fadbd013f0ac3b4b653e812178b3db64deb5e6cb6dec218e3fc90";
    };
}
