# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "File-Presence";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/atweiden/file-presence/archive/da87b4d8ed6bb97c014ffd2d0543fb2a882a4001.tar.gz";
        sha256 = "6d5777aa0edc9acb9cde20426e893b1c4e1b5937c260cff07c4d9b338c89cea8";
    };
}
