# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Finance-GDAX-API";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest-HMAC" rakuPackages."Digest-SHA" rakuPackages."JSON-Fast" rakuPackages."LibCurl" rakuPackages."MIME-Base64" ];
    src = fetchurl {
        url = "https://github.com/adaptiveoptics/P6-Finance-GDAX-API/archive/9ad4a0842e2a61ad60c6a5f0e2c9a52f952899de.tar.gz";
        sha256 = "981ea746fadcff38a8bee92a92312e2ae2f5d8b03c95a15cdf3b5c5d9a451969";
    };
}
