# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "FindBin";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/L/LE/LEMBARK/Perl6/FindBin-0.6.3.tar.gz";
        sha256 = "a7e8e96937b68b41ef3b8cfd2015a2df63957abb78d0d2c5518d8544886db749";
    };
}
