# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Find-Bundled";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Find-Bundled/archive/8e918656e2ac70633e74d72d0211ad01c975e1dd.tar.gz";
        sha256 = "0517565ac3cbe4c8f427aed5d760bc0e36cf4eef1e40c03d08c50d17bbd39d0b";
    };
}
