# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "flow";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-flow/archive/7de3e893a60b3b9cdbd5b71374512b20dd917d71.tar.gz";
        sha256 = "8975d47a2b63951781a8fa55a1f3712125316580110fca5af64c9f8d286b1e7b";
    };
}
