# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Flower";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/supernovus/flower/archive/ab4816c3f2d6e29a43296e1f3626106e314d081f.tar.gz";
        sha256 = "574632b54e2a4c0bde2db2346e5f8277d60bba8b4af59b775f610d706876e2de";
    };
}
