# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Font-FreeType";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/W/WA/WARRINGD/Perl6/Font-FreeType-0.2.0.tar.gz";
        sha256 = "0e9248ea95930f19f175542273c14ee404aac2ae7aea2494dc9ccac796f42e64";
    };
}
