# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Font-QueryInfo";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/samcv/perl6-Font-QueryInfo/archive/e0fc0629dc7a46e4f167fb0cbc3d8bbfbe910f9d.tar.gz";
        sha256 = "f219e85260398699c6cce2a6864d20000b33805bae6efaa1fb62cc52a8d7884e";
    };
}
