# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Foo-Dependencies-A-on-B";
    buildDepends = [  ];
    depends = [ rakuPackages."Foo-Dependencies-B-on-A" ];
    src = fetchurl {
        url = "https://github.com/AlexDaniel/foo-dependencies-a-on-b/archive/5f0698935ed86f35ffdeeb45386eb79ac283b296.tar.gz";
        sha256 = "22f337330f24ac38283aac417c756c567647513a10c3c949ea2b81cf60c8ec66";
    };
}
