# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Foo-";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/AlexDaniel/foo-nullbyte-foo/archive/4cb0bfaa6b2ee50a2d452fbc582046c27c477087.tar.gz";
        sha256 = "804fbf521161b5aa2d2dc72c745725dc4e49257d4b35c5eef3bc3856cff5be84";
    };
}
