# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Foo-Regressed";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/AlexDaniel/foo-regressed/archive/590175d3f74b2cc8016e59654dd913ea38ed48e3.tar.gz";
        sha256 = "3370ce012a0700dcaf764921c758a557665d7d00323908384c5ed74a750da966";
    };
}
