# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Foo-<b>Foo";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/AlexDaniel/foo-b-foo/archive/aed8c0b9afcb3e222b6ec33dd5204185b32e26ce.tar.gz";
        sha256 = "a63db7d102dfff0df1385b594c676a2bd9eebbb521f1a2cb741302e0e8dd853d";
    };
}
