# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Format-Lisp";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/drforr/perl6-Format-Lisp/archive/a46d8ab4421990ab6deda31ceee9c6850b6a5e0d.tar.gz";
        sha256 = "57901d5f4cc54eb26d9b1e40c22b5cb77f33de406c9763adcf9f2152c43f990d";
    };
}
