# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Fortran-Grammar";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/nobodyinperson/perl6-fortran-grammar/archive/59939f13ac88e5e80d3f47ca9ef96d65d85da386.tar.gz";
        sha256 = "408beab97448e8f396d2e9f4ec65a47526ae4da1ee101bf81c3030f6a3a8f2ba";
    };
}
