# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Frinfon";
    buildDepends = [  ];
    depends = [ rakuPackages."Crust" rakuPackages."Router-Boost" ];
    src = fetchurl {
        url = "https://github.com/skaji/Frinfon/archive/9c01279bfdab2dc57b49c11607b45bbd01ec14cb.tar.gz";
        sha256 = "77f5dda4ad997e85a168c9939c394af9d04b05ec4d9caa77b19a36b4dd26506d";
    };
}
