# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Games-TauStation-DateTime";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Games-TauStation-DateTime/archive/012632608db7a745419f24dd391deb83c13a2a6c.tar.gz";
        sha256 = "0e6b4e2db27c719aca80d2f16930362f502de4a299afd84d18c8c967861a60a6";
    };
}
