# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Geo-Coordinates-UTM";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KJ/KJPYE/Perl6/Geo-Coordinates-UTM-0.9.0.tar.gz";
        sha256 = "b9e8b7e46beeee919dab68e732c6e62b4f712652b9fb8fc510d85524f210ab58";
    };
}
