# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Geo-Region";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/patch/geo-region-pm6/archive/a2472d16fb9c778af5f925edf472a78c9e38191a.tar.gz";
        sha256 = "1536c6f2b066debbe78c48bff78fb0604628caf83a4c79a20bda9eb3da080378";
    };
}
