# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Geo-Coder-OpenCage";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-UserAgent" rakuPackages."JSON-Unmarshal" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TA/TADZIK/Perl6/Geo-Coder-OpenCage-1.0.tar.gz";
        sha256 = "17ed250c70f52e945630248b8e62b3fd21fc6379f03415cd8784576de53ff8e5";
    };
}
