# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Geo-Hash";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TI/TITSUKI/Perl6/Geo-Hash-0.0.1.tar.gz";
        sha256 = "dd3d2bd15a6aac7c87e31e032faea8ad5f4b9eee53d99b3e9e25f77e780ca0d4";
    };
}
