# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Geo-IP2Location-Lite";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/leejo/geo-ip2location-lite-p6/archive/4ed5146cbccf1bb8669c240b4b730be51da4b24b.tar.gz";
        sha256 = "eb7d62f8fe1148c87e7ec52d2c618b50d423880dc4d72bbdaf8adf48d8e6a1a1";
    };
}
