# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Geo-Coder-OpenCage";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-UserAgent" rakuPackages."JSON-Unmarshal" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://github.com/tadzik/Geo-Coder-OpenCage/archive/21cf7596c4321bd940894cd7dabc77a99d0245a2.tar.gz";
        sha256 = "140e6c056a1831061107dbcb53456315e10ad7ee7162f29df1247602e4a8f14c";
    };
}
