# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "GeoIP2";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/bbkr/GeoIP2/archive/0f47c7d9ee152318e2e2f3022a4232475033f37b.tar.gz";
        sha256 = "8eeb1ca3b41a0fe855ffdda1c133ff81e197819fee45f4c1cc3064a9c538a02b";
    };
}
