# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Getopt-Long";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/L/LE/LEONT/Perl6/Getopt-Long-0.1.6.tar.gz";
        sha256 = "380d4bc821c89965e70bf8b291a37a962db1abfc42f8f344b0ff68b4cecbbb1b";
    };
}
