# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Getopt-Std";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ppentchev/perl6-Getopt-Std/archive/8fc26c84f37b718199c3a39bde0bb76516ffcbf2.tar.gz";
        sha256 = "85d85328568bd90c00cf86041ac86f4371b3de719557eb63529d718d85140d95";
    };
}
