# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Getopt-Std";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ppentchev/perl6-Getopt-Std/archive/eee6dd26890bbf3d92154c1cee237cfd316f854d.tar.gz";
        sha256 = "b32487a6831a2b339c289f91807e199705ac79d60fcd1484b532e7a3c0d739e0";
    };
}
