# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Getopt-Type";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tadzik/Getopt-Type/archive/10d4d01a02540e0fdb8c965b671b5e64bac49afd.tar.gz";
        sha256 = "9101e07be97bb0dc8d7fad726f57680e8bfee1e17703ae44decd9bd357455dfe";
    };
}
