# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Getopt-Advance";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-Table" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AL/ALOREN/Perl6/Getopt-Advance-1.1.4.tar.gz";
        sha256 = "0b76d4daf0acb113989e0b243b78f918579661857b25d2c65a545988e6cb17a9";
    };
}
