# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Git-PurePerl";
    buildDepends = [  ];
    depends = [ rakuPackages."Compress-Zlib" rakuPackages."DateTime-TimeZone" rakuPackages."Digest" rakuPackages."File-Find" ];
    src = fetchurl {
        url = "https://github.com/raydiak/Git-PurePerl/archive/cc460c87e55e2b588fe24a77953fec20a813aa0b.tar.gz";
        sha256 = "42d3cb73bc90f6cee90d899b19d2989cb95e4991af0e15fe130bfb3096155a5c";
    };
}
