# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Git-Config";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/gfldex/perl6-git-config/archive/74ffb6f2df457e908f6602a125855761d833b57d.tar.gz";
        sha256 = "ac80a2e26ad3f3f3cd59c9c1eba5074236a8de8f42feb7883418b90f0cc25c5d";
    };
}
