# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "GlotIO";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Tinyish" rakuPackages."JSON-Fast" rakuPackages."URI-Escape" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-GlotIO/archive/a43aee1138ed299038d46789a504185936d2a291.tar.gz";
        sha256 = "ffcd3ad3657cabca62f02959c5e3904efdc8c7fdaa395fe6721218b96ce77bea";
    };
}
