# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Gnome-Gio";
    buildDepends = [  ];
    depends = [ rakuPackages."Gnome-GObject" rakuPackages."Gnome-Glib" rakuPackages."Gnome-N" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/gnome-gio-0.4.2.2.tar.gz";
        sha256 = "890f12c43b54c4f3e9e4e083f8a566ffe364d1de79fb943466f8f238d7c99c82";
    };
}
