# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Gnome-N";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/perl6-gnome-native-0.15.1.1.tar.gz";
        sha256 = "305db2d84b058825402d081808a496e992762734ae45e5f0341655df3c0a1c67";
    };
}
