# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Gnome-GObject";
    buildDepends = [  ];
    depends = [ rakuPackages."Gnome-Glib" rakuPackages."Gnome-N" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/perl6-gnome-gobject-0.15.6.tar.gz";
        sha256 = "b6c330d8434944e8eb7058dc543a955f7522fc2943963987e7dcb35a98c89b9f";
    };
}
