# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Gnome-Gtk3";
    buildDepends = [  ];
    depends = [ rakuPackages."Gnome-GObject" rakuPackages."Gnome-Gdk3" rakuPackages."Gnome-Glib" rakuPackages."Gnome-N" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/perl6-gnome-gtk3-0.21.0.tar.gz";
        sha256 = "0263b651cb50c1b33b702cd1fd097449e1bdcc5c1caf28fc154596b7891ef529";
    };
}
