# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Gnome-Gdk3";
    buildDepends = [  ];
    depends = [ rakuPackages."Gnome-GObject" rakuPackages."Gnome-Glib" rakuPackages."Gnome-N" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/gnome-gdk3-0.15.4.1.tar.gz";
        sha256 = "b02a157f03a1fedbc82bd3df7bce066d82c4937a73e9cd695f4ce6748b846b4d";
    };
}
