# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Gnome-N";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/gnome-native-0.17.3.tar.gz";
        sha256 = "a0fb2ac40b100c54e4c0bf32120c1df6b76f0f6830d1ad17edfdf7b9fb0d3b17";
    };
}
