# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Grammar-BNF";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tadzik/Grammar-BNF/archive/2e34618e0bfb712ce1eb569abd0c134396d4967d.tar.gz";
        sha256 = "7b2efffb488dd701e16a0b96778d17ed5cf46e5d66c37267b149a82c518d7752";
    };
}
