# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Grammar-PrettyErrors";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/B/BD/BDUGGAN/Perl6/Grammar-PrettyErrors-0.0.4.tar.gz";
        sha256 = "69770256b45e628837a763e5a15a27f60ca9b1dd7aed946fd17b4ee3ca49db64";
    };
}
