# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Grammar-HTTP";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ugexe/Perl6-Grammar--HTTP/archive/210371b64dafcca7b4eecf450489d9a992388f27.tar.gz";
        sha256 = "e146be4c8997bad74720e85fc5a9630442483aae3a32b797d07e82746d27966e";
    };
}
