# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Grammar-Highlighter";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://github.com/niner/Grammar-Highlighter/archive/7561779940ae22a4d7e2441d522acd9a564db600.tar.gz";
        sha256 = "d447912a2aa32ac41ef3a3eb31fc954e70e81d88589105eba4540d10f3516759";
    };
}
