# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Grammar-Modelica";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/albastev/Grammar-Modelica/archive/793979835e62ff907203824249fc73e9441b2c44.tar.gz";
        sha256 = "acde2461f18f8797d03b673732a724f955e4f5bcf391c9f4b9091960dd7e13a4";
    };
}
