# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "GraphQL";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" rakuPackages."Text-Wrap" ];
    src = fetchurl {
        url = "https://github.com/CurtTilmes/Perl6-GraphQL/archive/ad213b6bab7a8542b0d0b41dd31cbe576ce120e5.tar.gz";
        sha256 = "0062d9162b087338bfa6b6b765373afd38b7ca3ab4472953f8396c5a11724611";
    };
}
