# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Graphics-PLplot";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-graphics-plplot/archive/ed60061e42b2eb2665571819dc912c83bffaec39.tar.gz";
        sha256 = "adf0ca7e167246519317684544d80b532fabe228c27af312c24688b0e739ef04";
    };
}
