# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "GraphQL-Server";
    buildDepends = [  ];
    depends = [ rakuPackages."Bailador" rakuPackages."GraphQL" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/GraphQL-Server-0.1.tar.gz";
        sha256 = "c7bd92d39467c56ca09d629f8591e266e779ff41a23f80fd10fa1b3ace7fc924";
    };
}
