# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Graphics-TinyTIFF";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RY/RYNIX/Perl6/Graphics-TinyTIFF-0.0.6.tar.gz";
        sha256 = "949c7cf8ac3c590c617edd5c7fd358dd06b0a5f20e2f2f1fee78a9345bd380ba";
    };
}
