# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Gravatar-URL";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest-MD5" rakuPackages."URI-Escape" ];
    src = fetchurl {
        url = "https://github.com/fayland/perl6-Gravatar-URL/archive/b1fc10d6a444ce2cf18d9bff6f5b1be7d36db01c.tar.gz";
        sha256 = "0d0ec7281be79c4b67dce76bfeb05c0e08a5d8db1fccb75d62e4d234bd21db02";
    };
}
