# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Green";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-green/archive/6392d7ec92a77e609858d4f5febbbe800a59416a.tar.gz";
        sha256 = "69fac078f278210079b7a0a5132877c0e29a2493a991b6625f2a85e07d92afa4";
    };
}
