# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "GTK-Simple";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perl6/gtk-simple/archive/7503760cb06e8aa4eb6a50991d62a0a94e62b289.tar.gz";
        sha256 = "8ea6e25f7a7323bd60dd48a8a1ac2fe1713453a58ff94d5c773aa47f412ca855";
    };
}
