# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "GTK-Simpler";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-gtk-simpler/archive/668a5602327ce4f97048045885adb2cf9507d721.tar.gz";
        sha256 = "679f61877ceaab3322d468e577821c8d6e51b6be3a4e60a1edb66c0508c8d167";
    };
}
