# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Haikunator";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Atrox/haikunatorperl/archive/5108b616847c06f1bf8e93c5d6a8affbcafda52f.tar.gz";
        sha256 = "abb33936f290d84374cd7fd5d51527c78da6f2477fca765abb57166834a9eb47";
    };
}
