# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Hash-Consistent";
    buildDepends = [  ];
    depends = [ rakuPackages."String-CRC32" rakuPackages."Subsets-Common" ];
    src = fetchurl {
        url = "https://github.com/bradclawsie/Hash-Consistent/archive/422635275367a4c2bc99239a300130110be6bab9.tar.gz";
        sha256 = "e5b0796b3d0e8b49a49a1f0de586b7d88e40bf91aa14d290164b158f04f007d7";
    };
}
