# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Hash-Util";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Hash-Util-0.0.2.tar.gz";
        sha256 = "3a353ba1cdbcaa9fbc3d831e64d8907754556a6a947d1872f336505ceca0cd53";
    };
}
