# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Hash-Merge";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Hash-Merge-1.0.0.tar.gz";
        sha256 = "a600c4f9c0060ad48d8ca53506497784da0d8abaa2f033d6e24ca19a879775f5";
    };
}
