# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Hash-with";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Hash-with-0.0.2.tar.gz";
        sha256 = "d35ba81cf9d44833e64495a008522473d7a69f292be7b5eb5f484747b35c89fc";
    };
}
