# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Hashids";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/kalkin/perl6-hashids/archive/271c3f202193fe645eff231a4cb84e0c691b279d.tar.gz";
        sha256 = "593069c8c539652f240af95991997a67e4768975043b68a6e7eff1efa9ecc820";
    };
}
