# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HexDump-Tiny";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perlpilot/p6-HexDump-Tiny/archive/c9e026dcf036c83ad840a7ea1d482bab4e436f6d.tar.gz";
        sha256 = "195a8ff11e1508a2941f2b7bee6514bb902883a8aff20f389b1666bbdfe10c9c";
    };
}
