# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Hinges";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/supernovus/hinges/archive/c608f262c26b301c6432436836c0df0a1eaf6c50.tar.gz";
        sha256 = "eef364cbdabed95c7db666367f32c739c2e80e4bcf60576f801c3348dfadb6f2";
    };
}
