# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-Strip";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/dagurval/HTML-Strip/archive/43527117e067496b498d4cafe8a86f9974323b3b.tar.gz";
        sha256 = "aac78d030675b41c7835a3549a74e55bec71db95be9f8865dbd42eb826398b27";
    };
}
