# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-Parser";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-html-parser/archive/cc3dbd0d635a2192e1034a6f4eb27488e8703883.tar.gz";
        sha256 = "ab5c0cbbf6af28a2900af1800f394ab0a60569e2832707ab691eb5c11cd5b4f1";
    };
}
