# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-BoreDOM";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AL/ALLSOPP/Perl6/HTML-BoreDOM-0.0.7.tar.gz";
        sha256 = "b4fb3e42d66899d8d5b1fe10d78fc5545a33099cac4a53f4ff9e34a5acbf1093";
    };
}
