# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-Escape";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/moznion/p6-HTML-Escape/archive/57907ffbf2e83819feb23d0de13eefd4cb99954d.tar.gz";
        sha256 = "db4f3f52027521e4ac89d1d0c67440fc8786572f735977a98366d8a967287fba";
    };
}
