# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-Parser-XML";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-html-parser-xml/archive/8eeaf21826646a8805d0191b64b4e71e092e2bbc.tar.gz";
        sha256 = "5c24e9e5f003394b8bb65ff91e2f97e8a267d8418cc3357f2f9769522c9d777b";
    };
}
