# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-BoreDOM";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AL/ALLSOPP/Perl6/HTML-BoreDOM-0.0.6.tar.gz";
        sha256 = "579a81e1578af9be7a15383c0be72aec0a434af9c6650d8a1af12872b6f5f570";
    };
}
