# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-Canvas-To-PDF";
    buildDepends = [  ];
    depends = [ rakuPackages."CSS-Properties" rakuPackages."Color" rakuPackages."HTML-Canvas" rakuPackages."JSON-Fast" rakuPackages."PDF-Content" rakuPackages."PDF-Font-Loader" rakuPackages."PDF-Lite" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/W/WA/WARRINGD/Perl6/HTML-Canvas-To-PDF-0.0.3.tar.gz";
        sha256 = "cf4bc2fb104e15a1cbd00753c1a135ea0342fce6e3758f905d205e9fae4e9339";
    };
}
