# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTML-Tag";
    buildDepends = [  ];
    depends = [ rakuPackages."HTML-Entity" ];
    src = fetchurl {
        url = "https://github.com/adaptiveoptics/HTML-Tag/archive/0c733490e7ece19341cdd3d9dfe938ec270e034b.tar.gz";
        sha256 = "9da1320a0d482b27384bfd976a44ab407b8a402805000dbda5d3ab8d8c046439";
    };
}
