# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Server-Async";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Roles" ];
    src = fetchurl {
        url = "https://github.com/perl6-community-modules/perl6-http-server-async/archive/986580515444d5c3d72a9fc481e13d09869533ff.tar.gz";
        sha256 = "2a2b0e7277669eaf0d3967f1e0cd7aa8cbde0ce3b9dc94228ed2f46cd1d1c9e5";
    };
}
