# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Server-Router-YAML";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Server" rakuPackages."HTTP-Server-Router" rakuPackages."YAML-Parser-LibYAML" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-http-server-router-yaml/archive/7a3be16c2d33ebee04e671bac04d8b6d00c30866.tar.gz";
        sha256 = "9babc33ef1c50905dc9f8d94653ab1c18e90e4058d2beb65d06f5f268c61fdc7";
    };
}
