# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Supply";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zostay/HTTP-Supply/archive/d99d79903b83731ef7408bb145f181c734d540ee.tar.gz";
        sha256 = "5fcc4c220238d37dfa6dc6258f7bcf9fcc71b8ee8c0697ac2140105661777841";
    };
}
