# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Server-Tiny";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Parser" rakuPackages."HTTP-Status" rakuPackages."IO-Blob" ];
    src = fetchurl {
        url = "https://github.com/tokuhirom/p6-HTTP-Server-Tiny/archive/150aaa730b0a442db08cf2da2314662cd77de74f.tar.gz";
        sha256 = "cb4ded154c27cb36440e16206daa987835034305a3e99cd414c7019098bae54e";
    };
}
