# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-HPACK";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jnthn/p6-http-hpack/archive/608a74c5f56d76891ce9c7f9422320e9fdd5b6af.tar.gz";
        sha256 = "23ee7336901fdbb3e57c3d56ca295c467c7fdeba0d2feb2de53011d016f1d7c7";
    };
}
