# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Server-Async-Plugins-Router-Simple";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Server-Async" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-http-server-async-plugins-router-simple/archive/e422c7551f29f12f8bc6f5c15d3d0ef4c8ddca6d.tar.gz";
        sha256 = "12da2f644d571cdbdc1ce570e3e6302b677398a12413e6795739078be86a9cbe";
    };
}
