# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Tinyish";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" rakuPackages."curl" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SK/SKAJI/Perl6/HTTP-Tinyish-0.1.4.tar.gz";
        sha256 = "2d67d3d89ffdf1fe9e384b4901e1b62c37bfe9cef154948892d2a8560222cbd6";
    };
}
