# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-ParseParams";
    buildDepends = [  ];
    depends = [ rakuPackages."URI-Encode" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-HTTP-ParseParams/archive/7d299f9b2d3224fe9aa401afa3879e91986f8fd2.tar.gz";
        sha256 = "d2e48b607286c08feb8c1e3a5bed2eadda8fc177fb37a6414b9784aadf25789e";
    };
}
