# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Request-Supply";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/HTTP-Request-Supply-0.2.0.tar.gz";
        sha256 = "277b8df9ae9253384d3ebadce571f89e6dfb365cf4a2054a5a265407eb9e21c1";
    };
}
