# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-API-Pingdom";
    buildDepends = [  ];
    depends = [ rakuPackages."Base64" rakuPackages."LibCurl" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/HTTP-API-Pingdom-0.1.0.tar.gz";
        sha256 = "26a93ea6a815c62f27ac3117de261ba33d24d15a9acbdc21512b4fd1854605e9";
    };
}
