# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-MultiPartParser";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/tokuhirom/p6-HTTP-MultiPartParser/archive/1982328dded27cc3e459dbb87aa822fff8f44de6.tar.gz";
        sha256 = "13deb49207e722f3ab303f672ff8d0912f796163ec7b5139179da04ef13db9d0";
    };
}
