# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Signature";
    buildDepends = [  ];
    depends = [ rakuPackages."DateTime-Format" rakuPackages."Digest" rakuPackages."Digest-HMAC" rakuPackages."Digest-SHA" rakuPackages."HTTP-UserAgent" rakuPackages."MIME-Base64" rakuPackages."OpenSSL-RSATools" ];
    src = fetchurl {
        url = "https://github.com/pierre-vigier/Perl6-HTTP-Signature/archive/b154f95ef1e4485a47d92ad8e875f3f74b616378.tar.gz";
        sha256 = "a9ad16df20db8e3032fce58b5a32e44c49d3eb12155b81795a2749ebb0735fae";
    };
}
