# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Request-Supply";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zostay/HTTP-Supply/archive/5948177a2cd2bbeb6d858e8a2b1858ae85da303c.tar.gz";
        sha256 = "14898dfa8886cb50d463d242094c72602842d223896049f3a1d3d7e113eb7f0b";
    };
}
