# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Status";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/supernovus/perl6-http-status/archive/c8226cfcfe5ee65536880287fcd0c332f7f409f5.tar.gz";
        sha256 = "158fec836397c886201d285f4debb646b072ea550817c84e5d201b66f4c270b8";
    };
}
