# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Easy";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Status" rakuPackages."PSGI" ];
    src = fetchurl {
        url = "https://github.com/supernovus/perl6-http-easy/archive/8742272c4913e6e05895f90c96262cd0c37772d1.tar.gz";
        sha256 = "9b2ae6ac47283b85ff734f87ffd65ecb15a996f7620cd4e0851f3b49f26bce72";
    };
}
