# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "HTTP-Client";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-Status" rakuPackages."IO-Socket-SSL" rakuPackages."MIME-Base64" ];
    src = fetchurl {
        url = "https://github.com/supernovus/perl6-http-client/archive/0425ea3afb1a86dc20a546beabc0735b31b65626.tar.gz";
        sha256 = "769ab1d7e3b4a7f2134da21ce179b397d5d636d5451712bb9f60e90a72d248a4";
    };
}
