# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "I18n-Simple";
    buildDepends = [  ];
    depends = [ rakuPackages."Hash-Merge" rakuPackages."YAMLish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/I18n-Simple-0.1.2.tar.gz";
        sha256 = "200d2d2316f55b84e98436f00ce595512208726708af6b85c0ec09c9150f4ea4";
    };
}
