# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "I18N-LangTags";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/U/UF/UFOBAT/Perl6/I18N-LangTags-0.1.0.tar.gz";
        sha256 = "e2dc663edf5bf2e3418eb9b7dceba3c77697760f8cb4ca25c33fa51c60560de4";
    };
}
