# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IConv";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AL/ALOREN/Perl6/IConv-0.0.2.tar.gz";
        sha256 = "3cceaf0d09a398ef04eef4fb1851d50fe2154fc92ea1a0b5a5681c52f316677c";
    };
}
