# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Ident-Client";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/yuvipanda/perl6-Ident-Client/archive/b5dc48a1260f08bf4910121aeb3c043ed740d4b4.tar.gz";
        sha256 = "1bd73043de70f115c703ba58c35317f23c6a99b7ff8c9f46cccb468541fcb8dd";
    };
}
