# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IDNA-Punycode";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FROGGS/p6-IDNA-Punycode/archive/6476c14c967f730798eed638a55c25cd7f8b5a4e.tar.gz";
        sha256 = "c3810ad80062ac6f85193c63b412644ed537e8b391becbc8e60f0d06348c64cb";
    };
}
