# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "if";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FROGGS/p6-if/archive/d4ef4186a0837b405dfda652d3ed58ceecb0a082.tar.gz";
        sha256 = "acc20f3285ba9f7738676391288d7d47ea51b352b25432f3d7c20d2fc90586e8";
    };
}
