# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ignore";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Find" ];
    src = fetchurl {
        url = "https://github.com/Heather/ignore/archive/6901aecff4c02a1751d277c263b0f5da90c637bd.tar.gz";
        sha256 = "bc67d203154609686e63f5f13408d4543b07fb7b01c13de7cea50b1d19823441";
    };
}
