# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Image-Libexif";
    buildDepends = [  ];
    depends = [ rakuPackages."NativeHelpers-Blob" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Image-Libexif-0.1.0.tar.gz";
        sha256 = "4e34c932f022f0a3f09d9ad7586f0d42628563724c8fe59134743449ffd776bb";
    };
}
