# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Image-PNG-Portable";
    buildDepends = [  ];
    depends = [ rakuPackages."Compress-Zlib" rakuPackages."String-CRC32" ];
    src = fetchurl {
        url = "https://github.com/raydiak/Image-PNG-Portable/archive/def950367201a02c098ab7acea6fd1f4468d4eca.tar.gz";
        sha256 = "806d1407f7451491fe4e98a4b0bc3f1837349e3e41b723e311133e2a9fa0fe1d";
    };
}
