# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Image-RGBA-Text";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/cygx/p6-image-rgba-text/archive/e11a2db7909af7bdcb6353029a1c74394c59e44f.tar.gz";
        sha256 = "1e671f016f550d50be6bd471f92914e0dbd020f80cec7c77e0db3411ad2566c9";
    };
}
