# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Image-RGBA";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/cygx/p6-image-rgba/archive/a9f689fa689bec9cf902cf35e6a8375c07f8d529.tar.gz";
        sha256 = "a2ac48019438db2487c81f7b8056f469553dd46b03db68e7f6b78a78a2ce0cf9";
    };
}
