# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Image-QRCode";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Image-QRCode-0.0.5.tar.gz";
        sha256 = "9abb96f1b717af3b6237cb2b53edc4bdd0a51790adc55515e66c690997e3836a";
    };
}
