# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Imlib2";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" ];
    src = fetchurl {
        url = "https://github.com/hankache/perl6-Imlib2/archive/c04089abc18d3aaabe3d420abb5f210b80ba62d3.tar.gz";
        sha256 = "55e99e933c6a8760e6b4543414ca3a45659696c30d20738c522554492953e0db";
    };
}
