# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Ini-Storage";
    buildDepends = [  ];
    depends = [ rakuPackages."Path-Util" ];
    src = fetchurl {
        url = "https://github.com/jaffa4/inistorage/archive/3dc0b497c867103c2378b971baff8b996f211f7d.tar.gz";
        sha256 = "bef384aaa9cbaae85505a918fe4b3334599a15531e8b76d64801fbbcb94f425e";
    };
}
