# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Inline";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FROGGS/p6-Inline-C/archive/1f00cf2dd7ccf09d0e0f94a63914ea4a9ca49270.tar.gz";
        sha256 = "dac859b2b80a7531fdfc6fac9c5fd48643bcdf74a831e95292e211afdcdb003d";
    };
}
