# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Inline-Python";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/niner/Inline-Python/archive/53a1c2ca1751b5928909d929493e5ed29a721d02.tar.gz";
        sha256 = "ae0ebce0b6bff32733ab80d700549c7baacab6f7a2258d1b3b3358be9842b2a8";
    };
}
