# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Inline-Python";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/niner/Inline-Python/archive/7ceee0baf3c47cdb35fcf6bfa3e83d43b0fc3e8c.tar.gz";
        sha256 = "1bcfa86c533c12f029a944e7681281d78f19bae7fe5a7632d70c1c109c72e816";
    };
}
