# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Inline-Perl5";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/N/NI/NINE/Perl6/Inline-Perl5-0.44.tar.gz";
        sha256 = "52db124fd7f1f7faa904524a5e918046a7e9e72bd9811a0f92261e33cc772c88";
    };
}
