# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Inline-Brainfuck";
    buildDepends = [  ];
    depends = [ rakuPackages."Term-termios" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Inline-Brainfuck/archive/0e53686a77bb6b9592985af5238648cdaec61392.tar.gz";
        sha256 = "5b219bad50a5859e6982b67cf6e7899a346e2caefb72c279c86d1513cc0f63fc";
    };
}
