# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Inline-Scheme-Guile";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" ];
    src = fetchurl {
        url = "https://github.com/drforr/perl6-Inline-Scheme-Guile/archive/a7cc8b555784d3bc44198139008f93c604f6a300.tar.gz";
        sha256 = "de8f915cb1f70717ca4a0022e1c564da41eb02c5d0f84ca8c8a16a19067aafbf";
    };
}
