# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Intl-LanguageTag";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/alabamenhu/bcp47/archive/3d41cecc46782cfb65b24a7140fc8a4fd52a4df9.tar.gz";
        sha256 = "5486d5c6df34e65a19d15c4ae0e38da81e8c3aaf2f47e023fd8e01dd51d003eb";
    };
}
