# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Intl-UserLanguage";
    buildDepends = [  ];
    depends = [ rakuPackages."Intl-BCP47" ];
    src = fetchurl {
        url = "https://github.com/alabamenhu/UserLanguage/archive/54809344a803c0187d809787e8cbe5eb3a9f2744.tar.gz";
        sha256 = "3b0e2a7aee977e54b6fe7d611abebac11db83e272a72954dd5b57d9600fc44be";
    };
}
