# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Intl-CLDR";
    buildDepends = [  ];
    depends = [ rakuPackages."Intl-BCP47" rakuPackages."Intl-UserLanguage" ];
    src = fetchurl {
        url = "https://github.com/alabamenhu/Intl-CLDR/archive/fb8bd76768bd815397ee62df11951703bd959ff5.tar.gz";
        sha256 = "15edc93caabfb25bc787f61bee62e5f8e15a9f38f0ede0f0c9efcd57a00c193c";
    };
}
