# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-Capture-Simple";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/sergot/IO-Capture-Simple/archive/360a6bed347723940b9f0fb12be04cb5ec84f350.tar.gz";
        sha256 = "14e3bb296434ef3a850d0da31552c0627398267161241c3a66d6cc2aff57eb04";
    };
}
