# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-Glob";
    buildDepends = [  ];
    depends = [ rakuPackages."Test" rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/IO-Glob-0.6.tar.gz";
        sha256 = "025f072044fcf9500ae556684db1974d996f6885b235fe14b8bd1f07d4cab8f5";
    };
}
