# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-Notification-Recursive";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Find" ];
    src = fetchurl {
        url = "https://github.com/perlpilot/p6-IO-Notification-Recursive/archive/df50aad31bbd45f74170bad154a1eccf2f313484.tar.gz";
        sha256 = "762c200457e5ec4567a23a5d8580e9f3ba12f73db5db59c55ffe745f792d9ebc";
    };
}
