# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-Path-ChildSecure";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-IO-Path-ChildSecure/archive/d98c6f45c8a7152e3676b0c39166a62598dbcbf4.tar.gz";
        sha256 = "3e0c1b75ba9881489994d579507de1bec451bb2d5fbec88e8ddd778d87ae381e";
    };
}
