# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-Path-XDG";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/IO-Path-XDG-0.1.0.tar.gz";
        sha256 = "afcd7ab772ee45c069dc150be7e3321f5cb91742591810b40bf6bb5c84853b2e";
    };
}
