# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-Socket-Async-SSL";
    buildDepends = [  ];
    depends = [ rakuPackages."OpenSSL" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/IO-Socket-Async-SSL-0.6.tar.gz";
        sha256 = "9e8678c788052fef6b5d4fc44c5e2e6f8211e58b7df513c963e3934ecd532cea";
    };
}
