# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-Socket-SSL";
    buildDepends = [  ];
    depends = [ rakuPackages."OpenSSL" ];
    src = fetchurl {
        url = "https://github.com/sergot/io-socket-ssl/archive/f07010c8965855ff734de297466c883afffbb560.tar.gz";
        sha256 = "0ff75ec310b1ef175c62974646820f43f8d7249a0f5c905caa8c8e9d13691a56";
    };
}
