# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IO-TailFile";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/skaji/perl6-tail/archive/f365fa1e130fabebdda4774d10261474cb6dc437.tar.gz";
        sha256 = "93d8a20451fbf9d0066d9fd1ac57b754aceaa6c13663fcfc62b7a282403dab64";
    };
}
