# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IP-Addr";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/V/VR/VRURG/Perl6/IP-Addr-v0.0.2.tar.gz";
        sha256 = "43338ac4448feb282027c7d8d9abf2c04ed1e0c6504cf586f1ef2310b3fb4ad6";
    };
}
