# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IP-Addr";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/V/VR/VRURG/Perl6/IP-Addr-v0.0.3.tar.gz";
        sha256 = "87f702efc51f70199223e6774260e0ffa61aae97299e7375a7aa12e307afaa74";
    };
}
