# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IP-Random";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMASLAK/Perl6/IP-Random-0.0.10.tar.gz";
        sha256 = "9e9509fd4e1ecaf5f03fe991c4e6377e8c88b068ca6fb3749cdabf70990c68a3";
    };
}
