# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IRC-Client-Plugin-NickServ";
    buildDepends = [  ];
    depends = [ rakuPackages."Config" rakuPackages."IRC-Client" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/IRC-Client-Plugin-NickServ-0.2.1.tar.gz";
        sha256 = "072f55cce357ea1fd5a4e9af6cbf6afb91f671a44edb32733784206ce96fc004";
    };
}
