# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IRC-Client-Plugin-Factoid";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" rakuPackages."IRC-Client" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-IRC-Client-Plugin-Factoid/archive/11c37a8b67669a5e4f9839919cbe5ca0e7d756d4.tar.gz";
        sha256 = "c6cfdf90ac799c922ba7513756fe819e7d089438f70e8be6a449a69590f924a9";
    };
}
