# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IRC-Client-Plugin-Ignore";
    buildDepends = [  ];
    depends = [ rakuPackages."IRC-Client" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/IRC-Client-Plugin-Ignore-0.1.0.tar.gz";
        sha256 = "3035567f9db1bb95b0c03ed47f0da63acbab4a0b0c80e6904366ad99367c00d0";
    };
}
