# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IRC-Async";
    buildDepends = [  ];
    depends = [ rakuPackages."Readline" ];
    src = fetchurl {
        url = "https://github.com/scovit/perl6-IRC-Async/archive/0748d970df2e44e6370e359c993c66d53bb48380.tar.gz";
        sha256 = "8543be77a2e9ac4faf4c46d7bc317938e7aeb8840cdeedcd9e075be02e7c7f7d";
    };
}
