# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IRC-Client";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-IRC-Client/archive/b8b0bc91c9a7882451d76a8cf4256ccc12cf1189.tar.gz";
        sha256 = "98a63c750233a5ad1c69443da5321fe3ad8b33dc2d42e339709e948423ec4f67";
    };
}
