# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IRC-Client-Plugin-UrlTitle";
    buildDepends = [  ];
    depends = [ rakuPackages."HTML-Entity" rakuPackages."HTML-Parser-XML" rakuPackages."HTTP-UserAgent" rakuPackages."IO-Socket-SSL" rakuPackages."IRC-Client" rakuPackages."IRC-TextColor" rakuPackages."URL-Find" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/IRC-Client-Plugin-UrlTitle-1.1.3.tar.gz";
        sha256 = "f34eb3069b89a90b7d67ff7d2661d5a8d6278e4de6ec9807741815328719aef8";
    };
}
