# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "IRC-TextColor";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/samcv/IRC-TextColor/archive/d29948457feb9f55f2815f1c520bc1401b9b8fa2.tar.gz";
        sha256 = "193889b851d9947fc192059eb58e6492109fe3156465f17f3e93ac2625e19bc8";
    };
}
