# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "JSON-Unmarshal";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" rakuPackages."JSON-Name" ];
    src = fetchurl {
        url = "https://github.com/tadzik/JSON-Unmarshal/archive/e1b6288c5f3165058f36c0f4e171cdf2dfd640da.tar.gz";
        sha256 = "6232b8c68ad617f956e7b234d7ab52e706749e55e5f0010bfa9817df3fa12fac";
    };
}
