# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "JSON-Stream";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/FCO/json-stream/archive/a940967d6f90bea42b8cd8ed034bc82759372f6a.tar.gz";
        sha256 = "818c2e3104c9d5cae2aff9af44b48b437d5b9c1828b2acfa2d5a3cedf3c4ca83";
    };
}
