# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "JSON-WebToken";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest-HMAC" rakuPackages."Digest-SHA" rakuPackages."JSON-Fast" rakuPackages."MIME-Base64" ];
    src = fetchurl {
        url = "https://github.com/jamesalbert/JSON-WebToken/archive/ef38836334bcb4f1136eadc1e492dbd1d8ca69e1.tar.gz";
        sha256 = "3201d5be4436c7982d057611a5cd28ce6a4fa545b142b03ab07af05704e16aea";
    };
}
