# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "JSON-Pointer";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/JSON-Pointer-1.0.tar.gz";
        sha256 = "7e0072548435fff9a21795370c63cbaf28dc542ec195b3637e2f4c4d6f2dd021";
    };
}
