# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "JSON-Path";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/JSON-Path-1.7.tar.gz";
        sha256 = "71455bc99e00333588cdbde4fe6dfefd134301ac291897bd17ea3196c8f1a54d";
    };
}
