# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "JSON-Pretty";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" ];
    src = fetchurl {
        url = "https://github.com/FROGGS/p6-JSON-Pretty/archive/c7c90d7358e4c806ee5460dfa25cb248e75c31a5.tar.gz";
        sha256 = "a86595882fa45ff8d9d21ebc0296db1518f93244cc5a3ed5a4abadf5dacd56a1";
    };
}
