# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "KHPH";
    buildDepends = [  ];
    depends = [ rakuPackages."Base64-Native" rakuPackages."Compress-Bzip2" rakuPackages."Terminal-Readsecret" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ML/MLDEVINE/Perl6/KHPH-0.0.9.tar.gz";
        sha256 = "2e6882139f8c63b83ea8e2e02498de2edc35b51bba87f8ac55daa357454f7b83";
    };
}
