# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lazy-Static";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SA/SAMGWISE/Perl6/Lazy-Static-0.0.1.tar.gz";
        sha256 = "c43731373aaa93a8eda50c7d725e4867572c258bfc26d78dc691742126d907ec";
    };
}
