# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "LCS-All";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/wollmers/P6-LCS-All/archive/2ff4926dc74d570e66862b9cec997c3926988a72.tar.gz";
        sha256 = "d0afb6339297b825f5fd7a6e022f4faeb299358196954c20f3f375fc21d92202";
    };
}
