# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "LendingClub";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" rakuPackages."Net-HTTP" ];
    src = fetchurl {
        url = "https://github.com/peelle/LendingClub/archive/f5706017231a6b80623cd7689421840ca04c0a7c.tar.gz";
        sha256 = "b52a68b62022248da1716c3981ca1ad5b9d7c8d5e4403614080e84ec64558cdb";
    };
}
