# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Libarchive";
    buildDepends = [  ];
    depends = [ rakuPackages."Archive-Libarchive-Constants" rakuPackages."Archive-Libarchive-Raw" rakuPackages."BitEnum" rakuPackages."NativeHelpers-Callback" rakuPackages."Number-Bytes-Human" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/Libarchive-0.1.tar.gz";
        sha256 = "1fcd14bb9c8a1b5dd6145bf092d03df8400dd9a865b0fe8a1453afde5f2c137b";
    };
}
