# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
curl }:
rakuPackage {
    name = "LibCurl";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/LibCurl-0.9.tar.gz";
        sha256 = "937508b3646a8db98d74e624c78b27a3f729c4cf9a83414d2447e535be152d9e";
    };
    preInstallPhase = ''
        ldLibraryPath=${lib.makeLibraryPath [ curl ]}
        export LD_LIBRARY_PATH=$ldLibraryPath:$LD_LIBRARY_PATH
    '';
}
