# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Libclang";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AZ/AZAWAWI/Perl6/Libclang-0.2.0.tar.gz";
        sha256 = "f3fda8c3d11057cc8e336c9a673868bec49bbfff70dfb968f4a6ace95d41f088";
    };
}
