# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "LibGit2";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/LibGit2-0.2.tar.gz";
        sha256 = "04e695ba3d091ec11722ac76260419a76aa3868b94862411b1facd5874e80de6";
    };
}
