# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "License-SPDX";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Class" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/License-SPDX-3.7.1.tar.gz";
        sha256 = "55ad4745f809fb59e9d338022f14ab8237efcb442afe78ebe6794c49a1470252";
    };
}
