# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "License-SPDX";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Class" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/License-SPDX-3.8.0.tar.gz";
        sha256 = "648ace9ddc79e8eb355cda2be88b36d5105c13420106403b4f879cf6c18ea375";
    };
}
