# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-Pangram";
    buildDepends = [  ];
    depends = [ rakuPackages."Pod-To-Text" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FI/FISCHER/Perl6/Lingua-Pangram-0.1.1.tar.gz";
        sha256 = "989ada8f9947f6c03c3e73c5e5cc08c0b15dd709ba18248dfaa430828c950bcc";
    };
}
