# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-EN-Syllable";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/coke/p6-lingua-en-syllable/archive/4b0c45911341b15186256d90e01da9719d7a03a8.tar.gz";
        sha256 = "942934977db38e941085c33fdc89c170af052662fd0b7d0021b27c87a0bbde31";
    };
}
