# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-Conjunction";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Lingua-Conjunction/archive/3c3b02fed05d700b2e86b19db2471b79b579ece8.tar.gz";
        sha256 = "228113a96ef84751f6e4c635d19ef5b71a3c635b29fee84fa44b2b3f952e64c6";
    };
}
