# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-Palindrome";
    buildDepends = [  ];
    depends = [ rakuPackages."Pod-To-Text" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FI/FISCHER/Perl6/Lingua-Palindrome-0.1.0.tar.gz";
        sha256 = "8e089d5398787d8f121048bb82532faec0541de17f973ad2bb398697a0a7f11b";
    };
}
