# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-Lipogram";
    buildDepends = [  ];
    depends = [ rakuPackages."Pod-To-Text" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FI/FISCHER/Perl6/Lingua-Lipogram-0.1.0.tar.gz";
        sha256 = "5997b9b1b263978f4bc2980b8b5998e17f3e8b6e9d65485724f2f6ee8fd81c6f";
    };
}
