# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-EN-Numbers";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Lingua-EN-Numbers/archive/08460ff1e3f8a3e95d276b1e9997db48e8c28799.tar.gz";
        sha256 = "aeb415cf973547b298d4bafed40a209f2c81c6530cd18c46b3b6cb93dd6e1d69";
    };
}
