# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-EN-Sentence";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/dginev/perl6-Lingua-EN-Sentence/archive/c24517d5be9ea370db6189a2a21b2190d720acee.tar.gz";
        sha256 = "5485a1b7d5b29c5077cdc628cac15f5548eb967a7665118da6c5a0e9424165f7";
    };
}
