# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lingua-Unihan";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" rakuPackages."Encode" ];
    src = fetchurl {
        url = "https://github.com/fayland/perl6-Lingua-Unihan/archive/2b98c30c9a0bb25824922f2c7c20935a4afaf5ac.tar.gz";
        sha256 = "3ea7a66946a36124739ea0b2db76a04669cc133d3fb15b2fd374606171ed44a5";
    };
}
