# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Linux-Cpuinfo";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Linux-Cpuinfo-0.0.10.tar.gz";
        sha256 = "42fc3f6a8ef2ec047ba034b4f635a8156d3f0a03b895daf91704265bc85c1525";
    };
}
