# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Linux-Joystick";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Linux-Joystick/archive/4446993a8654a881178ad51105b79cb36e96fc49.tar.gz";
        sha256 = "7371f89f8992dcaafb6b63083b2cb666efe0a7a63d56717da2b7badf30bfea62";
    };
}
