# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Linux-Proc-Statm";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Skarsnik/p6-linux-proc-statm/archive/3c693653154614ff5e4d22b8120e87b3b5d788b6.tar.gz";
        sha256 = "64b21017142587bdc7a6ba75387d2ffd857fdf22fc6234ba518e297461c4cb74";
    };
}
