# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "List-Utils";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/colomon/List-Utils/archive/b8eb232844b3b308f2b53af2b4a971e3076bcdf3.tar.gz";
        sha256 = "95df55d283d4fc525b9b90e398f115c1f0b7e17553320f3f35819c7157569599";
    };
}
