# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "List-UtilsBy";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/List-UtilsBy-0.0.5.tar.gz";
        sha256 = "11cd972d7bd6d330437dcf621cbc8ce06603bf00f151e6ef04d60051a5154ff0";
    };
}
