# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "LLVM";
    buildDepends = [  ];
    depends = [ rakuPackages."NativeHelpers-Blob" ];
    src = fetchurl {
        url = "https://github.com/ALANVF/Raku-LLVM/archive/990de397e575a122e6045f59908b6366aa719c9e.tar.gz";
        sha256 = "cb044a8732b0b4ab3a8e402e39d22ab607e8f4fb225ba4d70af0797dd03c6d40";
    };
}
