# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Locale-Codes";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/fayland/perl6-Locale-Codes/archive/07bf8816f4f9f305b46f7b8f9029a00264ce0053.tar.gz";
        sha256 = "3599eb3ee3307b64f6a3bc6abd43dc0f17827ef7f69b6c170a4dbaf472e45aa3";
    };
}
