# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-Timeline";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/Log-Timeline-0.3.tar.gz";
        sha256 = "68ce3d4a0740b98fc6fbe0950d08dac41d32d1f5d24a2168da708ed7dbe16bb3";
    };
}
