# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-Minimal";
    buildDepends = [  ];
    depends = [ rakuPackages."Grammar-Tracer" rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MO/MOZNION/Perl6/Log-Minimal-0.0.1.tar.gz";
        sha256 = "5725e70d619252e05bd688499760f44434f42ad6e46190d95a4f0c586b89467b";
    };
}
