# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-Syslog-Native";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Log-Syslog-Native-0.0.9.tar.gz";
        sha256 = "d4d1dc06958cb65e8e5092c64067d0150e4ba1af113d1c9f2ed850a97e4ba0b2";
    };
}
