# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-Minimal";
    buildDepends = [  ];
    depends = [ rakuPackages."Grammar-Tracer" rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://github.com/moznion/p6-Log-Minimal/archive/3d3b8d481b84b1babdf7b27d1cc87f9b7ddbace0.tar.gz";
        sha256 = "dad9fa74adbfb24d15ca6bd450e0b9e88a6cbd3a1e8b50f8e1e7f09df662ddd8";
    };
}
