# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-D";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jaffa4/logd/archive/eab4b880555d643066106e0e80cb320d50f364b0.tar.gz";
        sha256 = "fa520c75eef770582b94f00c04f87a6237004c73aa9361b232c2d5d5e372e21e";
    };
}
