# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-Async";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/bduggan/p6-log-async/archive/cdd568dcfbe57ebafbc1553d5a4e0879d356457b.tar.gz";
        sha256 = "90348357a2515997f1c5f52a08d70ad6423aec2fa44afc869e901999ea650e2e";
    };
}
