# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-ZMQ";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" rakuPackages."Net-ZMQ" ];
    src = fetchurl {
        url = "https://github.com/gabrielash/p6-log-zmq/archive/c0fc3bd4ac74e155e05f218089d2bc4fe8da3afa.tar.gz";
        sha256 = "39e0af343d085c685ea6346d2021bead88a88ec87f01a441b91877b654f50000";
    };
}
