# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log-Any";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jsimonet/log-any/archive/9e427611ffb16d9d6bad7df1eb9530a96f2faac3.tar.gz";
        sha256 = "531190d88654ffd4648ed17d417b5c19aa4bf302527aabd4212a45f7e2e59d39";
    };
}
