# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Log";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/whity/perl6-log/archive/8214583f86ff82e3ce2e8a50dbcd4f08e05d5397.tar.gz";
        sha256 = "209af9ca6b4cdf7c8f3c66b108f4ef8cafcd1f0d4ee4eb8fd4faf8bcb638993b";
    };
}
