# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "LogP6-Writer-Journald";
    buildDepends = [  ];
    depends = [ rakuPackages."LogP6" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AT/ATROXAPER/Perl6/LogP6-Writer-Journald-1.3.3.tar.gz";
        sha256 = "527fc4762c7cc6276c328367b02fe47a334f9d11531987ec1c80e8c04e74b9be";
    };
}
