# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lumberjack-Application";
    buildDepends = [  ];
    depends = [ rakuPackages."Crust" rakuPackages."HTTP-Server-Tiny" rakuPackages."HTTP-UserAgent" rakuPackages."JSON-Class" rakuPackages."Lumberjack" rakuPackages."Template6" rakuPackages."WebSocket" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Lumberjack-Application-0.0.7.tar.gz";
        sha256 = "5abb59f43dabad364ee281c6da9a9fa36d8a1117678b085475392d65e38ed34f";
    };
}
