# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lumberjack";
    buildDepends = [  ];
    depends = [ rakuPackages."DateTime-Format" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Lumberjack-0.0.9.tar.gz";
        sha256 = "9ca127f45db2dd12ad3fd7d893908dc2be7b9f75f482b2bf48aa850c36d9c466";
    };
}
