# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Lumberjack";
    buildDepends = [  ];
    depends = [ rakuPackages."DateTime-Format" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Lumberjack-0.0.10.tar.gz";
        sha256 = "b2b2a6432ce88cd1a0615d9ad8c95edb53dce2fef1098b04bc8988b271bc8943";
    };
}
