# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "LWP-Simple";
    buildDepends = [  ];
    depends = [ rakuPackages."MIME-Base64" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://github.com/perl6/perl6-lwp-simple/archive/944fad322b0ed14f4966374b3ef9487abc9240a4.tar.gz";
        sha256 = "09842010c8a3a841cb2f1a903ff31a2dbccff7ee3973cbf01d9df45dad891ec1";
    };
}
