# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "LZW-Revolunet";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KN/KNARKHOV/Perl6/lzw-revolunet-perl6-0.0.11.tgz";
        sha256 = "f37bf5b1557c8bbbcdd28fa8ae698dbc5d66773b45d32bd9f09b91ab76ea85be";
    };
}
