# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MagickWand";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AZ/AZAWAWI/Perl6/MagickWand-0.1.0.tar.gz";
        sha256 = "b7514657c4e807b775e5c7f205981f4226788b80f65ce5bc9187f680f4882499";
    };
}
