# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "mandelbrot";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/colomon/mandelbrot/archive/b2d3a7b99faf0f59e061a4cefdb0f7e47ca47635.tar.gz";
        sha256 = "08bf6edf70d36f7f47641c89ae3cbdc86258efa00525f5059166139849f57e5e";
    };
}
