# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Manifesto";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Manifesto-0.0.4.tar.gz";
        sha256 = "f171c934ea8cc161f778223175e4fc5bd0bd17a36b9d5959779e06e1b14b0aa2";
    };
}
