# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Markit";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/U/UZ/UZLUISF/Perl6/Markit-0.0.1.tar.gz";
        sha256 = "2e83a169b1961f63520c8d659d75f4661b4ba344e65f3206496df03f6431f5e9";
    };
}
