# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Model";
    buildDepends = [  ];
    depends = [ rakuPackages."Math-RungeKutta" rakuPackages."SVG" rakuPackages."SVG-Plot" ];
    src = fetchurl {
        url = "https://github.com/moritz/Math-Model/archive/cdc618c6c028a6dd9308bd2de0df9f10afd095a3.tar.gz";
        sha256 = "210c0a1ca113d1319726bbd71ce79950f36a92097703dcc92705b851b660555d";
    };
}
