# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Libgsl-BLAS";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" rakuPackages."Math-Libgsl-Complex" rakuPackages."Math-Libgsl-Constants" rakuPackages."Math-Libgsl-Matrix" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Math-Libgsl-BLAS-0.0.3.tar.gz";
        sha256 = "b2f524e6183d2e8fba4a54771c8bc31da8a1b146ad0a3f3dc4685aab76a50644";
    };
}
