# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Libgsl-Sort";
    buildDepends = [  ];
    depends = [ rakuPackages."Math-Libgsl-Constants" rakuPackages."Math-Libgsl-Matrix" rakuPackages."Math-Libgsl-Permutation" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Math-Libgsl-Sort-0.0.2.tar.gz";
        sha256 = "1c771ca6d41d39bd8f97e1ec47ebf61e31ceec0cb9f43d2c94872255a6080e12";
    };
}
