# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Factorial-Operator";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RI/RIBNOTTER/Perl6/Math-Factorial-Operator-0.1.2.0.tar.gz";
        sha256 = "5d4df6afd10f7c9ad3199c917c1f332fcc8a637f01742a5f65d68466e3fb3fb3";
    };
}
