# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Model";
    buildDepends = [  ];
    depends = [ rakuPackages."Math-RungeKutta" rakuPackages."SVG" rakuPackages."SVG-Plot" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MO/MORITZ/Perl6/Math-Model-0.3.tar.gz";
        sha256 = "58dceeadf82d7814b75d903786da2d9f8ee35f6a0e7dc2d467e6d6984b7313ec";
    };
}
