# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-FourierTransform";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/MattOates/Math--FourierTransform/archive/cc8631926d8ee12e1b8bd1cfa2e740632fd44513.tar.gz";
        sha256 = "c85da02717713922140ebb2042b22c661c1da06415035c725f7935818f3a0cc3";
    };
}
