# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Random";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/bluebear94/Math-Random/archive/a49ea0783459b146e236fb54e08e1ebb0b84dafc.tar.gz";
        sha256 = "fb2b0ba74ba0141208bbaae3bad03940a5888e1daee7cc18aa2dcc780830b0b4";
    };
}
