# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Libgsl-Elementary";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Math-Libgsl-Elementary-0.0.2.tar.gz";
        sha256 = "b32a5ca9b8db842b08fdaf675d7bbc4a5d041806f9536c4a51004ef2494b90ab";
    };
}
