# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Polygons";
    buildDepends = [  ];
    depends = [ rakuPackages."SVG" rakuPackages."SVG-Plot" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/P/PS/PSIXSTEVE/Perl6/Math-Polygons-0.0.4.tar.gz";
        sha256 = "84394236bccff60ba82a75a9b7351c9cd3283d99db48073b3e5d02aa41cae8e1";
    };
}
