# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Libgsl-Complex";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Math-Libgsl-Complex-0.0.4.tar.gz";
        sha256 = "dcc3b2319360c2a9440df70b2a4fc4ffae3561aaebc7b2fb761eab07df62efb2";
    };
}
