# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Arrow";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ajs/perl6-Math-Arrow/archive/bba3ec0d12fef47ba570131bf752c075fe39b6fb.tar.gz";
        sha256 = "c4a72e7cbd4385d40d25d41a0e55ea09c31aceb6e1210296b3aeb6ff0eb9622f";
    };
}
