# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Matrix";
    buildDepends = [  ];
    depends = [ rakuPackages."AttrX-Lazy" ];
    src = fetchurl {
        url = "https://github.com/pierre-vigier/Perl6-Math-Matrix/archive/89521b23e6db28592c529ce9b07fb3ba195c2395.tar.gz";
        sha256 = "71f34f3e1e36cd6b0e9a644dbcf56d5c903db919e97de68fa90d096fb3e3555d";
    };
}
