# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Libgsl-Function";
    buildDepends = [  ];
    depends = [ rakuPackages."Math-Libgsl-Constants" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Math-Libgsl-Function-0.0.1.tar.gz";
        sha256 = "6f25f5f598d91aac05d557eaf479a13b66eb2f7cc3d40982d8622f20f6db4a51";
    };
}
