# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-ConvergenceMethods";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/antoniogamiz/Math-ConvergenceMethods/archive/4f28a877566934c32c16f62eb5703c3fa89fc7fc.tar.gz";
        sha256 = "ae8774eeaa9d6318d914c6f997b485b0787659c49ddbac22af2f7774d28a6b39";
    };
}
