# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Libgsl-Multiset";
    buildDepends = [  ];
    depends = [ rakuPackages."LibraryMake" rakuPackages."Math-Libgsl-Constants" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Math-Libgsl-Multiset-0.0.2.tar.gz";
        sha256 = "f259acf2ef0eaff6d7d74215aac459f2821c81798512577365737c7b95b60ef6";
    };
}
