# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Math-Libgsl-Constants";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FR/FRITH/Perl6/Math-Libgsl-Constants-0.0.4.tar.gz";
        sha256 = "97405a3fe6ece4eeaff0d5d2f3f29de51b8d829df55f6c14d4a4e5a23c0a003a";
    };
}
