# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Matrix-Bot";
    buildDepends = [  ];
    depends = [ rakuPackages."LogP6" rakuPackages."Matrix-Client" rakuPackages."Text-Markdown" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Matrix-Bot-0.2.0.tar.gz";
        sha256 = "bff92844673be9978f961b3a132343ae52fe805f0e53675fac363a996ea8e2b4";
    };
}
