# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Matrix-Client";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-UserAgent" rakuPackages."IO-Socket-SSL" rakuPackages."JSON-Fast" rakuPackages."URI-Encode" ];
    src = fetchurl {
        url = "https://github.com/matiaslina/perl6-matrix-client/archive/ec4393cb81952fffa2273e313818a57c9611c5a2.tar.gz";
        sha256 = "a57bd1398853dcfcb281a5ae6071f341f9017f82f93789fe40da054892028d30";
    };
}
