# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MeCab";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TI/TITSUKI/Perl6/MeCab-0.0.15.tar.gz";
        sha256 = "6c0245398348671ee3d3dc8054c978713ad46de1fc31f77e35cf1ea45724dbf0";
    };
}
