# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MeCab";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TI/TITSUKI/Perl6/MeCab-0.0.17.tar.gz";
        sha256 = "7248c29e19bbc93048540290ec5324249cf2afe1e0ba6fdf9ef7bdbd42a177a4";
    };
}
