# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Memoize";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Memoize-0.0.5.tar.gz";
        sha256 = "7c78e0d3b9a4305b690e826c36cb38fc8fd86c6d0b00607c832a268da460bf1c";
    };
}
