# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MessagePack";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/uasi/messagepack-pm6/archive/711bd11c7e6aeb69d117e0c9b4b9b88efe4d479b.tar.gz";
        sha256 = "fb2bf9e823a0525e273af515423255a6ad9270efc0fd65c7ca28a78c7e4ff31d";
    };
}
