# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MessagePack-Class";
    buildDepends = [  ];
    depends = [ rakuPackages."Data-MessagePack" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/MessagePack-Class-0.0.2.tar.gz";
        sha256 = "cf1c0458140e345caa9db2bbf268d0cf25a1b584d1f19044bb3ec88b717b733c";
    };
}
