# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Method-Also";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Method-Also-0.0.5.tar.gz";
        sha256 = "89e2769c0abb22dd4b558124a75bea8fe098d2374b7e1e39ebf13fb87188007d";
    };
}
