# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Method-Also";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Method-Also-0.0.4.tar.gz";
        sha256 = "bd426fce1dedc578a1e0d2aea7fdd02b0c4c7d80c5d28ac9c708d89f6a9ba6cf";
    };
}
