# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MIME-Base64";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perl6/Perl6-MIME-Base64/archive/4c0acad236679037e99be92b23463245cfeda800.tar.gz";
        sha256 = "f874cfd655bb316634b47e454b58ef4bdbe7da25dcf9f780997801560c0b718d";
    };
}
