# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MIME-QuotedPrint";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/retupmoca/p6-MIME-QuotedPrint/archive/a4149c73c9ba95c4d0ee3b7a7a03eff9410c5f69.tar.gz";
        sha256 = "9a8ab7e3b09b939809e126f0aeb50c7e301c8e17e89833c2b78283d0530acc95";
    };
}
