# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Module-Toolkit";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Find" rakuPackages."JSON-Fast" rakuPackages."Shell-Command" rakuPackages."TAP-Harness" ];
    src = fetchurl {
        url = "https://github.com/tadzik/Module-Toolkit/archive/659aee08c46e133c91a8619019a7b724f8e7b2ca.tar.gz";
        sha256 = "4afbafab8aa7235f6aa131c115a086a244806da428af7583d0dbee0cada780c0";
    };
}
