# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Module-Pod";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/D/DM/DMAESTRO/Perl6/Module-Pod-0.9.1.tar.gz";
        sha256 = "c55b812d64c8f3821a2615a849a8d13bbe2ca7d767f7066bdfb031df5849f126";
    };
}
