# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Movieinfo";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" rakuPackages."Net-HTTP-GET" ];
    src = fetchurl {
        url = "https://github.com/palapitta/Movieinfo/archive/a392a385fbb3fa9eaf83a528f91e1453ad9ffadb.tar.gz";
        sha256 = "097f20cf2b028d7a1babbd23ffca910accc3d7fc42455d6df46eda2bd40bf1ab";
    };
}
