# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "MQTT-Client";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Juerd/p6-mqtt/archive/fbc30403c0579ac2fba69e7f69076caf9958df77.tar.gz";
        sha256 = "562d5b48146f3c216122257800dff1eb22afa0bfc8ad00a78b123661992dc310";
    };
}
