# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Music-Engine";
    buildDepends = [  ];
    depends = [ rakuPackages."Math-Curves" rakuPackages."Net-OSC" rakuPackages."ScaleVec" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SA/SAMGWISE/Perl6/Music-Engine-0.0.2.tar.gz";
        sha256 = "06a673c5e85e740a45bc5b20dcebf5b80384cca2f22f2e71f935432a946e16b6";
    };
}
