# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Native-Exec";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/Native-Exec-0.1.tar.gz";
        sha256 = "d4ebf9753ee8aa4ffea6a0536b836f55afa576a1e84f6dc6dc01a2219919dbd4";
    };
}
