# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "NativeHelpers-Blob";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/salortiz/NativeHelpers-Blob/archive/b00a4899ce219dae5fe97e9e414d01dd92874f53.tar.gz";
        sha256 = "87d03555ea7bb63ba721f43b6f64139e5c41066361d96a259582f333d6858230";
    };
}
