# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "NativeHelpers-Callback";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CT/CTILMES/Perl6/NativeHelpers-Callback-0.1.tar.gz";
        sha256 = "22865fd98021c39512cc2360fd8c9e6650be40d2dc89f789825baf9ebd2a9285";
    };
}
