# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Native-Packing";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/Native-Packing-p6/archive/23dcfc761d0c0c0b0032d7cb8dce1e32ce387794.tar.gz";
        sha256 = "f78bbca2db7023bdb758e07b2df27f24683a5270df563db9a74e78eea35c1fe6";
    };
}
