# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "NativeHelpers-CBuffer";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/scovit/NativeHelpers-CBuffer/archive/a4c923d6ba0bc0a742ac18f6539199c65b7e9fa0.tar.gz";
        sha256 = "b585425d9dec2790ed5168a9f0f25dfdda95f2643014c2e8bfcfaebea2133ce6";
    };
}
