# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "NCurses";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-ncurses/archive/91cc41f8f4dce10f7d659fe39b971d7796ea8a5e.tar.gz";
        sha256 = "1f6340d0ddd82601270d56a63a907266b989cfb56a6598aea53b8d5e0032eb3a";
    };
}
