# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-Telnet";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Net-Telnet-0.0.2.tar.gz";
        sha256 = "02f8da08ff05f1a55a9563fdcb48c74957c0c3d9435148eba32a44445bcc984a";
    };
}
