# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-Curl";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-net-curl/archive/6058c370112a2477b71608ee273231cde1d8f4ae.tar.gz";
        sha256 = "1269e4e8d6fe92684845973f95e6e5f52b388477f7ef29a4e74d58375df18d51";
    };
}
