# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-POP3";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest" rakuPackages."IO-Socket-SSL" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Net-POP3/archive/95f7fee3c1907d22c0775af082a50135fc792000.tar.gz";
        sha256 = "fa25d63a1c7706560452f0fd4452c30ab55812836ba897bff9fffed24a929e34";
    };
}
