# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-netent";
    buildDepends = [  ];
    depends = [ rakuPackages."P5getnetbyname" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Net-netent-0.0.2.tar.gz";
        sha256 = "c90da3e8991e5c993b0544b0f358895a00f7fb3f96e0437d549b83d6f989691f";
    };
}
