# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-BGP";
    buildDepends = [  ];
    depends = [ rakuPackages."DateTime-Monotonic" rakuPackages."NativeHelpers-Blob" rakuPackages."OO-Monitors" rakuPackages."StrictClass" rakuPackages."TCP-LowLevel" rakuPackages."Terminal-ANSIColor" rakuPackages."if" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMASLAK/Perl6/Net-BGP-0.1.8.tar.gz";
        sha256 = "87b0f89341625a3c8e68ed7249be490e331118212dbdce71e21ea184bbfc89ca";
    };
}
