# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-AMQP";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Net-AMQP/archive/0859532137131a6c3c3fea770129b56006cd4c4f.tar.gz";
        sha256 = "fecb8c8fd33b06e2858aee0302153ad2f5e7ad820bb5c4a606f4115bd098192d";
    };
}
