# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-IRC-Bot";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/TiMBuS/Net--IRC/archive/cfc00411fd10eb41c63c90a7e82f451b6c9127bf.tar.gz";
        sha256 = "26d30499880cc1ef4740c76c51c8cad9322e554b92b698af44b8862a721e7d14";
    };
}
