# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-AMQP";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Net-AMQP/archive/60a78b8d8e1fd2b878f68978c8d7356ab3a8f6ee.tar.gz";
        sha256 = "1a58cb9c49456f8dfe9aa7159c861792abd20dea3efb040d275499dfc3959c08";
    };
}
