# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-RCON";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/shuppet/p6-net-rcon/archive/6ee477fafe93ae726d06225c2a7e4d87adb12421.tar.gz";
        sha256 = "72dfa42af303ad1aed26bb5cb2bee3ae004332a71d0e254668642d3bcd45c0dc";
    };
}
