# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-SMTP";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest" rakuPackages."Digest-HMAC" rakuPackages."Email-Simple" rakuPackages."IO-Socket-SSL" rakuPackages."MIME-Base64" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Net-SMTP/archive/7f67d5067a7a97b09b794e701a27c16fd2f6bee3.tar.gz";
        sha256 = "35b540fcfd2d510cd4f2689a479c64cb03b28388f9ac95b5d1009c90fa1f1c33";
    };
}
