# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Net-XMPP";
    buildDepends = [  ];
    depends = [ rakuPackages."MIME-Base64" rakuPackages."Net-DNS" rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/kalkin/Net-XMPP/archive/855e6ae2606bfed6fc60a9c71a52ae27716015d9.tar.gz";
        sha256 = "e0d7ff8c537f8ffc89502c8e15d689c1effe3a54157cbf62244e5ba8ce75fd13";
    };
}
