# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "November";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest" rakuPackages."HTML-Template" ];
    src = fetchurl {
        url = "https://github.com/viklund/november/archive/24117b2d001572f25cfa6fffeea9e2b9a84ed411.tar.gz";
        sha256 = "f1e70bfbff3723c70e22f52c70722dbb70ef93dfb92dd18ce12ed4991b69ee19";
    };
}
