# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Number-Bytes-Human";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/dugword/Number-Bytes-Human/archive/b610a5cbda9db2b348bcaf01b622108e817f3d3b.tar.gz";
        sha256 = "aeb22ee4d8a6059eebecf18a1a7c5950ee0d34d5e76436728f02558b01b7f684";
    };
}
