# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Object-Container";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/moznion/p6-Object-Container/archive/bf1ad6154c7c192cbc44948c510d86f70f5665e8.tar.gz";
        sha256 = "4d8f3fd406c2a22c9af651c4ab1eb0d36db5b77c6069799b7babce521062cfc2";
    };
}
