# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Object-Permission";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Object-Permission-0.0.3.tar.gz";
        sha256 = "e9d49090eaec8954e595d94a74ecc58c37fd9cb8d964cd3c8b51a765cd38762c";
    };
}
