# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Object-Delayed";
    buildDepends = [  ];
    depends = [ rakuPackages."Object-Trampoline" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Object-Delayed-0.0.8.tar.gz";
        sha256 = "616d106f470abd14401e448666a82cd0e1c69aa599ffb513b46217f84636ed4a";
    };
}
