# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "OEIS";
    buildDepends = [  ];
    depends = [ rakuPackages."WWW" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TO/TOBS/Perl6/OEIS-1.0.1.tar.gz";
        sha256 = "c40060b0cccc8b6fbb1f2126ec7872223d313a087672f0b3ad79bb9908a6a600";
    };
}
