# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "OLE-Storage_Lite";
    buildDepends = [  ];
    depends = [ rakuPackages."P5localtime" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JG/JGOFF/Perl6/OLE-Storage_Lite-0.0.2.tar.gz";
        sha256 = "6105c450a99fe50b53764ddc434eb79aad27afb551db525725e2d7a3e694d503";
    };
}
