# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "OO-Actors";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jnthn/oo-actors/archive/0b5cb2ac9d077d30b10fa84c437002d458f3d06f.tar.gz";
        sha256 = "670e2b42de9e17683e2ba6eeebc3f2157183946d068ec993a84b9e3f9c2cbb35";
    };
}
