# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "OO-Monitors";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JN/JNTHN/Perl6/OO-Monitors-1.1.1.tar.gz";
        sha256 = "2146af731830e9b22791b87c90d105d405dc4bae7b0069342b56cfda5c6f7fb2";
    };
}
