# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "OO-Schema";
    buildDepends = [  ];
    depends = [ rakuPackages."CompUnit-Util" ];
    src = fetchurl {
        url = "https://github.com/LLFourn/p6-OO-Schema/archive/e5d735723452a9e257d3dfe86c198f274d14b30e.tar.gz";
        sha256 = "4b38ab2349d7f9460ca46057c8203d74f560fcc632daead3ab249faaad512240";
    };
}
