# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "OpenCV";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-opencv/archive/2e3ce4fe6c7b8a447193b96f1dc6f673b490fd8c.tar.gz";
        sha256 = "a542d2e45d7b334d860e33c5033d5c05735a8af5149ccf7933221e9cbe4fa479";
    };
}
