# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "OpenSSL";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/sergot/openssl/archive/c631d85a80273f8e072ecb799fa35708560715b5.tar.gz";
        sha256 = "794a3697d0174e22f3cb8dfcbf0e24ec4f1882430040574e8947ca7dfd953ed3";
    };
}
