# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Operator-Listcat";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AS/ASHER/Perl6/Operator-Listcat-1.0.0.tar.gz";
        sha256 = "97e36835eb3398ababd52c39bdc6069455afcd0f1cb3fecf4365d09f91776ac6";
    };
}
