# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Operator-feq";
    buildDepends = [  ];
    depends = [ rakuPackages."Text-Levenshtein-Damerau" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-operator-feq/archive/db8db5030c524819b27ad1081260ba4c4fc9fd7e.tar.gz";
        sha256 = "e4c322ae7c17ec732c8154ab8140ca9327e9bc42907c7a8eb65a2f4c1f3b4f2c";
    };
}
