# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Operator-dB";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AL/ALLSOPP/Perl6/Operator-dB-0.0.95.tar.gz";
        sha256 = "02a709266a3e3744203530ad07dc875f2388b792b2509573334d13977e7b2abf";
    };
}
