# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ORM-ActiveRecord";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" rakuPackages."JSON-Tiny" rakuPackages."Log-Async" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/G/GD/GDONALD/Perl6/ORM-ActiveRecord-0.0.9.tar.gz";
        sha256 = "e815e25e98b1770dbff1027d72ce0632eb53aa9ce8b0a4206f0ac42d2becffaa";
    };
}
