# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Overwatch";
    buildDepends = [  ];
    depends = [ rakuPackages."Shell-Command" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-overwatch/archive/265776a03930f823f2d3e4b6bd10284ef46c35e3.tar.gz";
        sha256 = "1cde7f12c79768b7c6f953dd0d6fcaca47d827d812df5bae202709aa6eb2ac9c";
    };
}
