# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Oyatul";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Oyatul-0.0.6.tar.gz";
        sha256 = "cedcffa21b5e444b7c9de08d7ef413417068a703ca953be3c9bf3de7a919eb05";
    };
}
