# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5__FILE__";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5__FILE__-0.0.3.tar.gz";
        sha256 = "77cdd97f3e1b0e97955449231471d3aa483f2e293cc60bc95a428fd17c22b196";
    };
}
