# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5__DATA__";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5__DATA__-0.0.1.tar.gz";
        sha256 = "7c1ae313804f4e4cb2865256009b22e0074461446d08a856d8c5e2ba181c2228";
    };
}
