# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5built-ins";
    buildDepends = [  ];
    depends = [ rakuPackages."P5-X" rakuPackages."P5__FILE__" rakuPackages."P5caller" rakuPackages."P5chdir" rakuPackages."P5chomp" rakuPackages."P5chr" rakuPackages."P5defined" rakuPackages."P5each" rakuPackages."P5fc" rakuPackages."P5fileno" rakuPackages."P5getgrnam" rakuPackages."P5getnetbyname" rakuPackages."P5getpriority" rakuPackages."P5getprotobyname" rakuPackages."P5getpwnam" rakuPackages."P5getservbyname" rakuPackages."P5hex" rakuPackages."P5index" rakuPackages."P5lc" rakuPackages."P5lcfirst" rakuPackages."P5length" rakuPackages."P5localtime" rakuPackages."P5math" rakuPackages."P5opendir" rakuPackages."P5pack" rakuPackages."P5print" rakuPackages."P5push" rakuPackages."P5quotemeta" rakuPackages."P5readlink" rakuPackages."P5ref" rakuPackages."P5reset" rakuPackages."P5reverse" rakuPackages."P5seek" rakuPackages."P5shift" rakuPackages."P5sleep" rakuPackages."P5study" rakuPackages."P5substr" rakuPackages."P5tie" rakuPackages."P5times" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5built-ins-0.0.22.tar.gz";
        sha256 = "93e79ea3be957083834ae9f233de2772cf28b0d70e1125af1f256aa81637623c";
    };
}
