# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5caller";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5caller-0.0.8.tar.gz";
        sha256 = "8850e2f5d91001c8585f5b76b5b5c75f910b9e4d462cf3d6f200a708258a0b2c";
    };
}
