# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5chdir";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5chdir-0.0.6.tar.gz";
        sha256 = "92bce3fc1bf8742cd86be204769929f9c0fbc4d30772b74676717bab1d67b0c7";
    };
}
