# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5chomp";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5chomp-0.0.6.tar.gz";
        sha256 = "601fc7147c4a6b43e451d3a5473cf15958785be985cba00f4edf4911588ffd08";
    };
}
