# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5each";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5each-0.0.6.tar.gz";
        sha256 = "ee847be75159a1a5da425c00a2f60852c60b43c5257589b489aef309480cb9d5";
    };
}
