# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5fc";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5fc-0.0.6.tar.gz";
        sha256 = "a9c7004a787d69db395442a6d5130833a002e637c0c5008d58c8b280f67dbe30";
    };
}
