# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5getpriority";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5getpriority-0.0.6.tar.gz";
        sha256 = "2ef0edbea5cf83041fe5bed91ef268cd4da27d82889b3cffb0329d18833784cf";
    };
}
