# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5getnetbyname";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5getnetbyname-0.0.5.tar.gz";
        sha256 = "60a4dab9296b481d63b1259ae443e94c9d69212767061aadc3f6b20d4ace9681";
    };
}
