# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5getprotobyname";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5getprotobyname-0.0.4.tar.gz";
        sha256 = "4bb83dd393395e1b62a2bef190bc835c9d79dd79cf9e044e9636cea384629da2";
    };
}
