# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5hex";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5hex-0.0.6.tar.gz";
        sha256 = "dff9051815d3bfe3175747f3f0c2f39705e32ecaf59634e6504702235d5762a1";
    };
}
