# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5index";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5index-0.0.5.tar.gz";
        sha256 = "f75ad097b42c71a1cc7e3dfd3e7e69c5788cc035f694d794b0b9969d11efdaa6";
    };
}
