# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5lcfirst";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5lcfirst-0.0.8.tar.gz";
        sha256 = "ab749110b4407cf6d48d1a7848e95aa51515e3576cd49d99ce0d58f77f87cb2d";
    };
}
