# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5lc";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5lc-0.0.7.tar.gz";
        sha256 = "82b136515bdb376f5e9b16313032a0d0230086aa8ba4ccc85090579a8521187a";
    };
}
