# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5length";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5length-0.0.5.tar.gz";
        sha256 = "f972e3646be5b19e919994e9b9a3c2df9c25aba272943f6ea511174341176365";
    };
}
