# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5opendir";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5opendir-0.0.5.tar.gz";
        sha256 = "ce2bce11353ac7ca825b7fdb0ea8542f8e95c518510e360c8df58aa881ad3fb4";
    };
}
