# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5pack";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5pack-0.0.9.tar.gz";
        sha256 = "89b2bff4938145074f8825aa716cdf2a2168e51eaf82d36254c55eda15efc841";
    };
}
