# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5push";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5push-0.0.5.tar.gz";
        sha256 = "9a4715fd07f3ea5cf70b1c54b7392ee670a19ae113192130e9125ae2696a018c";
    };
}
