# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5reset";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5reset-0.0.4.tar.gz";
        sha256 = "d548c9fc8465ab3e9ca265ab2e40e142b823d1de2ede1de38c59b6d464ed5957";
    };
}
