# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5reverse";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5reverse-0.0.6.tar.gz";
        sha256 = "c9a57e830de44d4b0149323f8e8cbd9d13c0a4df5a0f2bbe8402cd9066434041";
    };
}
