# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5seek";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5seek-0.0.3.tar.gz";
        sha256 = "a4eee913ab84934429e76294954d62f85176b4df6b46d3e713f3191107027a16";
    };
}
