# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5shift";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5shift-0.0.5.tar.gz";
        sha256 = "39039a23f4ff5db722aa1e0cdd7be1d898885674ec56f79154ed7cd2c184a143";
    };
}
