# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5sleep";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5sleep-0.0.8.tar.gz";
        sha256 = "945b10a0bb9f130f4688ea83925803a6e8046d966c9f6966992f81a5f99edd75";
    };
}
