# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5substr";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5substr-0.0.5.tar.gz";
        sha256 = "b025c4e51d2d807c480255387d9b3de32fa9485a05b9e540634563f1fe9a8f49";
    };
}
