# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P5times";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/P5times-0.0.7.tar.gz";
        sha256 = "478f637045cdcf98f4a183c103612d8324276da370eb47d50ea3ca39c43e43c7";
    };
}
