# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P6TCI";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ugexe/P6TCI/archive/67d11a7979664b114dbd690c582da511d31bc8d8.tar.gz";
        sha256 = "9484daa672641023a41daf52f254908b2e2f6a20205d877d34e5186ad91ecc0f";
    };
}
