# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "P6TK";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ALANVF/P6TK/archive/1b6ee89eb708af4844a253003710a0512240876a.tar.gz";
        sha256 = "4f55296371428f47e900a0f78cbc0dd6dbe2fe1545f7d19853c95e19537d51aa";
    };
}
