# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "panda-stub";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/stmuk/p6-panda-stub/archive/55b7779b1d440ff36871c5b90d0a6ea5ab090f54.tar.gz";
        sha256 = "bb7c91d3a70c03a09aa0dc81486c8dcee5b59fe3dc090ad0fefe2654d54b1d60";
    };
}
