# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Parser-FreeXL-Native";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/spebern/Parser-FreeXL-Native/archive/e97a6570c9f6ddffa287d6583c05960dbc47deb3.tar.gz";
        sha256 = "9f211ce79faf22201a4f96541f714f8ecd6723204aff18e68036739502882410";
    };
}
