# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Parser-FreeXL-Native";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/spebern/Parser-FreeXL-Native/archive/a0e037612cd6f3cc66c68447f390004be928073c.tar.gz";
        sha256 = "f9891c31e9ed49e9b1e9ea58762eefc6be477332edbf6b3554444a792e2c1a5f";
    };
}
