# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Path-Map";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/fjwhittle/p6-Path-Map/archive/5efa6813266a192ffbad93db76aa0204695ae6bd.tar.gz";
        sha256 = "f0ebf877e17e389cd0449be26269face52620d9bd5ce03880a6173192837c24e";
    };
}
