# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Path-Map";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/fjwhittle/p6-Path-Map/archive/81d0bd4ccff1a7763511d39d9dc46dcf495e6199.tar.gz";
        sha256 = "3c23d02929b09ffe710a714fd96047d7a270ca8865005b154a55311ea041ec31";
    };
}
