# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PathTools";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ugexe/Perl6-PathTools/archive/6a1f3633b6ce0d4d6e98c55486a7e209c8fddfdb.tar.gz";
        sha256 = "6ca7cc444781aa65c7a4677ca5f4f77d0800ac4270af74f6f1e44efb70b9474b";
    };
}
