# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Path-Through";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HY/HYTHM/Perl6/Path-Through-0.0.1.tar.gz";
        sha256 = "0a2b863ce3570c4f3c0829c313cfbc0c60f5ef9e52c9f8fd2e102852868e0fe6";
    };
}
