# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Path-Router";
    buildDepends = [  ];
    depends = [ rakuPackages."IO-String" rakuPackages."Linenoise" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/Path-Router-0.2.tar.gz";
        sha256 = "9f13792a1b7945df96c18fe55e72eca7b76bdc69be7ca91934b4303f9681e21d";
    };
}
