# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PDF-Class";
    buildDepends = [  ];
    depends = [ rakuPackages."PDF" rakuPackages."PDF-Content" rakuPackages."PDF-Grammar" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/W/WA/WARRINGD/Perl6/PDF-Class-0.3.8.tar.gz";
        sha256 = "1d563b36e11ea46f9a50a954e8ceb066a7386cefca6f3c7140d4eb850e4253c5";
    };
}
