# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PDF-Content";
    buildDepends = [  ];
    depends = [ rakuPackages."Base64-Native" rakuPackages."Color" rakuPackages."Compress-Zlib-Raw" rakuPackages."Font-AFM" rakuPackages."JSON-Fast" rakuPackages."Native-Packing" rakuPackages."PDF-Grammar" rakuPackages."PDF" ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/PDF-Content-p6/archive/f0748fd2e6bafe8a68f570a763926f5f14415e80.tar.gz";
        sha256 = "2c17bea01ce0743f704527ae87558e2d02a1b08e88ce979884112893f3cdfb20";
    };
}
