# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PDF-Lite";
    buildDepends = [  ];
    depends = [ rakuPackages."PDF" rakuPackages."PDF-Content" ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/PDF-Lite-p6/archive/a03ef461d6a460c9505a060e3eb8426571f553b9.tar.gz";
        sha256 = "f433086c9bfdd83bc9fe86fcf9069943361ca3ff4042a87beca75f5e5c95a847";
    };
}
