# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PDF-API6";
    buildDepends = [  ];
    depends = [ rakuPackages."PDF" rakuPackages."PDF-Class" rakuPackages."PDF-Content" ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/PDF-API6/archive/cdb0999dac4fc5e518157e2758397351a5a261be.tar.gz";
        sha256 = "76d01ecbeb4151aa19dc9a4c051421ca0b84b21b57eba40e56e049d35b960351";
    };
}
