# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PDF-ISO_32000";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/W/WA/WARRINGD/Perl6/PDF-ISO_32000-0.0.8.tar.gz";
        sha256 = "61237434b01bf1171da07d016fdffd291e5821dc3f732ff6801958ea4e8aee3b";
    };
}
