# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PDF";
    buildDepends = [  ];
    depends = [ rakuPackages."Compress-Zlib" rakuPackages."JSON-Fast" rakuPackages."OpenSSL" rakuPackages."PDF-Grammar" ];
    src = fetchurl {
        url = "https://github.com/p6-pdf/PDF-p6/archive/ded4a20c708fd714170bd420f81c31b0514baa56.tar.gz";
        sha256 = "f259a9e867c63b03ade95fce85c3dc54bd36a022b5e2293264b8d4b9f09dd9f1";
    };
}
