# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pekyll";
    buildDepends = [  ];
    depends = [ rakuPackages."Syndication" rakuPackages."Template6" ];
    src = fetchurl {
        url = "https://github.com/nunorc/p6-Pekyll/archive/f980516e0bbc309f3fe4c8ca30041605dbed76d2.tar.gz";
        sha256 = "3508d8e2f0e1303eb945ee2f87d9b88baa3d32dd6f6f341ffa0b8b2989cee475";
    };
}
