# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Perl6 Snowball Binding";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/sufrostico/perl6-snowball/archive/24b14d3f55e7a33ae2eb73e93d5c78b96d8031cc.tar.gz";
        sha256 = "bc03db29cd9f53c9045ef28fe5a07f73ea7e039551b6846d552c5513b0088246";
    };
}
