# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Perl6-Math-Quaternion";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Util/Perl6-Math-Quaternion/archive/3b90e593f6a428c9b8747bfa02e24087dbf2dcf2.tar.gz";
        sha256 = "d3d8a35ccebf6db3474af76a033c1f07668bc85b0b75f8a45ec77791ac098c45";
    };
}
