# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Perl6-Documentable";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" rakuPackages."JSON-Fast" rakuPackages."Log-Timeline" rakuPackages."Perl6-TypeGraph" rakuPackages."Pod-Load" rakuPackages."Pod-To-Cached" rakuPackages."Pod-To-HTML" rakuPackages."Pod-Utilities" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://github.com/perl6/Documentable/archive/41e03edb6d600e9bc23c0ca0d5fb918dd366a5bc.tar.gz";
        sha256 = "fb1e9caeffc7a56e4958d8e1032216530f507d6d9db07aff7772bb8794957ceb";
    };
}
