# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Perl6-Maven";
    buildDepends = [  ];
    depends = [ rakuPackages."Bailador" rakuPackages."JSON-Tiny" rakuPackages."LWP-Simple" ];
    src = fetchurl {
        url = "https://github.com/szabgab/Perl6-Maven/archive/1d9a6f2f7c06d4fd2f5dadba7b52b3ca03d46b2b.tar.gz";
        sha256 = "eb7d8e3b462afa4b82f03c0e652ceab2312035c11ba25eb34c2ca92398ea4832";
    };
}
