# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Perl6-Tidy";
    buildDepends = [  ];
    depends = [ rakuPackages."Perl6-Parser" rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JG/JGOFF/Perl6/Perl6-Tidy-0.0.7.tar.gz";
        sha256 = "480cbcace6b584c247af554966275318a6be113e0b1159e36f2d57c8bf21966d";
    };
}
