# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Perl6-Parser";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/drforr/perl6-Perl6-Parser/archive/d1c52d974feed8d887dbd3376f4b141e2e7f2c42.tar.gz";
        sha256 = "d46c390fbb1c6f2a89ca283b526c6f0713939d17b1d42327abaff29d1a84ce7a";
    };
}
