# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pg-Notify";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" rakuPackages."NativeHelpers-CStruct" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Pg-Notify-0.0.4.tar.gz";
        sha256 = "52db81c1484e7eb6f6ab2d9a344f4673ba8b278d4029b972c077a111d70cf608";
    };
}
