# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pluggable";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-pluggable/archive/a36f985f72ad282fd5b248bb3fac398f5739cdd1.tar.gz";
        sha256 = "43466283317467a1c279a76ad8050add124f3fb5ba16e5afb144eafe2bf6cb45";
    };
}
