# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-To-Latex";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/kalkin/Pod-To-Latex/archive/c123d38159e5871c5fd18f7775b8a48da5447de5.tar.gz";
        sha256 = "8b5c2cba99ff359cef396917834e3715948bfb03aada3ea41ac1fafa1d801e65";
    };
}
