# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-To-HTML-Section";
    buildDepends = [  ];
    depends = [ rakuPackages."HTML-Escape" rakuPackages."Pod-To-Anything" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Pod-To-HTML-Section-0.1.0.tar.gz";
        sha256 = "9d93ffd1acc5ec152d2d0d4e06d40c4e8e742171c248af8eae0f195193994b5a";
    };
}
