# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-Utilities";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/antoniogamiz/Pod-Utilities/archive/da709241fcd7a41759d3b07b51c2549be603ae48.tar.gz";
        sha256 = "504670c7252ffd243642bc9848d23fae1580cda4745f6a8a963da3c7b401614b";
    };
}
