# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-To-Cached";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Directory-Tree" rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/finanalyst/pod-cached/archive/4693592a8c6f75db7c29f13b2ed8b249b697e7e9.tar.gz";
        sha256 = "e7e132c12f21392db420015d727705e6ac4778b8c0593d569a6e4dd3c6a4e3c2";
    };
}
