# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-To-Cached";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Fast" ];
    src = fetchurl {
        url = "https://github.com/perl6/Pod-To-Cached/archive/c155d4e7ac01a34c7ed44216cd5fb58716a413e7.tar.gz";
        sha256 = "296a8004a77171811d63a6f46a20952fcc6b69887861052522dd95941641a7dc";
    };
}
