# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-Coverage";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" ];
    src = fetchurl {
        url = "https://github.com/teodozjan/pod6-coverage/archive/7ca45186a21162db231f66920f5e2eeef8faef71.tar.gz";
        sha256 = "3c39b7001616dcccdf2900c79781d3cfda2de8eef179519522ff472a9e3ab332";
    };
}
