# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-To-Pager";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Pod-To-Pager-0.2.0.tar.gz";
        sha256 = "f7737395cafc8f42830769c4cfdfbf53bb810604062f8373489e65acf87c412a";
    };
}
