# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-EOD";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/hoelzro/p6-pod-eod/archive/a025f3672ef3b08ec6bb33592781a6807c7e6037.tar.gz";
        sha256 = "b8d817aa06e002146bdd719eb64a18d1e3d80cd9ec887892d3aa34208314e335";
    };
}
