# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-Render";
    buildDepends = [  ];
    depends = [ rakuPackages."Pod-To-HTML" rakuPackages."Pod-To-Markdown" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/pod-render-0.8.0.tar.gz";
        sha256 = "b5bdd3d388762478fb223b79ad12530b847ed67e93e4e73d1fbb100da864e488";
    };
}
