# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-TreeWalker";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/autarch/perl6-Pod-TreeWalker/archive/507f3c7ec6c6565cdc61ce1bdb05b190f0ba5f8a.tar.gz";
        sha256 = "a1081a544a72c791ce8124a7ced7d763cd656409358a012e32f15d5008fdac31";
    };
}
