# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-To-BigPage";
    buildDepends = [  ];
    depends = [ rakuPackages."LWP-Simple" ];
    src = fetchurl {
        url = "https://github.com/perl6/perl6-pod-to-bigpage/archive/92f2e4ef9f20a5031a5f033dc876e72f9d544553.tar.gz";
        sha256 = "9b236c7f50f704729d98f39c7313212ae8e71e3ccef1e6f1afeba1365c32dfd4";
    };
}
