# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pod-PerlTricks";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" rakuPackages."Pod-Perl5" ];
    src = fetchurl {
        url = "https://github.com/dnmfarrell/Pod-PerlTricks/archive/993c72264a32df55f982683a758d80485a2b2134.tar.gz";
        sha256 = "763ed698530e61180aa2cae3d38220d67ad59b8b79984a2f6f1005e28010a7d0";
    };
}
