# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PodCache-Module";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Directory-Tree" rakuPackages."JSON-Fast" rakuPackages."LibCurl-Easy" rakuPackages."Pod-To-Cached" rakuPackages."Template-Mustache" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://github.com/finanalyst/pod-render/archive/02c49579afd206f85eb59113b30fc5344ff421f1.tar.gz";
        sha256 = "c3cbe9faeb1920b2b88bc9be5d67721dd65e8769d77551433eda0fb8c3d514f7";
    };
}
