# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "POSIX-getaddrinfo";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ML/MLDEVINE/Perl6/POSIX-getaddrinfo-0.1.2.tar.gz";
        sha256 = "30fc4ca05f85ce0e3a749b9cbc8e9bdf0086ea9fa423b5568af709b6bd6c1c11";
    };
}
