# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Powerline-Prompt";
    buildDepends = [  ];
    depends = [ rakuPackages."Git-Simple" ];
    src = fetchurl {
        url = "https://github.com/7ojo/perl6-powerline-prompt/archive/69ac4078d0d17fe9091683a70d0da111fd710d4d.tar.gz";
        sha256 = "6ce9fb1a6446aabce4be0b07a44f2ea8d8001aa62bdc2bab12ad3d97f266e2af";
    };
}
