# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "PowerNap";
    buildDepends = [  ];
    depends = [ rakuPackages."Serialise-Map" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SA/SAMGWISE/Perl6/PowerNap-0.0.2.tar.gz";
        sha256 = "aafc7daf7332d46a1f8a4bff5b40644859124a4340ab09be756daeaa27e2e0b8";
    };
}
