# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pretty-Table";
    buildDepends = [  ];
    depends = [ rakuPackages."Text-Wrap" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/U/UZ/UZLUISF/Perl6/Pretty-Table-0.0.2.tar.gz";
        sha256 = "682a4f5d0e58f273383be9d90dcf9d7d3111c013830b692c9e284784d9c4606e";
    };
}
