# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Prime-Factor";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Prime-Factor/archive/791723842e8462e47e633e4066f55505522db5f3.tar.gz";
        sha256 = "f284b321fcaa79013d3c1fe0c9a3848263893b4145fe6772c46bb15a93f18097";
    };
}
