# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Prime-Factor";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Prime-Factor/archive/230d394f8115186acdcd406e737a7f79602f9f70.tar.gz";
        sha256 = "689fd6fd222d3376d2d9effa96f9e50f3d0d5bedc06fd73d450da9c6ad2ce011";
    };
}
