# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Printer-ESCPOS";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/shantanubhadoria/p6-Printer-ESCPOS/archive/3d377f9d5e8d1b0d6067b75804b3b7d6163d8dbd.tar.gz";
        sha256 = "3fb05d85a4a552cd79f9c75a41e078be9319a0fa51bdb4dc39405a9868d46fbd";
    };
}
