# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ProblemSolver";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FCO/ProblemSolver/archive/1ae3b15757af8ec46b1af30efaf713fa559314ed.tar.gz";
        sha256 = "d724f4156811b73b5257135798779d38035a5fbe63c68d8af38cf15af4bb7333";
    };
}
