# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ProcStats";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/L/LE/LEMBARK/Perl6/ProcStats-0.3.0.tar.gz";
        sha256 = "2e521eaeec1d7b1e9e0904cf9676a7f9103bf1cbe2dad083fbd7c68f72f0b6a6";
    };
}
