# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Proc-Async-Timeout";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/gfldex/perl6-proc-async-timeout/archive/7d1b03199a12ee74f0af159ddb5ed5807d7fe83b.tar.gz";
        sha256 = "22cc54e24bf2396f940b5bf1f6a91be45c376f2525f6c8603ae5beb4ffa4abe1";
    };
}
