# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Proc-Q";
    buildDepends = [  ];
    depends = [ rakuPackages."RakudoPrereq" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Proc-Q/archive/de5e3f84fa01e9ca11f6fbc2696f1053b7c7999a.tar.gz";
        sha256 = "41c951e838210435bbc3c1fdb4d7cbd77be99c36679efff66729b33f8fe0c612";
    };
}
