# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Proc-More";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TB/TBROWDER/Perl6/Proc-More-Perl6-0.3.0.tar.gz";
        sha256 = "15e1b818e57bb1cba0304efa2fdf7ec74d20e0c5515f9f2ed0b51212674fce6e";
    };
}
