# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Proc-Feed";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/kjkuan/Proc-Feed/archive/0e334065d74d76265c07d21e5f726d19a02538ce.tar.gz";
        sha256 = "03297c4291b5b25ee44ee2ea99250ee5454600f5273ffb4ed00e32e2c5e902d4";
    };
}
