# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Prompt-Gruff";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/adaptiveoptics/P6-Prompt-Gruff/archive/f4ead814f04dc15d00ac8d56a3dfa6b0b5841303.tar.gz";
        sha256 = "909411b76dd77519f9f8859be8db67f9f688453ac94885962e0293dea6226e60";
    };
}
