# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Propius";
    buildDepends = [  ];
    depends = [ rakuPackages."OO-Monitors" rakuPackages."TimeUnit" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/A/AT/ATROXAPER/Perl6/Propius-0.1.1.tar.gz";
        sha256 = "7dd2967da35293d170e766d9627c0461605f9157543335263d9762d0161c2ac8";
    };
}
