# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Proxee";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Proxee/archive/4c39fe1ae91b9ef1cf59097e21fb8f3ddfd5527a.tar.gz";
        sha256 = "6f200783a450ab7911d3fec7fa5148398859e9eee9e5dd74f8e56cb566339e73";
    };
}
