# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Punnable";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FCO/Punnable/archive/09f6c8efb0aa71c795edcb7b590ded9ade27f3af.tar.gz";
        sha256 = "20a704ed30a2db4518510c7b8b7e407be4a3e856f6fb3e1fa2a95ac32ab49509";
    };
}
