# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "python-itertools";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ahalbert/perl6-itertools/archive/f46f6626a617888f0edd94ed5e292b3d2f54735e.tar.gz";
        sha256 = "e0b963eae19a19b16908a5f605691d2dbcddc211c9f1a4cea46fa34d181ebdf7";
    };
}
