# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Pythonic-Str";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Pythonic-Str/archive/43255f1043ec899b32351f6d3d88af60ad743e46.tar.gz";
        sha256 = "b89f0a5134094d64066e7d83519107080441e24fc162572db648545c1ab899b7";
    };
}
