# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "QM";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-Table" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/U/UZ/UZLUISF/Perl6/QM-0.0.2.tar.gz";
        sha256 = "1b2f7c58b71f3b7dc67b696eb65ee3626491bbc36203d5201083fb8089e9ce54";
    };
}
