# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Questhub";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-UserAgent" rakuPackages."IO-Socket-SSL" rakuPackages."JSON-Tiny" rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://github.com/perlpilot/p6-Questhub/archive/a1de76e6af34ce2153fef3fb245d3a1187ad68e6.tar.gz";
        sha256 = "dd40db489679ef5c2ba17c6e71c25886a49ff275713329ab85e760331c81c720";
    };
}
