# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Rakudo-Slippy-Semilist";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/gfldex/perl6-rakudo-slippy-semilists/archive/3cfd2989acdbd61297c5ba20c14e069bc3f9f095.tar.gz";
        sha256 = "45681b7366a6250d71d17d7b833e45382a00e91ddb3d154260f164d4d7dd6b37";
    };
}
