# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Rakudo-Perl6-Tracer";
    buildDepends = [  ];
    depends = [ rakuPackages."Rakudo-Perl6-Parsing" ];
    src = fetchurl {
        url = "https://github.com/jaffa4/perl6tracer/archive/6b324fba11a939149000b29467d75544c851e32d.tar.gz";
        sha256 = "6d3989ad37214f911f4d5aa73e3ee7dc128ad533601ba69e9890fea1340c8e7e";
    };
}
