# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Ranker";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/U/UZ/UZLUISF/Perl6/Ranker-0.0.3.tar.gz";
        sha256 = "6276ff9cf699aff21b14d1b019cc5d333b61abc0fcccd4cf5044fd5f6fa79909";
    };
}
