# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Rat-Precise";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Rat-Precise/archive/a996a482ba20124e428fb31fba7abc619398e9a5.tar.gz";
        sha256 = "76896166f5a3fd9967574bee09bfb9596f1cc04bd4895d1c0ff928026738482f";
    };
}
