# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Red";
    buildDepends = [  ];
    depends = [ rakuPackages."DB-Pg" rakuPackages."DBIish" rakuPackages."UUID" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/F/FC/FCO/Perl6/Red-0.1.5.tar.gz";
        sha256 = "abea288deb4bc28d08b0266a542f084da802a2cabb598cbe6a43be23fdab129e";
    };
}
