# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Redis-Async";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/CurtTilmes/perl6-eredis/archive/a71ccd22d8603e6a0a0c9b829cc10b1447f040b2.tar.gz";
        sha256 = "571c67b08aa03ff9957cf5d5cf7ef12fd7bb211aeb60635cc3d111a94c4fbad0";
    };
}
