# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Regex-FuzzyToken";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/alabamenhu/RegexFuzzyToken/archive/8557061220bababf6f1e1470845f8b5d1bec8946.tar.gz";
        sha256 = "a3c5f5447e7fa48001b245747747d14b82b844b54d27333d955431bf23dd1532";
    };
}
