# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Router-Boost";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/moznion/p6-Router-Boost/archive/902a28dfef437e7e776dae79da2c00baea045827.tar.gz";
        sha256 = "2d2096853c42077220282a4dd3c06294f4762e27de8cae08ce79fdcd99037a33";
    };
}
