# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "RPG-Base";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/japhb/RPG-Base/archive/60b45ba0492a8a7acfd4a2668ab5bd6700a650f5.tar.gz";
        sha256 = "0d9ee7f7cd3920b9367c2df222c0d800818abbc251acde5b8dfcf5ee75571c26";
    };
}
