# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "RPi-Device-ST7036";
    buildDepends = [  ];
    depends = [ rakuPackages."RPi-Wiring-Pi" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/P/PA/PATRICKZ/Perl6/RPi-Device-ST7036-0.0.3.tar.gz";
        sha256 = "4fac71496d3e5ce2a1c97c6f2fef9f17542f68f8d0a74826cc4726c7ad8c0ee4";
    };
}
