# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sanity";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ugexe/Raku-sanity/archive/6557e213b196c8c7bdc800e731a872a6168f25b3.tar.gz";
        sha256 = "4ee6cd72d9b4f54aa03b59a8dd038721de245f1f9c306a6ba9c19c041c6f4906";
    };
}
