# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SAT-Solver-MiniSAT";
    buildDepends = [  ];
    depends = [ rakuPackages."SAT" ];
    src = fetchurl {
        url = "https://github.com/taboege/raku-SAT-Solver-MiniSAT/archive/800c3de84f99076d915bebac2b52c09dcc88a855.tar.gz";
        sha256 = "d4a2dbd02ea5091f2b063111e5c9ba3105741a2fe59af97ff134f4d590b6af43";
    };
}
