# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Scalar-Util";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Scalar-Util-0.0.8.tar.gz";
        sha256 = "8ec09c7ed6687b51e63da289b0fd0c9453d28f734421955b6881daca362b0bc7";
    };
}
