# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ScaleVec";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" rakuPackages."Result" rakuPackages."Serialise-Map" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SA/SAMGWISE/Perl6/ScaleVec-0.0.6.tar.gz";
        sha256 = "aedc80938c50132357d42ff38d1acd43eae6118348e03b08bca95ea4e1ecf496";
    };
}
