# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Scalar-Util";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Scalar-Util-0.0.6.tar.gz";
        sha256 = "8dbb3197369e71e1e3129d451e1b530b19f6b06785526f4bfa94aed885bea167";
    };
}
