# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ScaleVec";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" rakuPackages."Result" rakuPackages."Serialise-Map" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SA/SAMGWISE/Perl6/ScaleVec-0.0.5.tar.gz";
        sha256 = "80ec707fc408351778593c2a9948c892b855032e47146ea56141a1808c524efe";
    };
}
