# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Scientist";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/lancew/ScientistP6/archive/a29cb982b9fa6bed087b2501202a19d476dcc019.tar.gz";
        sha256 = "02124c17958a602706171c81e36e6fd38e81b6abef216b86bae9c7918a58412c";
    };
}
