# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SDL2-Raw";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TI/TIMOTIMO/Perl6/SDL2-Raw-0.3.tar.gz";
        sha256 = "2adf2994762fddbb1ec33dc9d5d0ce194b1a1d7f3722e27ce2de9929fefe51f2";
    };
}
