# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Selenium-WebDriver";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" rakuPackages."File-Which" rakuPackages."File-Zip" rakuPackages."HTTP-UserAgent" rakuPackages."JSON-Tiny" rakuPackages."MIME-Base64" rakuPackages."URI-Encode" ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-selenium-webdriver/archive/5e3ff320d2f392e44df1433f0544201c154f2590.tar.gz";
        sha256 = "2d1778383ea078579b13e7065d2bfa39129c541846c7dd3b54bfe38a239134e7";
    };
}
