# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Semantic-Versioning";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/sirrobert/Semantic-Versioning/archive/dc388f6ce42e7d8dd90003d6510f3b1e243986ee.tar.gz";
        sha256 = "7d7e9614ff0913f08e13c7c0c8593b1ee5c91dbe106c83113cc44822df812e4d";
    };
}
