# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SeqSplitter";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FCO/SeqSplitter/archive/167b5bfcd99a8328c41ac56a667ba250bfe39f38.tar.gz";
        sha256 = "4ac1e56968b744f5df893afeaa07f2ae8a3498fef3f2e254b86a0cd2420e4bf8";
    };
}
