# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Serialize-Naive";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ppentchev/Serialize-Naive/archive/fca9492db4558809fd8fce5c733388220f17997f.tar.gz";
        sha256 = "4330b4a4bd82dddf45a6e14c347899e4a3b9a37751b9aebcc964d26374ad8c83";
    };
}
