# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Shell-Capture";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ppentchev/Shell-Capture/archive/3df2176008823605a94dd36f89384aaf86691d14.tar.gz";
        sha256 = "96a18e05161dab7fab7824846aa655804b72bd734235b74411cb47076d244457";
    };
}
