# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slang-Predicate";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SA/SAMGWISE/Perl6/Slang-Predicate-0.0.1.tar.gz";
        sha256 = "df8f7b0bef9bb6c1e2086b66bfa440f255d1b8762bae2f8ee976eaea7342ac00";
    };
}
