# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slang-Roman";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/drforr/perl6-slang-roman/archive/7c2a929e0d3b50b0eafd5320d0f4fcf122add4c8.tar.gz";
        sha256 = "9372b7caffb6aed0437ed85b5a3ac7981658d1bfb721eb556e41c99956555d13";
    };
}
