# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slang-Tuxic";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/FROGGS/p6-Slang-Tuxic/archive/888a4a229a40d9b35b9fb4ccb8d05c1c63c0a18a.tar.gz";
        sha256 = "550aeed1d5aa5c77748ba35619f5767355b06d253504efa2a0197a99ce21bcbc";
    };
}
