# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slang-Subscripts";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Slang-Subscripts-0.0.2.tar.gz";
        sha256 = "e2b82935e570b43f9ef5e29c368dafd0473ba5b38ba2690839c5e9bb71e3d5b1";
    };
}
