# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slang-Mosdef";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/bduggan/mosdef/archive/8d9867f23ec7a354083fbf9a36482ff0e4809c01.tar.gz";
        sha256 = "a4b20619c701659793503115c548210ea7dec290321d1053bb8eea2bee65ac0d";
    };
}
