# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slang-SQL";
    buildDepends = [  ];
    depends = [ rakuPackages."DBIish" ];
    src = fetchurl {
        url = "https://github.com/tony-o/perl6-slang-sql/archive/1bc802e4d1e3765e99f82ca9cee933e10278c669.tar.gz";
        sha256 = "c9cea7d183d506cf56e4787c19607417539b7fc3f619bbeff86e84530abb3169";
    };
}
