# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slang-AltTernary";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/mryan/perl6-Slang-AltTernary/archive/b20b47682b5838b0e6b7e01fecad4002ec7f96da.tar.gz";
        sha256 = "2385b92c3528fe7a8571fd40d8bfb578783944d7efabfc3dcedc448b22a579d7";
    };
}
