# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Slippy-Semilist";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/gfldex/perl6-slippy-semilist/archive/4555ed811bcef309544f7f85161ab98893725924.tar.gz";
        sha256 = "c6177aa83f6d43254e1fdb385576e76ee1e3a7a13199c1c6a9acbff9c7bd0f77";
    };
}
