# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Smack";
    buildDepends = [  ];
    depends = [ rakuPackages."Apache-LogFormat-Compiler" rakuPackages."DateTime-Format" rakuPackages."Digest-MD5" rakuPackages."HTTP-Easy" rakuPackages."HTTP-Headers" rakuPackages."HTTP-Status" rakuPackages."HTTP-Supply" rakuPackages."HTTP-UserAgent" rakuPackages."Hash-MultiValue" rakuPackages."IO-Socket-Async-SSL" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HA/HANENKAMP/Perl6/Smack-0.5.1.tar.gz";
        sha256 = "cd05a941de72ac6c078288697a06ad50f7ec7799c02c424ee34dd7362f0e342e";
    };
}
