# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Smooth-Numbers";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/smooth-numbers/archive/725c05b17ba9efba901f0b0b4c0ffa6a116081d8.tar.gz";
        sha256 = "412cd98087243c323b2c25614124569d9f72d09df6b84d899a80546ff51e19a8";
    };
}
