# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sort-Naturally";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Sort-Naturally/archive/4c80abd905a8c8ef5631fd0d82c946b6a631d18e.tar.gz";
        sha256 = "0ca1c1cc49e7783b9f5ada4385828b3a6531655c354fca4d1595b3679b68b42f";
    };
}
