# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparky-Plugin-Notify-Email";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparky" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Sparky-Plugin-Notify-Email-0.0.1.tar.gz";
        sha256 = "95310b4a449fdc50e0fcac40276a09b82883081517862ba46f4da0985aa2602c";
    };
}
