# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrowdo-Azure-Web-Cert";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparrow6" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Sparrowdo-Azure-Web-Cert-0.0.4.tar.gz";
        sha256 = "9c9f1d5d4829f48004a46609981047ad92b5abb44043b8299df4f419b1e70555";
    };
}
