# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrowdo-Cpm";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparrowdo" ];
    src = fetchurl {
        url = "https://github.com/melezhik/sparrowdo-cpm/archive/8cd6a63858796149b491d7a72dc286d9e9c8161b.tar.gz";
        sha256 = "0d6a7d8ec91cb1f6d1e7a4a842b3bd0e35db7a8e58874b201abab978bc8709f6";
    };
}
