# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparky-Plugin-Hello";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparky" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Sparky-Plugin-Hello-0.0.2.tar.gz";
        sha256 = "b7b9ebb6b5135041ab9d718bf7417b142dea91cf7727db4b28c8cd07509b0029";
    };
}
