# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrowdo-Archive";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparrowdo" ];
    src = fetchurl {
        url = "https://github.com/melezhik/sparrowdo-archive/archive/b8322a491c23aa193b8b1d37678b0ffc4ce428dd.tar.gz";
        sha256 = "c014ce37d6a71f4a3b1a46e7578318a60c5e6ae8e8cc527098a0b10e0c522987";
    };
}
