# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrowdo-Ruby-Bundler";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparrowdo" ];
    src = fetchurl {
        url = "https://github.com/melezhik/sparrowdo-ruby-bundler/archive/49c824619a1a7982bdc8172fa6636d4d9e26f911.tar.gz";
        sha256 = "ba4d0c7801377ea4021c48cb35b6800e63c6d7684b23b3779ebfef988fe0b6ec";
    };
}
