# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparky-Plugin-Notify-Telegram";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparky" rakuPackages."TelegramBot" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SP/SPIGELL/Perl6/Sparky-Plugin-Notify-Telegram-0.0.2.tar.gz";
        sha256 = "e36c40055480577fa1109a4236937ab8ad382db2a6c57c263337af2c39a6e03d";
    };
}
