# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrow6";
    buildDepends = [  ];
    depends = [ rakuPackages."Data-Dump" rakuPackages."File-Directory-Tree" rakuPackages."Hash-Merge" rakuPackages."JSON-Tiny" rakuPackages."YAMLish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Sparrow6-0.0.19.tar.gz";
        sha256 = "cee21091bd100753486358f35a53b8c443f662d42b567ffe391293e1c04fb634";
    };
}
