# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrowdo-VSTS-YAML-Build";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparrowdo" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Sparrowdo-VSTS-YAML-Build-0.0.7.tar.gz";
        sha256 = "e675585818fd230bc26cd9a12b442ebf10e9d624bca95aa6cf5b8c2f7f724df1";
    };
}
