# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrowdo-Rvm";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparrow6" rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Sparrowdo-Rvm-0.0.2.tar.gz";
        sha256 = "c74554b77ffe1f9cd81db9baa4b08eef117bad54fdd820bea59d832470a6e601";
    };
}
