# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sparrowdo-VSTS-YAML-Angular-Build";
    buildDepends = [  ];
    depends = [ rakuPackages."Sparrowdo" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Sparrowdo-VSTS-YAML-Angular-Build-0.0.6.tar.gz";
        sha256 = "58b5fc83ed038124893566dc1af187e295607a158613988e1e0461b0bfadf2f8";
    };
}
