# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Spit";
    buildDepends = [  ];
    depends = [ rakuPackages."DispatchMap" rakuPackages."JSON-Tiny" ];
    src = fetchurl {
        url = "https://github.com/spitsh/spitsh/archive/3f306f9a3bcc6ae3876887a4453c8f9cba35e95e.tar.gz";
        sha256 = "0cd2eab9fd8ebcc3b8dfdfada94a15eaa22cf1fe547e9022848edcab351c86a9";
    };
}
