# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Spit";
    buildDepends = [  ];
    depends = [ rakuPackages."DispatchMap" rakuPackages."JSON-Tiny" ];
    src = fetchurl {
        url = "https://github.com/spitsh/spitsh/archive/11b5f00757cb85320ab777cd3551ad0412c1db86.tar.gz";
        sha256 = "162aa63ebf0f53d551003409224a95ec0bbd5469ff0f6b8648ba0c2c1a4d42fa";
    };
}
