# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SQL-Lexer";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/D/DM/DMAESTRO/Perl6/SQL-Lexer-0.2.2.tar.gz";
        sha256 = "9606535b4ef325d2b413bc54c9628fc5a7e89747e7ed7f7eec247de96b8407ea";
    };
}
