# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SSH-LibSSH";
    buildDepends = [  ];
    depends = [ rakuPackages."Concurrent-Progress" ];
    src = fetchurl {
        url = "https://github.com/jnthn/p6-ssh-libssh/archive/b8be2b5e02ca3d5fbbfccae584ad345f90bd6bf1.tar.gz";
        sha256 = "108fd81b576172726a8949cf2f7de4d1fdac632d73e1a8c85a454cfe7dd7c225";
    };
}
