# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SSL";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/grondilu/openssl/archive/25e328186cd7d04e4661a382d0b6d3ca5cbab328.tar.gz";
        sha256 = "c1d9edac881f3457e6a9dcd59c690a7de0ab973153a8fabb50100f80621cf110";
    };
}
