# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SSL";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/grondilu/openssl/archive/6f523e717164f99ef913f429c799074ad947ee43.tar.gz";
        sha256 = "92e0f7e914e84cd69ee7cf87159404a16b456f98b8d299b152e300d9784ed7a4";
    };
}
