# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Staticish";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Staticish-0.0.7.tar.gz";
        sha256 = "a8c45727635370d93035d2919e4dc648588ee0501b7d46cd98fa7634ca4ea5d6";
    };
}
