# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Stream-Buffered";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" rakuPackages."IO-Blob" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MO/MOZNION/Perl6/Stream-Buffered-0.0.1.tar.gz";
        sha256 = "c278dbdbbe5283220f3e8f30ed9c60abad94744bb9459b1efa82510a1b643170";
    };
}
