# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "StrictClass";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ufobat/p6-StrictClass/archive/a411f4cec5b53a69d2278654054f1e24d9ff30a5.tar.gz";
        sha256 = "27df37b7dd8c27b8dc89059c049e9217534e0cdb8e46f8eca9b3a47cca284fac";
    };
}
