# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "String-Fields";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/String-Fields-0.0.5.tar.gz";
        sha256 = "ccb10d6d67aedc3cf05a9f2dd8bb558c78efa3a901e6dd44ff874843b63c6cf3";
    };
}
