# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "StrictClass";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/U/UF/UFOBAT/Perl6/StrictClass-0.0.3.tar.gz";
        sha256 = "e5fc624c37adf87128bdc3c9089155fbd1d7d941ddd357bc6227c358c476e57d";
    };
}
