# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "String-Stream";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/jaffa4/string-stream/archive/2cd5ba19b1c08eb8324aed1710b16b403936cf09.tar.gz";
        sha256 = "dd2bd39afd38eb8f414f486d84d2eacd4d6a8796ced0d110d38fa2f08fc5a7b7";
    };
}
