# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "String-Splice";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/String-Splice/archive/21ac2bfc0a28e85b8f532d03539a10cf6c6e1abd.tar.gz";
        sha256 = "9487adb7079c136403fdf0c7ee6b155231305c98280b1f9e928050613bbcdfe5";
    };
}
