# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "String-Fold";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/String-Fold-0.2.0.tar.gz";
        sha256 = "b389710bad5b78000cc50950c32de607a79025dac67f0d31af25b5a3e52258f9";
    };
}
