# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "String-FuzzyIndex";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/threadless-screw/String-FuzzyIndex/archive/f007c560d4ba411434050d042030a5e80717ed00.tar.gz";
        sha256 = "9a76c13a3a84fe688e46606fcd87c117b132a97e4c1bd447be52bb3ddf254b53";
    };
}
