# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "StrictNamedArguments";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/nxadm/StrictNamedArguments/archive/6a3a0e4275865e0d9051785d41f8a2156088d593.tar.gz";
        sha256 = "a5104013b4b1d6625a9b18768c10da73719f0c5a880151f99ecb7db3db778d3f";
    };
}
