# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sub-Util";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Sub-Util-0.0.4.tar.gz";
        sha256 = "1ce88adc9ed9c8b715552db9005167a157b76e640dc20af84055f42d1bd2fc73";
    };
}
