# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Subsets-Common";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/bradclawsie/Subsets-Common/archive/26072976461eb2a1e9273103d046f86571636cea.tar.gz";
        sha256 = "5735584be57cfb446d0283379fef54fac8a3dba91e0f63094615d2d1207aec63";
    };
}
