# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "subs";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/subs-0.0.2.tar.gz";
        sha256 = "715c15cc95b633ac589549d34c7b8b532658fa801a70f5e33f2da3763aa441b3";
    };
}
