# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Supply-Folds";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Supply-Folds-0.0.1.tar.gz";
        sha256 = "a85c88b8d67fe7bcf362b05dd06372f8f0ec0d70519a70c705b76d97d2606dc8";
    };
}
