# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Supply-Timeout";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/C/CO/CONO/Perl6/Supply-Timeout-0.0.2.tar.gz";
        sha256 = "25e8ef18e86d2be6ad4cede5562b96c21d53033fc3c8c26119e803f36e356ee2";
    };
}
