# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sustenance";
    buildDepends = [  ];
    depends = [ rakuPackages."Config-TOML" ];
    src = fetchurl {
        url = "https://github.com/atweiden/sustenance/archive/08512d8816f973ab4d60da3798e11c84f6f6f7d5.tar.gz";
        sha256 = "c7df8c505302cbb2b6c810b5b0e714a87d971ecf3c4f64f474081df6d9f8200b";
    };
}
