# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "SVG-Plot";
    buildDepends = [  ];
    depends = [ rakuPackages."SVG" ];
    src = fetchurl {
        url = "https://github.com/moritz/svg-plot/archive/062570a78fd38c3c6baba29dfe2fbb8ca014f4de.tar.gz";
        sha256 = "61dd08de6406dccd3e4d969ee9df273cc202afbbff568ad2e0f9a4d8afc8561b";
    };
}
