# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Syndication";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/p6-syndication/archive/0b5bf35fac1fc3ad166a00ad0b4afcfcdb1131d0.tar.gz";
        sha256 = "98efbf4e0f6ad529297fd90e4887e50ec3bd6634eb4fd2798e0ba7e40512d370";
    };
}
