# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sys-HostAddr";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP-Client" rakuPackages."Net-Netmask" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMASLAK/Perl6/Sys-HostAddr-0.1.2.tar.gz";
        sha256 = "f2d455edffa8a6d60aaab671af7d334d35791d1cf5f3318456b5882783aafa6a";
    };
}
