# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sys-IP";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Demayl/raku-Sys-IP/archive/ee6021e33ad3624871a17004cedd22e5b94371f4.tar.gz";
        sha256 = "d67942f29358e4a12420c32a70d265e721bb0e6d15a7045db2e026b13e0c8569";
    };
}
