# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Sys-Lastlog";
    buildDepends = [  ];
    depends = [ rakuPackages."System-Passwd" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Sys-Lastlog-0.0.12.tar.gz";
        sha256 = "bd6ee1ec64a93c253f35d45c63e266762033ed95511ec6ed7cf071281a23def1";
    };
}
