# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "System-Passwd";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/raku-community-modules/System-Passwd/archive/76ffef783752b2f4c26d8c2f5dd9a4ec3c05eaad.tar.gz";
        sha256 = "e397528989827bc4f9f072f05ec18e57e9e4d62f80a225b0f21cdb7ebedef33f";
    };
}
