# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "System-Passwd";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perl6-community-modules/System-Passwd/archive/a50c336a3c02aa98163c72bec025ec4c659ced9b.tar.gz";
        sha256 = "30f0c478345431c244fbb2fdaebb29fa1c486eeebf75390045d54c2df04c3be8";
    };
}
