# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "System-Query";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tony-o/p6-warthog/archive/f06ffee092a546dec9647a23318b4611de5a4adb.tar.gz";
        sha256 = "eb51ce2c8527bf118d178cb3c663eefbb65e18222650237e5a222851a274ebec";
    };
}
