# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "System-DiskAndUpdatesAlerts";
    buildDepends = [  ];
    depends = [ rakuPackages."FileSystem-Capacity" rakuPackages."Package-Updates" ];
    src = fetchurl {
        url = "https://github.com/ramiroencinas/perl6-System-DiskAndUpdatesAlerts/archive/06b38a3e7d63a2f62b1d1374cce7b5cfcc7b315d.tar.gz";
        sha256 = "93655df5b249db6867ba374b50185152885ffe9989265f3b791d5dedd3b26ab5";
    };
}
