# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "TCC";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/CurtTilmes/perl6-tcc/archive/17fd731044842810c54c55517033acf7d2dce8ae.tar.gz";
        sha256 = "2e59448baedff428e5a5f88879bb9e29c320798fde235185137ea70501247222";
    };
}
