# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "TCP-LowLevel";
    buildDepends = [  ];
    depends = [ rakuPackages."NativeHelpers-Blob" rakuPackages."StrictClass" rakuPackages."if" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMASLAK/Perl6/TCP-LowLevel-0.0.4.tar.gz";
        sha256 = "531e4b61bc1c490ac98ade8f5cf2ba00a4c7516513ac8e062813d63192556381";
    };
}
