# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Telegram";
    buildDepends = [  ];
    depends = [ rakuPackages."Cro-HTTP-Client" ];
    src = fetchurl {
        url = "https://github.com/ijneb/telegram-bot/archive/e6888303bca85b1ed1a9cc2f13208dac5a2834fc.tar.gz";
        sha256 = "0a69bfe1137ab05932902fdef96da6855fa65ebc2f840b8819f408de7d666af8";
    };
}
