# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Template6";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/supernovus/template6/archive/b49623478a221840875850e5382bebed8a2b643a.tar.gz";
        sha256 = "90d3af6cf09d7a8e33820b4bebc10045308aed4df8f1d2bc5eb53c84886c4829";
    };
}
