# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Temp-Path";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest-SHA" rakuPackages."File-Directory-Tree" ];
    src = fetchurl {
        url = "https://github.com/ufobat/perl6-Temp-Path/archive/5a6acee907d65fc5b681a6ea022aa18217f6e99b.tar.gz";
        sha256 = "900b1433e3d6fd9a798de0cdc74cb18dabf01d0fed533728feafb2ea402ee2bd";
    };
}
