# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Term-Choose-Util";
    buildDepends = [  ];
    depends = [ rakuPackages."Term-Choose" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KU/KUERBIS/Perl6/Term-Choose-Util-p6-1.3.4.tar.gz";
        sha256 = "d9f51270178d1438a9f58f0876e8f49a124f1a407d7d7a977be32c9165962333";
    };
}
