# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Terminal-Print";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Which" rakuPackages."OO-Monitors" rakuPackages."Term-termios" rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://github.com/ab5tract/Terminal-Print/archive/8f6278ebdeab3ea929484bc9ca5524beb33dcfd7.tar.gz";
        sha256 = "3e77b11af56bc58a00c584c0b8f01c1fb46c22243a743bac466feb028d208ab8";
    };
}
