# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Terminal-ANSIColor";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tadzik/Terminal-ANSIColor/archive/eeb2dadd2cc2b7df34588be7869768213fd9fff4.tar.gz";
        sha256 = "fc07868d1c0dc9220a771486c08d562fea2ccbcc409d0c3d304798d13a1417ac";
    };
}
