# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Term-termios";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/krunen/term-termios/archive/f4c84e1d95cb11be7655c489d2e470011ff269c8.tar.gz";
        sha256 = "c2e61db56dbe717ca3e780329e0c396af3d2bb2610c7397b60fc057cf5f0c19c";
    };
}
