# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Termbox";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JJ/JJATRIA/Perl6/Termbox-0.0.4.tar.gz";
        sha256 = "85379a92de23136f0073509856363b6b54db15f3a9c7f23ac4793bc1487982d4";
    };
}
