# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Term-Readsecret";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/titsuki/p6-Terminal-Readsecret/archive/d490c3260a15d7ebbe7f0732e6d7b02c282f5751.tar.gz";
        sha256 = "b7fe21e86d36add4dbfcea42cd6d1f65b8969c542df3e548d264a9443636796f";
    };
}
