# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Terminal-Caca";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/azawawi/perl6-terminal-caca/archive/fa7fb4eb448a835ab594d154fe465927c03b4136.tar.gz";
        sha256 = "4a83f03fbb22152e5b64cf07531fbc6713c1a5d4048a903b81ee2b38e68ee1f4";
    };
}
