# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Terminal-Getpass";
    buildDepends = [  ];
    depends = [ rakuPackages."Term-termios" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TI/TITSUKI/Perl6/Terminal-Getpass-0.0.6.tar.gz";
        sha256 = "d107c1baf9d4682acc72297ee04d13042d300ad1a3b1e58ed45d0a3bab55325f";
    };
}
