# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Color";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/H/HO/HOLLI/Perl6/Test-Color-1.001002.tar.gz";
        sha256 = "bbe6c38caeb38491499e59f7e802c12b0748cbe23a6212502ac23fb5ee7404fb";
    };
}
