# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Output";
    buildDepends = [  ];
    depends = [ rakuPackages."Test" ];
    src = fetchurl {
        url = "https://github.com/perl6-community-modules/perl6-Test-Output/archive/7f9350549b0643cad28b8e11a8875ed131cd7596.tar.gz";
        sha256 = "59a6e7b4640ec737290893cf2849024fc3762d64243a8cac43d9216fb5f4c5ae";
    };
}
