# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-META";
    buildDepends = [  ];
    depends = [ rakuPackages."License-SPDX" rakuPackages."META6" rakuPackages."Test" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Test-META-0.0.16.tar.gz";
        sha256 = "ccde57f8a98e46ce2aa25d8374d790662bf0821a8f3992a052ac7b63d2f2fd8b";
    };
}
