# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Script-Output";
    buildDepends = [  ];
    depends = [ rakuPackages."IO-Capture-Simple" rakuPackages."Pod-Load" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JM/JMERELO/Perl6/Test-Script-Output-0.0.4.tar.gz";
        sha256 = "ba96ede015626f57074188014ca81d1dc098da3cad7b70a976db173d7cccd4a3";
    };
}
