# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Declare";
    buildDepends = [  ];
    depends = [ rakuPackages."IO-Capture-Simple" rakuPackages."Test" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/D/DA/DARRENF/Perl6/Test-Declare-0.0.2.tar.gz";
        sha256 = "2e90407d3674db3e10404d66f87f76b051de539b499b59982d880bbcdbd4ec8a";
    };
}
