# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Testo";
    buildDepends = [  ];
    depends = [ rakuPackages."RakudoPrereq" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Testo/archive/1ee859e7f3953ffc6d73b47871a427feb5f38762.tar.gz";
        sha256 = "e86d472a16838fd3077b036cf85068bd501a713f00fde6521b94b86ac4d83322";
    };
}
