# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "TestML";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perl6-community-modules/testml-pm6/archive/37a6b615a93610942126e389222ae31d4b1d1824.tar.gz";
        sha256 = "0a9a1f7b953438e33eafe7ab8cd1482b106649fde7514707d422b7f0dd660691";
    };
}
