# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-IO-Socket-Async";
    buildDepends = [  ];
    depends = [ rakuPackages."OO-Monitors" ];
    src = fetchurl {
        url = "https://github.com/jnthn/p6-test-io-socket-async/archive/048c42d7af77dcd52e390c4f38839d23663e908e.tar.gz";
        sha256 = "81355b88ac1b41ac68811f52b98ed1f9f6d53a7073114c9970998f5e52071e67";
    };
}
