# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-SourceFiles";
    buildDepends = [  ];
    depends = [ rakuPackages."Test" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SA/SAMGWISE/Perl6/Test-SourceFiles-0.0.1.tar.gz";
        sha256 = "fca07cdeb35f641d674f9db46aa8a8bb4c6132420cecea1f64e4c4bc3063abca";
    };
}
