# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Declare";
    buildDepends = [  ];
    depends = [ rakuPackages."IO-Capture-Simple" rakuPackages."Test" ];
    src = fetchurl {
        url = "https://github.com/darrenf/p6-test-declare/archive/18b6bd209c218c10f251c68fdf90fc0b876ec120.tar.gz";
        sha256 = "fbb2ac385987ab02028cbe1dd3d235b686177bca3353ad0137dc3ec48c5f0da3";
    };
}
