# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Mock";
    buildDepends = [  ];
    depends = [ rakuPackages."OO-Monitors" ];
    src = fetchurl {
        url = "https://github.com/jnthn/test-mock/archive/1130427f4d9f3866fa39e113251bb142d7fa5cc8.tar.gz";
        sha256 = "88252a41b46077875baa703f563f9638b095eb78ebf6a51850973d52624b64d9";
    };
}
