# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Harness";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tadzik/Test-Harness/archive/4e1c88b10791821cadf5399109a4097fb2564a03.tar.gz";
        sha256 = "cde94159e554ca9eba4bf39b0771215c1717ec940ae98b949f91456921641626";
    };
}
