# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Deeply-Relaxed";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ppentchev/perl6-Test-Deeply-Relaxed/archive/bdc0e1316ee14f70ad039fd94133a0b48631733e.tar.gz";
        sha256 = "0a4e27b7527285313edfa6e89ac9de9ab2449de91d8dccbe9cf25bc741e8be25";
    };
}
