# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Performance";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Test-Performance-0.2.1.tar.gz";
        sha256 = "f95458b5a20c8809a09e9d993bb7c0552ec1f7ce052bafca4b5adf50e1080261";
    };
}
