# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Deeply-Relaxed";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ppentchev/perl6-Test-Deeply-Relaxed/archive/efda9fb38e299b878baa9b7402362cb36f844a39.tar.gz";
        sha256 = "7d63e732ae04383a22bdcc8eb82eaa5f534be0cff980717278ba04ae57dbe905";
    };
}
