# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Notice";
    buildDepends = [  ];
    depends = [ rakuPackages."Test" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Test-Notice/archive/f1a084282f7270bfbe858bd45afac0eddeb2f4e3.tar.gz";
        sha256 = "d9196a9b91f6a21d551851df26500d2ba9af75ab998ce61c4bd5dd27ef0caf7c";
    };
}
