# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Differences";
    buildDepends = [  ];
    depends = [ rakuPackages."Data-Dump" rakuPackages."Text-Diff" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RB/RBT/Perl6/Test-Differences-1.0.0.tar.gz";
        sha256 = "fdf18c04401e1eb1273837387861d5c7b972d2bb3def29fd45787a7f1c7a9391";
    };
}
