# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Test-Time";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-Scheduler" ];
    src = fetchurl {
        url = "https://github.com/FCO/test-time/archive/df899ad1deeb2c0909fedd763da48ba120b36fb8.tar.gz";
        sha256 = "59f92f652ef60caa0b3c653962a32a5025de9d1b17e001ecb05422d132245fdd";
    };
}
