# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Texas-To-Uni";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Altai-man/p6-Texas-To-Uni/archive/278b94efa286e4141221a26bd0e0567420931d99.tar.gz";
        sha256 = "a71e8a36ec7a5e298c3983037d48f8e228d55220e3674c12a5864306cebacc7c";
    };
}
