# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Diff-Sift4";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/masterduke17/text-diff-sift4/archive/e649f8c32e045c837212dc9ed14221c5df058427.tar.gz";
        sha256 = "1d5f41e76b0ae9334c0b9d213666c1e201e2f800b3439c66c8db21f4c59d58fc";
    };
}
