# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Levenshtein-Damerau";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ugexe/Perl6-Text--Levenshtein--Damerau/archive/fc4c5fad4bbdb324e68c221e24a585ff0028c39b.tar.gz";
        sha256 = "1772c715abadea858b992044bd12cc8679485568ddfbbbbed55989ace5334b69";
    };
}
