# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Utils";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TB/TBROWDER/Perl6/Text-Utils-Raku-2.1.1.tar.gz";
        sha256 = "2f318a00c8a0717fc924ddddd250da00654143477cc20a6c1cf65051f5efe205";
    };
}
