# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Names";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RI/RIBNOTTER/Perl6/Text-Names-0.0.2.tar.gz";
        sha256 = "c78515b4b9a04293b18a449be8cc115a1e3e9699a3a63f0c52518d5ef93e3cc5";
    };
}
