# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-UpsideDown";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/mcsnolte/Text-UpsideDown/archive/fd45300cebd54a12e446c1f40ac0574026e1f0af.tar.gz";
        sha256 = "9533d0bcc4fae9e8b7ccbfc341309d5c5cf57aa75d388be367c21bea3d168dcf";
    };
}
