# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-VimColour";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Temp" ];
    src = fetchurl {
        url = "https://github.com/stmuk/p6-Text-VimColour/archive/3e7f4e942cc6b88527838e1d32abaad200fc52fe.tar.gz";
        sha256 = "a37c80d4535fd026b7f655362757a793a824efba4be5a628359299c108fa2c65";
    };
}
