# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Utils";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TB/TBROWDER/Perl6/Text-Utils-Raku-2.0.1.tar.gz";
        sha256 = "bbfd5984a2b90b3b07497f41c2d1b663560db6f20a3107d8fda91fdfb38ab8eb";
    };
}
