# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-LDIF";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/slunski/perl6-text-ldif/archive/ebd6264f32414a331c97254c8632477da3647023.tar.gz";
        sha256 = "568d04d7e0b51af02d3f73738dd197d75f2fa293ee709fed22a9a11903fa8d3f";
    };
}
