# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-LDIF";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/Altai-man/perl6-text-ldif/archive/ce06acaa613efb41d43ac619ae491dafb30926c1.tar.gz";
        sha256 = "b7b21b97ba9f00e8b207a024e0c114adb8011a8cae0955bc3006a7326ae77dd0";
    };
}
