# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Abbrev";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/xfix/perl6-Text-Abbrev/archive/441c07e8bfe1ea0787afcee41f61ac826c894449.tar.gz";
        sha256 = "0eaed10870e1c38fadd131f6c0e634fa4608989d868ecec4232289cdf000317e";
    };
}
