# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Levenshtein";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Text-Levenshtein/archive/c7ad7810b91c9945f63cab807e4f5b7f70d7e547.tar.gz";
        sha256 = "c445deae821e31803a23279fb4734625d893fee25376b1333e9384a1afd7c9ed";
    };
}
