# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Center";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/thundergnat/Text-Center/archive/b6a28bd3ec62c3289ff8a0f0938f6391e36d4f88.tar.gz";
        sha256 = "f5365563b10a6a2e279752f40791f160cf14e66ab264910481d5056151fdd17e";
    };
}
