# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Markdown-Discount";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/hartenfels/Text-Markdown-Discount/archive/1c3fc36ba98ba664f117e1588a007ee68908568c.tar.gz";
        sha256 = "da39e0344557f7db1781a88366da013d4a9a1bfbdec6526c9015c54f2edeb68d";
    };
}
