# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Table-List";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/supernovus/perl6-text-table-list/archive/5d56135cac14961b39a57740b382080764199656.tar.gz";
        sha256 = "d76577ea0b740439dd4c65d2e175d7cc0496fdfd62ab959742d25c8c189947b4";
    };
}
