# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-LTSV";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/moznion/p6-Text-LTSV/archive/299f787c4855d9cc26017ab15e74e2645c4481d6.tar.gz";
        sha256 = "f8a58226abb30cd1d23570c28ab5fabbed02a356f1cad02a2d5f2988ee775620";
    };
}
