# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-Table-Simple";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/ugexe/Perl6-Text--Table--Simple/archive/a73d9ddb0d52b1b9bf3f7aa4e0b138a489201689.tar.gz";
        sha256 = "e3ead9203e89d31eaebbdccdec7da9ae8cf92c44da768f70d42ed2ffb4ff139a";
    };
}
