# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Text-BorderedBlock";
    buildDepends = [  ];
    depends = [ rakuPackages."Terminal-ANSIColor" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/T/TY/TYIL/Perl6/Text-BorderedBlock-0.1.0.tar.gz";
        sha256 = "8526a320694d1645b55d9583d967fe3a7fffb60109c4881a04f20efa96228756";
    };
}
