# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tie-StdHash";
    buildDepends = [  ];
    depends = [ rakuPackages."P5tie" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Tie-StdHash-0.0.6.tar.gz";
        sha256 = "404948f99e205117a8d9b26f71d0241f46ec8e7707948852f7dfd90b287e7a17";
    };
}
