# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tie-StdArray";
    buildDepends = [  ];
    depends = [ rakuPackages."P5tie" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Tie-StdArray-0.0.5.tar.gz";
        sha256 = "25ef1a8061d28dc372c36cec930536173661a4857be94f909ae048b6f50e05fc";
    };
}
