# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tie-Array";
    buildDepends = [  ];
    depends = [ rakuPackages."P5tie" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Tie-Array-0.0.6.tar.gz";
        sha256 = "01339f8cc05accc669da8b60011a163946856abbb76e58f2a8846e06054c6d34";
    };
}
