# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tie-Hash";
    buildDepends = [  ];
    depends = [ rakuPackages."P5tie" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Tie-Hash-0.0.6.tar.gz";
        sha256 = "a808b458e78517c5cc1008db2cc47aab66cefd30832cd58a2c06a105bbaae2ec";
    };
}
