# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Time-Crontab";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" ];
    src = fetchurl {
        url = "https://github.com/ufobat/p6-time-crontab/archive/f93a9af7923868401f2884f1599edbaf34acd00d.tar.gz";
        sha256 = "d3d9eae55cae93a15712b5d0deafc8a07c64894eba59b618be8326429bbb87cd";
    };
}
