# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tinky-Hash";
    buildDepends = [  ];
    depends = [ rakuPackages."Tinky" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/tinky-hash-0.4.2.tar.gz";
        sha256 = "8e360df12f4e6347d7bd21c60540c4b63cbf1f9355f593dd3bf4823d838a97c3";
    };
}
