# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tinky";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Tinky-0.0.8.tar.gz";
        sha256 = "4f24d4e3cfb0795c4d36f7ef34785fe74c0347bd177b4917568eb23be3aac8ba";
    };
}
