# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "TinyCC";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/cygx/p6-tinycc/archive/a090e663f284a2aee73872ffbc92637bcbd62310.tar.gz";
        sha256 = "1f91bb8e1368a4521b9bde4bcef20191690f6ff01a215420dc48a1d4c506ac1b";
    };
}
