# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "TinyID";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/bbkr/TinyID/archive/6693e35619df4367ab09d6e7185f261f9aa33361.tar.gz";
        sha256 = "1841f346e0bd468276a34125dad6a2a0d62f28baa6979851dc091c76f163d363";
    };
}
