# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Today";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Today-0.0.2.tar.gz";
        sha256 = "a3c1313d42bd3212dcd7e1409f2051028ab758c738e29d3cc9ce7564aabff12e";
    };
}
