# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tomty";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Directory-Tree" rakuPackages."Sparrow6" rakuPackages."YAMLish" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/ME/MELEZHIK/Perl6/Tomty-0.0.9.tar.gz";
        sha256 = "6de02ab99090aa24a9800570300280b41a38eddd3329b2de9cb88105544f8ccf";
    };
}
