# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Trait-Traced";
    buildDepends = [  ];
    depends = [ rakuPackages."Kind" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Trait-Traced-0.3.1.tar.gz";
        sha256 = "03fdcd0de1b60b72a40f3ab84cfe60459a0d50dcdc791bd4df6b9f65fb3f41d8";
    };
}
