# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Trait-Env";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SC/SCIMON/Perl6/Trait-Env-1.0.1.tar.gz";
        sha256 = "3fd6ad888e73f4b771c38cde682142be6884049e8655d4f8bee8782204f4e01b";
    };
}
