# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Trait-Env";
    buildDepends = [  ];
    depends = [ rakuPackages."JSON-Tiny" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/S/SC/SCIMON/Perl6/Trait-Env-1.1.0.tar.gz";
        sha256 = "9a28f87038c7296995875bf2c2549d3e8b65203cfbd7fb12764a846f4fab27e9";
    };
}
