# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Tuple";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/Tuple-0.0.5.tar.gz";
        sha256 = "184913de6d1380573eb76fb805257f9e396eea8a79a9062747a2930c720842e9";
    };
}
