# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Twitter";
    buildDepends = [  ];
    depends = [ rakuPackages."Base64" rakuPackages."Digest-HMAC" rakuPackages."Digest-SHA" rakuPackages."HTTP-Tinyish" rakuPackages."JSON-Fast" rakuPackages."Subset-Helper" rakuPackages."URI" rakuPackages."URI-Escape" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-Twitter/archive/631134cd05ee895d367beec6356791c4b5d7a43c.tar.gz";
        sha256 = "5ce2a524f929557fddbea372ff0295806fd378d95d313e2405859b0259c42aee";
    };
}
