# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "TXN-Parser";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest-xxHash" ];
    src = fetchurl {
        url = "https://github.com/atweiden/txn-parser/archive/464968e0d86630d6bb89662a5187f69ce77539be.tar.gz";
        sha256 = "bcc744098b7cd7885a0f538c75894ceda374a28eb2cb3e95e183e4b09214139f";
    };
}
