# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Type-EnumHOW";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/K/KA/KAIEPI/Perl6/Type-EnumHOW-0.0.2.tar.gz";
        sha256 = "a2f9f2a33ad232770f8836af26fb39c21480a593c99aa6052b6f8502e955d699";
    };
}
