# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Typesafe-XHTML-Writer";
    buildDepends = [  ];
    depends = [ rakuPackages."Typesafe-HTML" rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/gfldex/perl6-typesafe-xhtml-writer/archive/f534127581c4de2589de0fef342e60702f346570.tar.gz";
        sha256 = "14ca20ccfdab9ee3705e74333591b1046c2a601092d412a45a72f191acd1c8cf";
    };
}
