# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Typed-Subroutines";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tadzik/Typed-Subroutines/archive/ce6c6e2386ba40dfa03890d14f8df9f60a53ad12.tar.gz";
        sha256 = "7ec535d05c046a4388aa58c514ba8108a6a010ea79c738f72f849992d3f46b53";
    };
}
