# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Typesafe-HTML";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/gfldex/perl6-typesafe-html/archive/2a0933e6a8ce1969a5d73eaa1352a64b87e18cbb.tar.gz";
        sha256 = "5112be39d9a9b1d530f3d4a9a197d4eefd9e80070b5675cd2e60844b1e0678af";
    };
}
