# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Unicode-UTF8-Parser";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/krunen/unicode-utf8-parser/archive/be599589c64e14b1f6e9f5e9dab444cfd55adbc3.tar.gz";
        sha256 = "c414b4e76d47a73f840fd7ae56f92ad2145887163173e8106048303039ade522";
    };
}
