# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Unicode-PRECIS";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/M/MA/MARTIMM/Perl6/unicode-precis-0.5.1.tar.gz";
        sha256 = "5de34d35b891684f2869aa46cf101a1c67b37d0319a8766a19069bcb371e6411";
    };
}
