# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "UNIX-Daemonize";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/hipek8/p6-UNIX-Daemonize/archive/044a39528a21da78010f26f49d39b24aaf233450.tar.gz";
        sha256 = "4ce839979349cd569f179b5999d6446f2d381fead88bbad8df3769459b06d930";
    };
}
