# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "unprint";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/unprint-0.0.2.tar.gz";
        sha256 = "9e8ed728e604a5b9a6e17d6d259035ded9f90443252b029a2c437d8473c2b05b";
    };
}
