# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "unprint";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/unprint-0.0.3.tar.gz";
        sha256 = "4187204e9b198da3da0227b585238c85b47075a4c90c2ca9677c9e1c7ffb3ccc";
    };
}
