# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "URI-FetchFile";
    buildDepends = [  ];
    depends = [ rakuPackages."File-Which" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/URI-FetchFile-0.0.3.tar.gz";
        sha256 = "44eda7abd558de7527c4f341f594289935317e1b8b257389623e51717964e649";
    };
}
