# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "URI-Template";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/URI-Template-0.0.7.tar.gz";
        sha256 = "9417259e0b321f1f8d5377b363131ce1793509a34da8fbd7abd5f1a37e1f31cb";
    };
}
