# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "URI-Encode";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perl6-community-modules/URI-Encode/archive/5f4d747d38a16d1f8d1e572066ec9ef58323c9dc.tar.gz";
        sha256 = "2ae278b8e641ad1949aefbc7ef2d1124bf6105e4b6b99548cdd3a78ba98514d3";
    };
}
