# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "URI";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/perl6-community-modules/uri/archive/f8b08667b7c9e7c95a1aa6629ef0f0c615296ba1.tar.gz";
        sha256 = "ecfe88b1ac842e82c19f1c4426b9eb376e2579d5f32f72c53c9c9d69b56fdc33";
    };
}
