# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "US-ASCII";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/R/RO/RONALDWS/Perl6/US-ASCII-0.6.6.tar.gz";
        sha256 = "725531ac7cbe3a5a93635c0cdc1a5d9388886f2542ba4dfdd7a186f8b6403c79";
    };
}
