# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Util-Bitfield";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/Util-Bitfield-0.0.4.tar.gz";
        sha256 = "724a289078d6e25f4fb0f894cf5f8dc553d2cceda8a3e504e7a26d7d7af3398f";
    };
}
