# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "UUID";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-UUID/archive/26cb869622057da286b1b60780ee39e3b4ece0a4.tar.gz";
        sha256 = "363d5d5d76178644e0fa43736b55513e039d1101e84882d7bc63e4a3dbd1cace";
    };
}
