# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "ValueType";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/ValueType-0.0.2.tar.gz";
        sha256 = "1a71d87d0c158bbe0e4828b95d646e48061ac6671a62f79448804862e7f3ba4e";
    };
}
