# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "vars";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/E/EL/ELIZABETH/Perl6/vars-0.0.4.tar.gz";
        sha256 = "d8840265c1ad853feff0568465cf89c6776ee14ee18eae87168913bce818c4c7";
    };
}
