# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Verge-RPC-Client";
    buildDepends = [  ];
    depends = [ rakuPackages."Base64-Native" rakuPackages."Data-Dump" rakuPackages."JSON-Fast" rakuPackages."LWP-Simple" rakuPackages."Slippy-Semilist" rakuPackages."WWW" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/B/BR/BRAKMIC/Perl6/Verge-RPC-Client-0.0.2.tar.gz";
        sha256 = "818608d20ebbeb6eca02f645b7f125580e17fcb428878e2146fc8518885d5e06";
    };
}
