# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Web-App-MVC";
    buildDepends = [  ];
    depends = [ rakuPackages."DB-Model-Easy" rakuPackages."HTTP-Easy" rakuPackages."JSON-Tiny" rakuPackages."SCGI" rakuPackages."Web" rakuPackages."Web-Template" ];
    src = fetchurl {
        url = "https://github.com/supernovus/perl6-web-app-mvc/archive/6d5dfb7ef39ee2bfb377db2b8c0ecbe5f30aa293.tar.gz";
        sha256 = "7a6466490a16707b1daee2fcdaf2d42b634cb158231fa87cb1fa649aa7a983e6";
    };
}
