# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Web-RF";
    buildDepends = [  ];
    depends = [ rakuPackages."Crust" rakuPackages."Path-Router" rakuPackages."URI-Escape" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-Web-RF/archive/d5474b597fbf631c9be5def9ad43a83ecfbd95e0.tar.gz";
        sha256 = "594a97b98faa308d013660b11f2d4296274c8157055262979f53060c181eb524";
    };
}
