# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Web";
    buildDepends = [  ];
    depends = [ rakuPackages."FastCGI" rakuPackages."HTTP-Easy-PSGI" rakuPackages."MIME-Types" rakuPackages."PSGI" rakuPackages."SCGI" ];
    src = fetchurl {
        url = "https://github.com/supernovus/perl6-web/archive/4c04fa3bb65d15eb35edb8073c3c1e2ce143be5d.tar.gz";
        sha256 = "2fcd558ec710d63cf91d844c2e35de68f4f7d241248fd30073009963edc6d63b";
    };
}
