# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WebService-GitHub";
    buildDepends = [  ];
    depends = [ rakuPackages."Cache-LRU" rakuPackages."HTTP-UserAgent" rakuPackages."IO-Socket-SSL" rakuPackages."JSON-Fast" rakuPackages."MIME-Base64" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://github.com/fayland/perl6-WebService-GitHub/archive/72ef9499faea03dc3570927be39607c643d5b119.tar.gz";
        sha256 = "133dccb4f27f665678d80fdefb2ddc9a8f111a23bf25429541be46b679249dd9";
    };
}
