# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WebService-AWS-S3";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest" rakuPackages."Digest-HMAC" rakuPackages."HTTP-UserAgent" rakuPackages."IO-Socket-SSL" rakuPackages."JSON-Fast" rakuPackages."Test" rakuPackages."URI" rakuPackages."URI-Encode" rakuPackages."XML-Class" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/B/BD/BDUGGAN/Perl6/WebService-AWS-S3-0.0.3.tar.gz";
        sha256 = "3683daae6ec9b8702cbc0a62cb3c3caf4748ad5b1bea1e1f447d60599c7b3f43";
    };
}
