# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WebSocket";
    buildDepends = [  ];
    depends = [ rakuPackages."Digest" rakuPackages."MIME-Base64" ];
    src = fetchurl {
        url = "https://github.com/tokuhirom/p6-Protocol-WebSocket/archive/ca9ac790a556e6dc2a0c7e991c5c8717f1f1c445.tar.gz";
        sha256 = "a9a23a0129100da1703c2a98ce66253b487a86ea6c2e0838a395384e4154e169";
    };
}
