# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WebService-GoogleDyDNS";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-UserAgent" rakuPackages."WebService-HazIP" ];
    src = fetchurl {
        url = "https://github.com/cbk/WebService-GoogleDyDNS/archive/7f14c8e8d6216f1c525bf0403b35ba8b85782428.tar.gz";
        sha256 = "8e2d24a1039587f8c7df0ebdb86f078949b7062674d19714bb8c157c788100cb";
    };
}
