# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WebService-Soundcloud";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-UserAgent" rakuPackages."IO-Socket-SSL" rakuPackages."JSON-Class" rakuPackages."JSON-Fast" rakuPackages."JSON-Name" rakuPackages."URI" rakuPackages."URI-Template" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/WebService-Soundcloud-0.0.8.tar.gz";
        sha256 = "02ac38dac9f8d05749ef8df0ef79c4df8218003b1ec4fb93ed92ea71aef95e45";
    };
}
