# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WhereList";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-WhereList/archive/da0af09ba66fe52660a8be162d3f995e32607fb6.tar.gz";
        sha256 = "4a4e5c5f1128fddfc7cc0eba21a3fdc4efa521bfc6112aab53c7ff15e05b6b37";
    };
}
