# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WWW-vlc-Remote";
    buildDepends = [  ];
    depends = [ rakuPackages."DOM-Tiny" rakuPackages."HTTP-UserAgent" rakuPackages."URI-Encode" ];
    src = fetchurl {
        url = "https://github.com/zoffixznet/perl6-WWW-vlc-Remote/archive/f74c287ddfe64822bee052f4370617ee23455adc.tar.gz";
        sha256 = "3f13f3705811ddb79d2b1b1bf5c398291d4f87ecfd154aa31a60c3395530e44d";
    };
}
