# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "WWW-SilverGoldBull";
    buildDepends = [  ];
    depends = [ rakuPackages."HTTP-UserAgent" rakuPackages."JSON-Fast" rakuPackages."URI" ];
    src = fetchurl {
        url = "https://github.com/dboys/p6-WWW-SilverGoldBull/archive/9c3f944c04aaac65b3dbede34c734456e26cd8f0.tar.gz";
        sha256 = "a19e74214e3ca9f7b22f39bfeb84ed5408e11d370ba0467b0630e2f6b5b60ac2";
    };
}
