# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "X-Protocol";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/skids/perl6xproto/archive/6750e05da9b70b180eeaebaeb9e15d35d5856cd3.tar.gz";
        sha256 = "36fb5c3da764c21304305de48a67fc917e5be53e1ae370a9a96672b8c0dbe2a1";
    };
}
