# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "XML-Class";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/XML-Class-0.0.7.tar.gz";
        sha256 = "3788cacc05f549bf7e5c7d22c0204ca68fdd90f9b4803c33b2241bf77be01db2";
    };
}
