# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "XML-Canonical";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/retupmoca/P6-XML-Canonical/archive/ad229190f7928e7777227e7983760ebe9335373f.tar.gz";
        sha256 = "592ae7b613a5d6df5bdb5626d2ef12a499b4f9938164d68f7c365ce825c043e4";
    };
}
