# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "XML-XPath";
    buildDepends = [  ];
    depends = [ rakuPackages."Test-META" rakuPackages."XML" ];
    src = fetchurl {
        url = "https://github.com/ufobat/p6-XML-XPath/archive/be346ab137c977ea7a9e9006db953692ea807147.tar.gz";
        sha256 = "a99a82fffee550650df82dd14fd58eeb67d35f210084f37e9fdae7bb2cad187f";
    };
}
