# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "XML-Class";
    buildDepends = [  ];
    depends = [ rakuPackages."XML" ];
    src = fetchurl {
        url = "https://www.cpan.org/authors/id/J/JS/JSTOWE/Perl6/XML-Class-0.0.8.tar.gz";
        sha256 = "ed0e11b38423cec7343d8ac13da000fc3dc83c0804d2263efcda7dda077f88f2";
    };
}
