# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "XML";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/supernovus/exemel/archive/417f63773db8cf9e000a9839e21e4cfffbf677e6.tar.gz";
        sha256 = "11669e661aee782cf2154b595a6a0112ba817f8c2299538c391c792340197720";
    };
}
