# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "YAMLish";
    buildDepends = [  ];
    depends = [ rakuPackages."MIME-Base64" ];
    src = fetchurl {
        url = "https://github.com/leont/yamlish/archive/59923fbf0d6864baa72f0310549ca88903900ccd.tar.gz";
        sha256 = "2f38947efa69c81c074cf64248eba39372688ea4e9eb9badc1c75683428a3c07";
    };
}
