# !!! GENERATED BY tools/generate-nix.pl DO NOT EDIT
{ fetchurl, lib, rakuPackage, rakuPackages,
 }:
rakuPackage {
    name = "Zodiac-Chinese";
    buildDepends = [  ];
    depends = [  ];
    src = fetchurl {
        url = "https://github.com/tmtvl/Zodiac-Chinese/archive/bc423017e8211eb4915bc8944bcf1b2dc0290a11.tar.gz";
        sha256 = "251a0e2151ef0369a1787dda882c8928aef142dc47fed9864ddf20a4e2279e60";
    };
}
